/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Spring Boot 3.5
 *
 * Domain Model:
 * Banking Industry Domain Model
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone National Bank Confidential
 *
 * 2026 Turnstone National Bank
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone National Bank - General Release
 */
package com.harbormaster.projector;

import java.util.*;
import java.util.stream.Collectors;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.stereotype.Component;

import org.springframework.data.domain.Pageable;
import org.springframework.data.domain.PageRequest;
import org.springframework.stereotype.Component;

import com.harbormaster.api.*;
import com.harbormaster.entity.*;
import com.harbormaster.exception.*;
import com.harbormaster.repository.*;

/**
 * <h2>AccountEntity Projector</h2>
 * <p>
 * The Account Entity Projector is responsible for maintaining the write model for
 * Account entities. It subscribes to domain events published by the Account
 * Aggregate and updates query-optimized projections used by REST APIs,
 * dashboards, and reporting services.
 * </p>
 * <p>
 * A Projector contains no business logic and never validates commands or
 * modifies the authoritative state of the domain.
 * </p>
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Spring Boot 3.5</td></tr>
 *          <tr><td>published</td><td>09/08/2026</td></tr>
 *          <tr><td>design pattern</td><td>ServiceLayer</td></tr>
 *          <tr><td>architecture style</td><td>Layered</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>Banking Industry Domain Model</td></tr>
 *          <tr><td>description</td><td>HCIDL model capturing core banking, payments, lending, cards, KYC, and FX capabilities.</td></tr>
 *          <tr><td>industry</td><td>Banking</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Services Used</h3>
 *
 *      <ul>
 *          <li>AccountRepository</li>
 *          <li>ProjectorRegistry</li>
 *      </ul>
 *
 * <p>@author Harbormaster Dev Team</p>
 */
@Component("account-entity-projector")
public class AccountEntityProjector implements EntityProjector<Account>{
		
	// core constructor
	public AccountEntityProjector(ProjectorRegistry registry,
										AccountRepository repository ) {
        this.registry 	= registry;
		this.repository = repository;
    }

	@Override
	public Class<Account> getEntityClass() {
		return Account.class;
	}

    /*
	 * Insert a Account
	 * 
     * @param	entity Account
     */
    public Account create( Account entity) {
	    LOGGER.info("creating " + entity.toString() );
	   
    	// ------------------------------------------
    	// persist a new one
    	// ------------------------------------------ 
	    return repository.save(entity);
        
    }

	/*
	 * Update a Account
	 * 
     * @param	entity Account
     */
    public Account update( Account entity) {
	    LOGGER.info("updating " + entity.toString() );

	    // ------------------------------------------
    	// save with an existing instance
    	// ------------------------------------------ 
		return repository.save(entity);

    }
    
	/*
	 * Delete a Account
	 * 
     * @param	id		UUID
     */
    public Account delete( UUID id ) {
	    LOGGER.info("deleting " + id.toString() );

    	// ------------------------------------------
    	// locate the entity by the provided id
    	// ------------------------------------------
	    Account entity = repository.findById(id).get();
	    
    	// ------------------------------------------
    	// delete what is discovered 
    	// ------------------------------------------
    	repository.delete( entity );
    	
    	return entity;
    }    

    /*
     * Assign a Bank
     * 
     * @param	parentId	UUID
     * @param	assignment 	Bank 
     * @return	Account
     */
    public Account assignBank( UUID parentId, Bank assignment ) {
	    LOGGER.info("assigning Bank as " + assignment.toString() );

	    Account parentEntity = repository.findById( parentId ).get();
	    assignment = registry.project( Bank.class, assignment.getBankId());

	    // ------------------------------------------
		// assign the Bank to the parent entity
		// ------------------------------------------ 
	    parentEntity.setBank( assignment );

	    // ------------------------------------------
    	// save the parent entity
    	// ------------------------------------------ 
	    repository.save(parentEntity);
        
	    return parentEntity;
    }
    

	/*
	 * Unassign the Bank
	 * 
	 * @param	parentId		UUID
	 * @return	Account
	 */
	public Account unAssignBank( UUID parentId ) {
		Account parentEntity = repository.findById(parentId).get();

		LOGGER.info("unAssigning Bank on " + parentEntity.toString() );
		
	    // ------------------------------------------
		// null out the Bank on the parent entithy
		// ------------------------------------------     
	    parentEntity.setBank(null);

	    // ------------------------------------------
		// save the parent entity
		// ------------------------------------------ 
	    repository.save(parentEntity);
    
	    return parentEntity;
	}

    /*
     * Assign a Branch
     * 
     * @param	parentId	UUID
     * @param	assignment 	Branch 
     * @return	Account
     */
    public Account assignBranch( UUID parentId, Branch assignment ) {
	    LOGGER.info("assigning Branch as " + assignment.toString() );

	    Account parentEntity = repository.findById( parentId ).get();
	    assignment = registry.project( Branch.class, assignment.getBranchId());

	    // ------------------------------------------
		// assign the Branch to the parent entity
		// ------------------------------------------ 
	    parentEntity.setBranch( assignment );

	    // ------------------------------------------
    	// save the parent entity
    	// ------------------------------------------ 
	    repository.save(parentEntity);
        
	    return parentEntity;
    }
    

	/*
	 * Unassign the Branch
	 * 
	 * @param	parentId		UUID
	 * @return	Account
	 */
	public Account unAssignBranch( UUID parentId ) {
		Account parentEntity = repository.findById(parentId).get();

		LOGGER.info("unAssigning Branch on " + parentEntity.toString() );
		
	    // ------------------------------------------
		// null out the Branch on the parent entithy
		// ------------------------------------------     
	    parentEntity.setBranch(null);

	    // ------------------------------------------
		// save the parent entity
		// ------------------------------------------ 
	    repository.save(parentEntity);
    
	    return parentEntity;
	}

    /*
     * Assign a Product
     * 
     * @param	parentId	UUID
     * @param	assignment 	BankingProduct 
     * @return	Account
     */
    public Account assignProduct( UUID parentId, BankingProduct assignment ) {
	    LOGGER.info("assigning Product as " + assignment.toString() );

	    Account parentEntity = repository.findById( parentId ).get();
	    assignment = registry.project( BankingProduct.class, assignment.getBankingProductId());

	    // ------------------------------------------
		// assign the Product to the parent entity
		// ------------------------------------------ 
	    parentEntity.setProduct( assignment );

	    // ------------------------------------------
    	// save the parent entity
    	// ------------------------------------------ 
	    repository.save(parentEntity);
        
	    return parentEntity;
    }
    

	/*
	 * Unassign the Product
	 * 
	 * @param	parentId		UUID
	 * @return	Account
	 */
	public Account unAssignProduct( UUID parentId ) {
		Account parentEntity = repository.findById(parentId).get();

		LOGGER.info("unAssigning Product on " + parentEntity.toString() );
		
	    // ------------------------------------------
		// null out the Product on the parent entithy
		// ------------------------------------------     
	    parentEntity.setProduct(null);

	    // ------------------------------------------
		// save the parent entity
		// ------------------------------------------ 
	    repository.save(parentEntity);
    
	    return parentEntity;
	}


    /*
     * Add to the Owners
     * 
     * @param	parentID	UUID
     * @param	addTo		childType
     * @return	Account
     */
    public Account addToOwners( UUID parentId, Customer addTo ) {
	    LOGGER.info("handling AssignOwnersToAccountEvent - " );
	    
	    Account parentEntity = repository.findById(parentId).get();
	    Customer child = registry.project( Customer.class, addTo.getCustomerId());
	    
	    parentEntity.getOwners().add( child );

	    // ------------------------------------------
    	// save 
    	// ------------------------------------------ 
	    repository.save(parentEntity);
        
	    return parentEntity;
    }
    

    /*
     * Remove from the Owners
     * 
     * @param	parentID	UUID
     * @param	removeFrom	childType
     * @return	Account
     */
	public Account removeFromOwners( UUID parentId, Customer removeFrom ) {
	    LOGGER.info("handling RemoveOwnersFromAccountEvent " );
	
	    Account parentEntity = repository.findById(parentId).get();
	    Customer child = registry.project( Customer.class, removeFrom.getCustomerId());
	    
	    parentEntity.getOwners().remove( child );
	
	    // ------------------------------------------
		// save
		// ------------------------------------------ 
	    update(parentEntity);
	    
	    return parentEntity;
	}

    /*
     * Add to the Transactions
     * 
     * @param	parentID	UUID
     * @param	addTo		childType
     * @return	Account
     */
    public Account addToTransactions( UUID parentId, Transaction addTo ) {
	    LOGGER.info("handling AssignTransactionsToAccountEvent - " );
	    
	    Account parentEntity = repository.findById(parentId).get();
	    Transaction child = registry.project( Transaction.class, addTo.getTransactionId());
	    
	    parentEntity.getTransactions().add( child );

	    // ------------------------------------------
    	// save 
    	// ------------------------------------------ 
	    repository.save(parentEntity);
        
	    return parentEntity;
    }
    

    /*
     * Remove from the Transactions
     * 
     * @param	parentID	UUID
     * @param	removeFrom	childType
     * @return	Account
     */
	public Account removeFromTransactions( UUID parentId, Transaction removeFrom ) {
	    LOGGER.info("handling RemoveTransactionsFromAccountEvent " );
	
	    Account parentEntity = repository.findById(parentId).get();
	    Transaction child = registry.project( Transaction.class, removeFrom.getTransactionId());
	    
	    parentEntity.getTransactions().remove( child );
	
	    // ------------------------------------------
		// save
		// ------------------------------------------ 
	    update(parentEntity);
	    
	    return parentEntity;
	}

    /*
     * Add to the Statements
     * 
     * @param	parentID	UUID
     * @param	addTo		childType
     * @return	Account
     */
    public Account addToStatements( UUID parentId, AccountStatement addTo ) {
	    LOGGER.info("handling AssignStatementsToAccountEvent - " );
	    
	    Account parentEntity = repository.findById(parentId).get();
	    AccountStatement child = registry.project( AccountStatement.class, addTo.getAccountStatementId());
	    
	    parentEntity.getStatements().add( child );

	    // ------------------------------------------
    	// save 
    	// ------------------------------------------ 
	    repository.save(parentEntity);
        
	    return parentEntity;
    }
    

    /*
     * Remove from the Statements
     * 
     * @param	parentID	UUID
     * @param	removeFrom	childType
     * @return	Account
     */
	public Account removeFromStatements( UUID parentId, AccountStatement removeFrom ) {
	    LOGGER.info("handling RemoveStatementsFromAccountEvent " );
	
	    Account parentEntity = repository.findById(parentId).get();
	    AccountStatement child = registry.project( AccountStatement.class, removeFrom.getAccountStatementId());
	    
	    parentEntity.getStatements().remove( child );
	
	    // ------------------------------------------
		// save
		// ------------------------------------------ 
	    update(parentEntity);
	    
	    return parentEntity;
	}

    /*
     * Add to the StandingInstructions
     * 
     * @param	parentID	UUID
     * @param	addTo		childType
     * @return	Account
     */
    public Account addToStandingInstructions( UUID parentId, StandingInstruction addTo ) {
	    LOGGER.info("handling AssignStandingInstructionsToAccountEvent - " );
	    
	    Account parentEntity = repository.findById(parentId).get();
	    StandingInstruction child = registry.project( StandingInstruction.class, addTo.getStandingInstructionId());
	    
	    parentEntity.getStandingInstructions().add( child );

	    // ------------------------------------------
    	// save 
    	// ------------------------------------------ 
	    repository.save(parentEntity);
        
	    return parentEntity;
    }
    

    /*
     * Remove from the StandingInstructions
     * 
     * @param	parentID	UUID
     * @param	removeFrom	childType
     * @return	Account
     */
	public Account removeFromStandingInstructions( UUID parentId, StandingInstruction removeFrom ) {
	    LOGGER.info("handling RemoveStandingInstructionsFromAccountEvent " );
	
	    Account parentEntity = repository.findById(parentId).get();
	    StandingInstruction child = registry.project( StandingInstruction.class, removeFrom.getStandingInstructionId());
	    
	    parentEntity.getStandingInstructions().remove( child );
	
	    // ------------------------------------------
		// save
		// ------------------------------------------ 
	    update(parentEntity);
	    
	    return parentEntity;
	}

    /*
     * Add to the FeeCharges
     * 
     * @param	parentID	UUID
     * @param	addTo		childType
     * @return	Account
     */
    public Account addToFeeCharges( UUID parentId, FeeCharge addTo ) {
	    LOGGER.info("handling AssignFeeChargesToAccountEvent - " );
	    
	    Account parentEntity = repository.findById(parentId).get();
	    FeeCharge child = registry.project( FeeCharge.class, addTo.getFeeChargeId());
	    
	    parentEntity.getFeeCharges().add( child );

	    // ------------------------------------------
    	// save 
    	// ------------------------------------------ 
	    repository.save(parentEntity);
        
	    return parentEntity;
    }
    

    /*
     * Remove from the FeeCharges
     * 
     * @param	parentID	UUID
     * @param	removeFrom	childType
     * @return	Account
     */
	public Account removeFromFeeCharges( UUID parentId, FeeCharge removeFrom ) {
	    LOGGER.info("handling RemoveFeeChargesFromAccountEvent " );
	
	    Account parentEntity = repository.findById(parentId).get();
	    FeeCharge child = registry.project( FeeCharge.class, removeFrom.getFeeChargeId());
	    
	    parentEntity.getFeeCharges().remove( child );
	
	    // ------------------------------------------
		// save
		// ------------------------------------------ 
	    update(parentEntity);
	    
	    return parentEntity;
	}



    /**
     * Method to retrieve the Account via an FindAccountQuery
     * @return 	query	FindAccountQuery
     */
    @SuppressWarnings("unused")
    public Account find( UUID id ) {
    	LOGGER.info("handling find using " + id.toString() );
    	try {
    		return repository.findById(id).get();
    	}
    	catch( IllegalArgumentException exc ) {
    		LOGGER.warn( "Failed to find a Account - {0}", exc.getMessage() );
    	}
    	return null;
    }
    
    /**
     * Method to retrieve a collection of all Accounts
     *
     * @param	query	FindAllAccountQuery 
     * @return 	List<Account> 
     */
    @SuppressWarnings("unused")
    public List<Account> findAll( FindAllAccountQuery query ) {
    	LOGGER.info("handling findAll using " + query.toString() );
    	try {
    		return repository.findAll();
    	}
    	catch( IllegalArgumentException exc ) {
    		LOGGER.warn( "Failed to find all Account - {0}", exc.getMessage() );
    	}
    	return null;
    }


    //--------------------------------------------------
    // attributes
    // --------------------------------------------------
	@Autowired
    protected final AccountRepository repository;
	protected final ProjectorRegistry registry;


    private static final Logger LOGGER 	= LoggerFactory.getLogger(AccountEntityProjector.class.getName());

}
