/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Spring Boot 3.5
 *
 * Domain Model:
 * Banking Industry Domain Model
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone National Bank Confidential
 *
 * 2026 Turnstone National Bank
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone National Bank - General Release
 */
package com.harbormaster.projector;

import java.util.*;
import java.util.stream.Collectors;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.stereotype.Component;

import org.springframework.data.domain.Pageable;
import org.springframework.data.domain.PageRequest;
import org.springframework.stereotype.Component;

import com.harbormaster.api.*;
import com.harbormaster.entity.*;
import com.harbormaster.exception.*;
import com.harbormaster.repository.*;

/**
 * <h2>AccountStatementEntity Projector</h2>
 * <p>
 * The AccountStatement Entity Projector is responsible for maintaining the write model for
 * AccountStatement entities. It subscribes to domain events published by the AccountStatement
 * Aggregate and updates query-optimized projections used by REST APIs,
 * dashboards, and reporting services.
 * </p>
 * <p>
 * A Projector contains no business logic and never validates commands or
 * modifies the authoritative state of the domain.
 * </p>
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Spring Boot 3.5</td></tr>
 *          <tr><td>published</td><td>09/08/2026</td></tr>
 *          <tr><td>design pattern</td><td>ServiceLayer</td></tr>
 *          <tr><td>architecture style</td><td>Layered</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>Banking Industry Domain Model</td></tr>
 *          <tr><td>description</td><td>HCIDL model capturing core banking, payments, lending, cards, KYC, and FX capabilities.</td></tr>
 *          <tr><td>industry</td><td>Banking</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Services Used</h3>
 *
 *      <ul>
 *          <li>AccountStatementRepository</li>
 *          <li>ProjectorRegistry</li>
 *      </ul>
 *
 * <p>@author Harbormaster Dev Team</p>
 */
@Component("accountStatement-entity-projector")
public class AccountStatementEntityProjector implements EntityProjector<AccountStatement>{
		
	// core constructor
	public AccountStatementEntityProjector(ProjectorRegistry registry,
										AccountStatementRepository repository ) {
        this.registry 	= registry;
		this.repository = repository;
    }

	@Override
	public Class<AccountStatement> getEntityClass() {
		return AccountStatement.class;
	}

    /*
	 * Insert a AccountStatement
	 * 
     * @param	entity AccountStatement
     */
    public AccountStatement create( AccountStatement entity) {
	    LOGGER.info("creating " + entity.toString() );
	   
    	// ------------------------------------------
    	// persist a new one
    	// ------------------------------------------ 
	    return repository.save(entity);
        
    }

	/*
	 * Update a AccountStatement
	 * 
     * @param	entity AccountStatement
     */
    public AccountStatement update( AccountStatement entity) {
	    LOGGER.info("updating " + entity.toString() );

	    // ------------------------------------------
    	// save with an existing instance
    	// ------------------------------------------ 
		return repository.save(entity);

    }
    
	/*
	 * Delete a AccountStatement
	 * 
     * @param	id		UUID
     */
    public AccountStatement delete( UUID id ) {
	    LOGGER.info("deleting " + id.toString() );

    	// ------------------------------------------
    	// locate the entity by the provided id
    	// ------------------------------------------
	    AccountStatement entity = repository.findById(id).get();
	    
    	// ------------------------------------------
    	// delete what is discovered 
    	// ------------------------------------------
    	repository.delete( entity );
    	
    	return entity;
    }    

    /*
     * Assign a Account
     * 
     * @param	parentId	UUID
     * @param	assignment 	Account 
     * @return	AccountStatement
     */
    public AccountStatement assignAccount( UUID parentId, Account assignment ) {
	    LOGGER.info("assigning Account as " + assignment.toString() );

	    AccountStatement parentEntity = repository.findById( parentId ).get();
	    assignment = registry.project( Account.class, assignment.getAccountId());

	    // ------------------------------------------
		// assign the Account to the parent entity
		// ------------------------------------------ 
	    parentEntity.setAccount( assignment );

	    // ------------------------------------------
    	// save the parent entity
    	// ------------------------------------------ 
	    repository.save(parentEntity);
        
	    return parentEntity;
    }
    

	/*
	 * Unassign the Account
	 * 
	 * @param	parentId		UUID
	 * @return	AccountStatement
	 */
	public AccountStatement unAssignAccount( UUID parentId ) {
		AccountStatement parentEntity = repository.findById(parentId).get();

		LOGGER.info("unAssigning Account on " + parentEntity.toString() );
		
	    // ------------------------------------------
		// null out the Account on the parent entithy
		// ------------------------------------------     
	    parentEntity.setAccount(null);

	    // ------------------------------------------
		// save the parent entity
		// ------------------------------------------ 
	    repository.save(parentEntity);
    
	    return parentEntity;
	}




    /**
     * Method to retrieve the AccountStatement via an FindAccountStatementQuery
     * @return 	query	FindAccountStatementQuery
     */
    @SuppressWarnings("unused")
    public AccountStatement find( UUID id ) {
    	LOGGER.info("handling find using " + id.toString() );
    	try {
    		return repository.findById(id).get();
    	}
    	catch( IllegalArgumentException exc ) {
    		LOGGER.warn( "Failed to find a AccountStatement - {0}", exc.getMessage() );
    	}
    	return null;
    }
    
    /**
     * Method to retrieve a collection of all AccountStatements
     *
     * @param	query	FindAllAccountStatementQuery 
     * @return 	List<AccountStatement> 
     */
    @SuppressWarnings("unused")
    public List<AccountStatement> findAll( FindAllAccountStatementQuery query ) {
    	LOGGER.info("handling findAll using " + query.toString() );
    	try {
    		return repository.findAll();
    	}
    	catch( IllegalArgumentException exc ) {
    		LOGGER.warn( "Failed to find all AccountStatement - {0}", exc.getMessage() );
    	}
    	return null;
    }


    //--------------------------------------------------
    // attributes
    // --------------------------------------------------
	@Autowired
    protected final AccountStatementRepository repository;
	protected final ProjectorRegistry registry;


    private static final Logger LOGGER 	= LoggerFactory.getLogger(AccountStatementEntityProjector.class.getName());

}
