/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Spring Boot 3.5
 *
 * Domain Model:
 * Banking Industry Domain Model
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone National Bank Confidential
 *
 * 2026 Turnstone National Bank
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone National Bank - General Release
 */
package com.harbormaster.projector;

import java.util.*;
import java.util.stream.Collectors;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.stereotype.Component;

import org.springframework.data.domain.Pageable;
import org.springframework.data.domain.PageRequest;
import org.springframework.stereotype.Component;

import com.harbormaster.api.*;
import com.harbormaster.entity.*;
import com.harbormaster.exception.*;
import com.harbormaster.repository.*;

/**
 * <h2>BankingProductEntity Projector</h2>
 * <p>
 * The BankingProduct Entity Projector is responsible for maintaining the write model for
 * BankingProduct entities. It subscribes to domain events published by the BankingProduct
 * Aggregate and updates query-optimized projections used by REST APIs,
 * dashboards, and reporting services.
 * </p>
 * <p>
 * A Projector contains no business logic and never validates commands or
 * modifies the authoritative state of the domain.
 * </p>
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Spring Boot 3.5</td></tr>
 *          <tr><td>published</td><td>09/08/2026</td></tr>
 *          <tr><td>design pattern</td><td>ServiceLayer</td></tr>
 *          <tr><td>architecture style</td><td>Layered</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>Banking Industry Domain Model</td></tr>
 *          <tr><td>description</td><td>HCIDL model capturing core banking, payments, lending, cards, KYC, and FX capabilities.</td></tr>
 *          <tr><td>industry</td><td>Banking</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Services Used</h3>
 *
 *      <ul>
 *          <li>BankingProductRepository</li>
 *          <li>ProjectorRegistry</li>
 *      </ul>
 *
 * <p>@author Harbormaster Dev Team</p>
 */
@Component("bankingProduct-entity-projector")
public class BankingProductEntityProjector implements EntityProjector<BankingProduct>{
		
	// core constructor
	public BankingProductEntityProjector(ProjectorRegistry registry,
										BankingProductRepository repository ) {
        this.registry 	= registry;
		this.repository = repository;
    }

	@Override
	public Class<BankingProduct> getEntityClass() {
		return BankingProduct.class;
	}

    /*
	 * Insert a BankingProduct
	 * 
     * @param	entity BankingProduct
     */
    public BankingProduct create( BankingProduct entity) {
	    LOGGER.info("creating " + entity.toString() );
	   
    	// ------------------------------------------
    	// persist a new one
    	// ------------------------------------------ 
	    return repository.save(entity);
        
    }

	/*
	 * Update a BankingProduct
	 * 
     * @param	entity BankingProduct
     */
    public BankingProduct update( BankingProduct entity) {
	    LOGGER.info("updating " + entity.toString() );

	    // ------------------------------------------
    	// save with an existing instance
    	// ------------------------------------------ 
		return repository.save(entity);

    }
    
	/*
	 * Delete a BankingProduct
	 * 
     * @param	id		UUID
     */
    public BankingProduct delete( UUID id ) {
	    LOGGER.info("deleting " + id.toString() );

    	// ------------------------------------------
    	// locate the entity by the provided id
    	// ------------------------------------------
	    BankingProduct entity = repository.findById(id).get();
	    
    	// ------------------------------------------
    	// delete what is discovered 
    	// ------------------------------------------
    	repository.delete( entity );
    	
    	return entity;
    }    

    /*
     * Assign a Bank
     * 
     * @param	parentId	UUID
     * @param	assignment 	Bank 
     * @return	BankingProduct
     */
    public BankingProduct assignBank( UUID parentId, Bank assignment ) {
	    LOGGER.info("assigning Bank as " + assignment.toString() );

	    BankingProduct parentEntity = repository.findById( parentId ).get();
	    assignment = registry.project( Bank.class, assignment.getBankId());

	    // ------------------------------------------
		// assign the Bank to the parent entity
		// ------------------------------------------ 
	    parentEntity.setBank( assignment );

	    // ------------------------------------------
    	// save the parent entity
    	// ------------------------------------------ 
	    repository.save(parentEntity);
        
	    return parentEntity;
    }
    

	/*
	 * Unassign the Bank
	 * 
	 * @param	parentId		UUID
	 * @return	BankingProduct
	 */
	public BankingProduct unAssignBank( UUID parentId ) {
		BankingProduct parentEntity = repository.findById(parentId).get();

		LOGGER.info("unAssigning Bank on " + parentEntity.toString() );
		
	    // ------------------------------------------
		// null out the Bank on the parent entithy
		// ------------------------------------------     
	    parentEntity.setBank(null);

	    // ------------------------------------------
		// save the parent entity
		// ------------------------------------------ 
	    repository.save(parentEntity);
    
	    return parentEntity;
	}


    /*
     * Add to the Accounts
     * 
     * @param	parentID	UUID
     * @param	addTo		childType
     * @return	BankingProduct
     */
    public BankingProduct addToAccounts( UUID parentId, Account addTo ) {
	    LOGGER.info("handling AssignAccountsToBankingProductEvent - " );
	    
	    BankingProduct parentEntity = repository.findById(parentId).get();
	    Account child = registry.project( Account.class, addTo.getAccountId());
	    
	    parentEntity.getAccounts().add( child );

	    // ------------------------------------------
    	// save 
    	// ------------------------------------------ 
	    repository.save(parentEntity);
        
	    return parentEntity;
    }
    

    /*
     * Remove from the Accounts
     * 
     * @param	parentID	UUID
     * @param	removeFrom	childType
     * @return	BankingProduct
     */
	public BankingProduct removeFromAccounts( UUID parentId, Account removeFrom ) {
	    LOGGER.info("handling RemoveAccountsFromBankingProductEvent " );
	
	    BankingProduct parentEntity = repository.findById(parentId).get();
	    Account child = registry.project( Account.class, removeFrom.getAccountId());
	    
	    parentEntity.getAccounts().remove( child );
	
	    // ------------------------------------------
		// save
		// ------------------------------------------ 
	    update(parentEntity);
	    
	    return parentEntity;
	}

    /*
     * Add to the LoanAccounts
     * 
     * @param	parentID	UUID
     * @param	addTo		childType
     * @return	BankingProduct
     */
    public BankingProduct addToLoanAccounts( UUID parentId, LoanAccount addTo ) {
	    LOGGER.info("handling AssignLoanAccountsToBankingProductEvent - " );
	    
	    BankingProduct parentEntity = repository.findById(parentId).get();
	    LoanAccount child = registry.project( LoanAccount.class, addTo.getLoanAccountId());
	    
	    parentEntity.getLoanAccounts().add( child );

	    // ------------------------------------------
    	// save 
    	// ------------------------------------------ 
	    repository.save(parentEntity);
        
	    return parentEntity;
    }
    

    /*
     * Remove from the LoanAccounts
     * 
     * @param	parentID	UUID
     * @param	removeFrom	childType
     * @return	BankingProduct
     */
	public BankingProduct removeFromLoanAccounts( UUID parentId, LoanAccount removeFrom ) {
	    LOGGER.info("handling RemoveLoanAccountsFromBankingProductEvent " );
	
	    BankingProduct parentEntity = repository.findById(parentId).get();
	    LoanAccount child = registry.project( LoanAccount.class, removeFrom.getLoanAccountId());
	    
	    parentEntity.getLoanAccounts().remove( child );
	
	    // ------------------------------------------
		// save
		// ------------------------------------------ 
	    update(parentEntity);
	    
	    return parentEntity;
	}

    /*
     * Add to the PaymentCards
     * 
     * @param	parentID	UUID
     * @param	addTo		childType
     * @return	BankingProduct
     */
    public BankingProduct addToPaymentCards( UUID parentId, PaymentCard addTo ) {
	    LOGGER.info("handling AssignPaymentCardsToBankingProductEvent - " );
	    
	    BankingProduct parentEntity = repository.findById(parentId).get();
	    PaymentCard child = registry.project( PaymentCard.class, addTo.getPaymentCardId());
	    
	    parentEntity.getPaymentCards().add( child );

	    // ------------------------------------------
    	// save 
    	// ------------------------------------------ 
	    repository.save(parentEntity);
        
	    return parentEntity;
    }
    

    /*
     * Remove from the PaymentCards
     * 
     * @param	parentID	UUID
     * @param	removeFrom	childType
     * @return	BankingProduct
     */
	public BankingProduct removeFromPaymentCards( UUID parentId, PaymentCard removeFrom ) {
	    LOGGER.info("handling RemovePaymentCardsFromBankingProductEvent " );
	
	    BankingProduct parentEntity = repository.findById(parentId).get();
	    PaymentCard child = registry.project( PaymentCard.class, removeFrom.getPaymentCardId());
	    
	    parentEntity.getPaymentCards().remove( child );
	
	    // ------------------------------------------
		// save
		// ------------------------------------------ 
	    update(parentEntity);
	    
	    return parentEntity;
	}



    /**
     * Method to retrieve the BankingProduct via an FindBankingProductQuery
     * @return 	query	FindBankingProductQuery
     */
    @SuppressWarnings("unused")
    public BankingProduct find( UUID id ) {
    	LOGGER.info("handling find using " + id.toString() );
    	try {
    		return repository.findById(id).get();
    	}
    	catch( IllegalArgumentException exc ) {
    		LOGGER.warn( "Failed to find a BankingProduct - {0}", exc.getMessage() );
    	}
    	return null;
    }
    
    /**
     * Method to retrieve a collection of all BankingProducts
     *
     * @param	query	FindAllBankingProductQuery 
     * @return 	List<BankingProduct> 
     */
    @SuppressWarnings("unused")
    public List<BankingProduct> findAll( FindAllBankingProductQuery query ) {
    	LOGGER.info("handling findAll using " + query.toString() );
    	try {
    		return repository.findAll();
    	}
    	catch( IllegalArgumentException exc ) {
    		LOGGER.warn( "Failed to find all BankingProduct - {0}", exc.getMessage() );
    	}
    	return null;
    }


    //--------------------------------------------------
    // attributes
    // --------------------------------------------------
	@Autowired
    protected final BankingProductRepository repository;
	protected final ProjectorRegistry registry;


    private static final Logger LOGGER 	= LoggerFactory.getLogger(BankingProductEntityProjector.class.getName());

}
