/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Spring Boot 3.5
 *
 * Domain Model:
 * Banking Industry Domain Model
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone National Bank Confidential
 *
 * 2026 Turnstone National Bank
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone National Bank - General Release
 */
package com.harbormaster.projector;

import java.util.*;
import java.util.stream.Collectors;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.stereotype.Component;

import org.springframework.data.domain.Pageable;
import org.springframework.data.domain.PageRequest;
import org.springframework.stereotype.Component;

import com.harbormaster.api.*;
import com.harbormaster.entity.*;
import com.harbormaster.exception.*;
import com.harbormaster.repository.*;

/**
 * <h2>BranchEntity Projector</h2>
 * <p>
 * The Branch Entity Projector is responsible for maintaining the write model for
 * Branch entities. It subscribes to domain events published by the Branch
 * Aggregate and updates query-optimized projections used by REST APIs,
 * dashboards, and reporting services.
 * </p>
 * <p>
 * A Projector contains no business logic and never validates commands or
 * modifies the authoritative state of the domain.
 * </p>
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Spring Boot 3.5</td></tr>
 *          <tr><td>published</td><td>09/08/2026</td></tr>
 *          <tr><td>design pattern</td><td>ServiceLayer</td></tr>
 *          <tr><td>architecture style</td><td>Layered</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>Banking Industry Domain Model</td></tr>
 *          <tr><td>description</td><td>HCIDL model capturing core banking, payments, lending, cards, KYC, and FX capabilities.</td></tr>
 *          <tr><td>industry</td><td>Banking</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Services Used</h3>
 *
 *      <ul>
 *          <li>BranchRepository</li>
 *          <li>ProjectorRegistry</li>
 *      </ul>
 *
 * <p>@author Harbormaster Dev Team</p>
 */
@Component("branch-entity-projector")
public class BranchEntityProjector implements EntityProjector<Branch>{
		
	// core constructor
	public BranchEntityProjector(ProjectorRegistry registry,
										BranchRepository repository ) {
        this.registry 	= registry;
		this.repository = repository;
    }

	@Override
	public Class<Branch> getEntityClass() {
		return Branch.class;
	}

    /*
	 * Insert a Branch
	 * 
     * @param	entity Branch
     */
    public Branch create( Branch entity) {
	    LOGGER.info("creating " + entity.toString() );
	   
    	// ------------------------------------------
    	// persist a new one
    	// ------------------------------------------ 
	    return repository.save(entity);
        
    }

	/*
	 * Update a Branch
	 * 
     * @param	entity Branch
     */
    public Branch update( Branch entity) {
	    LOGGER.info("updating " + entity.toString() );

	    // ------------------------------------------
    	// save with an existing instance
    	// ------------------------------------------ 
		return repository.save(entity);

    }
    
	/*
	 * Delete a Branch
	 * 
     * @param	id		UUID
     */
    public Branch delete( UUID id ) {
	    LOGGER.info("deleting " + id.toString() );

    	// ------------------------------------------
    	// locate the entity by the provided id
    	// ------------------------------------------
	    Branch entity = repository.findById(id).get();
	    
    	// ------------------------------------------
    	// delete what is discovered 
    	// ------------------------------------------
    	repository.delete( entity );
    	
    	return entity;
    }    

    /*
     * Assign a Bank
     * 
     * @param	parentId	UUID
     * @param	assignment 	Bank 
     * @return	Branch
     */
    public Branch assignBank( UUID parentId, Bank assignment ) {
	    LOGGER.info("assigning Bank as " + assignment.toString() );

	    Branch parentEntity = repository.findById( parentId ).get();
	    assignment = registry.project( Bank.class, assignment.getBankId());

	    // ------------------------------------------
		// assign the Bank to the parent entity
		// ------------------------------------------ 
	    parentEntity.setBank( assignment );

	    // ------------------------------------------
    	// save the parent entity
    	// ------------------------------------------ 
	    repository.save(parentEntity);
        
	    return parentEntity;
    }
    

	/*
	 * Unassign the Bank
	 * 
	 * @param	parentId		UUID
	 * @return	Branch
	 */
	public Branch unAssignBank( UUID parentId ) {
		Branch parentEntity = repository.findById(parentId).get();

		LOGGER.info("unAssigning Bank on " + parentEntity.toString() );
		
	    // ------------------------------------------
		// null out the Bank on the parent entithy
		// ------------------------------------------     
	    parentEntity.setBank(null);

	    // ------------------------------------------
		// save the parent entity
		// ------------------------------------------ 
	    repository.save(parentEntity);
    
	    return parentEntity;
	}


    /*
     * Add to the Accounts
     * 
     * @param	parentID	UUID
     * @param	addTo		childType
     * @return	Branch
     */
    public Branch addToAccounts( UUID parentId, Account addTo ) {
	    LOGGER.info("handling AssignAccountsToBranchEvent - " );
	    
	    Branch parentEntity = repository.findById(parentId).get();
	    Account child = registry.project( Account.class, addTo.getAccountId());
	    
	    parentEntity.getAccounts().add( child );

	    // ------------------------------------------
    	// save 
    	// ------------------------------------------ 
	    repository.save(parentEntity);
        
	    return parentEntity;
    }
    

    /*
     * Remove from the Accounts
     * 
     * @param	parentID	UUID
     * @param	removeFrom	childType
     * @return	Branch
     */
	public Branch removeFromAccounts( UUID parentId, Account removeFrom ) {
	    LOGGER.info("handling RemoveAccountsFromBranchEvent " );
	
	    Branch parentEntity = repository.findById(parentId).get();
	    Account child = registry.project( Account.class, removeFrom.getAccountId());
	    
	    parentEntity.getAccounts().remove( child );
	
	    // ------------------------------------------
		// save
		// ------------------------------------------ 
	    update(parentEntity);
	    
	    return parentEntity;
	}

    /*
     * Add to the LoanAccounts
     * 
     * @param	parentID	UUID
     * @param	addTo		childType
     * @return	Branch
     */
    public Branch addToLoanAccounts( UUID parentId, LoanAccount addTo ) {
	    LOGGER.info("handling AssignLoanAccountsToBranchEvent - " );
	    
	    Branch parentEntity = repository.findById(parentId).get();
	    LoanAccount child = registry.project( LoanAccount.class, addTo.getLoanAccountId());
	    
	    parentEntity.getLoanAccounts().add( child );

	    // ------------------------------------------
    	// save 
    	// ------------------------------------------ 
	    repository.save(parentEntity);
        
	    return parentEntity;
    }
    

    /*
     * Remove from the LoanAccounts
     * 
     * @param	parentID	UUID
     * @param	removeFrom	childType
     * @return	Branch
     */
	public Branch removeFromLoanAccounts( UUID parentId, LoanAccount removeFrom ) {
	    LOGGER.info("handling RemoveLoanAccountsFromBranchEvent " );
	
	    Branch parentEntity = repository.findById(parentId).get();
	    LoanAccount child = registry.project( LoanAccount.class, removeFrom.getLoanAccountId());
	    
	    parentEntity.getLoanAccounts().remove( child );
	
	    // ------------------------------------------
		// save
		// ------------------------------------------ 
	    update(parentEntity);
	    
	    return parentEntity;
	}

    /*
     * Add to the Atms
     * 
     * @param	parentID	UUID
     * @param	addTo		childType
     * @return	Branch
     */
    public Branch addToAtms( UUID parentId, ATM addTo ) {
	    LOGGER.info("handling AssignAtmsToBranchEvent - " );
	    
	    Branch parentEntity = repository.findById(parentId).get();
	    ATM child = registry.project( ATM.class, addTo.getATMId());
	    
	    parentEntity.getAtms().add( child );

	    // ------------------------------------------
    	// save 
    	// ------------------------------------------ 
	    repository.save(parentEntity);
        
	    return parentEntity;
    }
    

    /*
     * Remove from the Atms
     * 
     * @param	parentID	UUID
     * @param	removeFrom	childType
     * @return	Branch
     */
	public Branch removeFromAtms( UUID parentId, ATM removeFrom ) {
	    LOGGER.info("handling RemoveAtmsFromBranchEvent " );
	
	    Branch parentEntity = repository.findById(parentId).get();
	    ATM child = registry.project( ATM.class, removeFrom.getATMId());
	    
	    parentEntity.getAtms().remove( child );
	
	    // ------------------------------------------
		// save
		// ------------------------------------------ 
	    update(parentEntity);
	    
	    return parentEntity;
	}



    /**
     * Method to retrieve the Branch via an FindBranchQuery
     * @return 	query	FindBranchQuery
     */
    @SuppressWarnings("unused")
    public Branch find( UUID id ) {
    	LOGGER.info("handling find using " + id.toString() );
    	try {
    		return repository.findById(id).get();
    	}
    	catch( IllegalArgumentException exc ) {
    		LOGGER.warn( "Failed to find a Branch - {0}", exc.getMessage() );
    	}
    	return null;
    }
    
    /**
     * Method to retrieve a collection of all Branchs
     *
     * @param	query	FindAllBranchQuery 
     * @return 	List<Branch> 
     */
    @SuppressWarnings("unused")
    public List<Branch> findAll( FindAllBranchQuery query ) {
    	LOGGER.info("handling findAll using " + query.toString() );
    	try {
    		return repository.findAll();
    	}
    	catch( IllegalArgumentException exc ) {
    		LOGGER.warn( "Failed to find all Branch - {0}", exc.getMessage() );
    	}
    	return null;
    }


    //--------------------------------------------------
    // attributes
    // --------------------------------------------------
	@Autowired
    protected final BranchRepository repository;
	protected final ProjectorRegistry registry;


    private static final Logger LOGGER 	= LoggerFactory.getLogger(BranchEntityProjector.class.getName());

}
