/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Spring Boot 3.5
 *
 * Domain Model:
 * Banking Industry Domain Model
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone National Bank Confidential
 *
 * 2026 Turnstone National Bank
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone National Bank - General Release
 */
package com.harbormaster.projector;

import java.util.*;
import java.util.stream.Collectors;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.stereotype.Component;

import org.springframework.data.domain.Pageable;
import org.springframework.data.domain.PageRequest;
import org.springframework.stereotype.Component;

import com.harbormaster.api.*;
import com.harbormaster.entity.*;
import com.harbormaster.exception.*;
import com.harbormaster.repository.*;

/**
 * <h2>ConsentEntity Projector</h2>
 * <p>
 * The Consent Entity Projector is responsible for maintaining the write model for
 * Consent entities. It subscribes to domain events published by the Consent
 * Aggregate and updates query-optimized projections used by REST APIs,
 * dashboards, and reporting services.
 * </p>
 * <p>
 * A Projector contains no business logic and never validates commands or
 * modifies the authoritative state of the domain.
 * </p>
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Spring Boot 3.5</td></tr>
 *          <tr><td>published</td><td>09/08/2026</td></tr>
 *          <tr><td>design pattern</td><td>ServiceLayer</td></tr>
 *          <tr><td>architecture style</td><td>Layered</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>Banking Industry Domain Model</td></tr>
 *          <tr><td>description</td><td>HCIDL model capturing core banking, payments, lending, cards, KYC, and FX capabilities.</td></tr>
 *          <tr><td>industry</td><td>Banking</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Services Used</h3>
 *
 *      <ul>
 *          <li>ConsentRepository</li>
 *          <li>ProjectorRegistry</li>
 *      </ul>
 *
 * <p>@author Harbormaster Dev Team</p>
 */
@Component("consent-entity-projector")
public class ConsentEntityProjector implements EntityProjector<Consent>{
		
	// core constructor
	public ConsentEntityProjector(ProjectorRegistry registry,
										ConsentRepository repository ) {
        this.registry 	= registry;
		this.repository = repository;
    }

	@Override
	public Class<Consent> getEntityClass() {
		return Consent.class;
	}

    /*
	 * Insert a Consent
	 * 
     * @param	entity Consent
     */
    public Consent create( Consent entity) {
	    LOGGER.info("creating " + entity.toString() );
	   
    	// ------------------------------------------
    	// persist a new one
    	// ------------------------------------------ 
	    return repository.save(entity);
        
    }

	/*
	 * Update a Consent
	 * 
     * @param	entity Consent
     */
    public Consent update( Consent entity) {
	    LOGGER.info("updating " + entity.toString() );

	    // ------------------------------------------
    	// save with an existing instance
    	// ------------------------------------------ 
		return repository.save(entity);

    }
    
	/*
	 * Delete a Consent
	 * 
     * @param	id		UUID
     */
    public Consent delete( UUID id ) {
	    LOGGER.info("deleting " + id.toString() );

    	// ------------------------------------------
    	// locate the entity by the provided id
    	// ------------------------------------------
	    Consent entity = repository.findById(id).get();
	    
    	// ------------------------------------------
    	// delete what is discovered 
    	// ------------------------------------------
    	repository.delete( entity );
    	
    	return entity;
    }    

    /*
     * Assign a Customer
     * 
     * @param	parentId	UUID
     * @param	assignment 	Customer 
     * @return	Consent
     */
    public Consent assignCustomer( UUID parentId, Customer assignment ) {
	    LOGGER.info("assigning Customer as " + assignment.toString() );

	    Consent parentEntity = repository.findById( parentId ).get();
	    assignment = registry.project( Customer.class, assignment.getCustomerId());

	    // ------------------------------------------
		// assign the Customer to the parent entity
		// ------------------------------------------ 
	    parentEntity.setCustomer( assignment );

	    // ------------------------------------------
    	// save the parent entity
    	// ------------------------------------------ 
	    repository.save(parentEntity);
        
	    return parentEntity;
    }
    

	/*
	 * Unassign the Customer
	 * 
	 * @param	parentId		UUID
	 * @return	Consent
	 */
	public Consent unAssignCustomer( UUID parentId ) {
		Consent parentEntity = repository.findById(parentId).get();

		LOGGER.info("unAssigning Customer on " + parentEntity.toString() );
		
	    // ------------------------------------------
		// null out the Customer on the parent entithy
		// ------------------------------------------     
	    parentEntity.setCustomer(null);

	    // ------------------------------------------
		// save the parent entity
		// ------------------------------------------ 
	    repository.save(parentEntity);
    
	    return parentEntity;
	}

    /*
     * Assign a Bank
     * 
     * @param	parentId	UUID
     * @param	assignment 	Bank 
     * @return	Consent
     */
    public Consent assignBank( UUID parentId, Bank assignment ) {
	    LOGGER.info("assigning Bank as " + assignment.toString() );

	    Consent parentEntity = repository.findById( parentId ).get();
	    assignment = registry.project( Bank.class, assignment.getBankId());

	    // ------------------------------------------
		// assign the Bank to the parent entity
		// ------------------------------------------ 
	    parentEntity.setBank( assignment );

	    // ------------------------------------------
    	// save the parent entity
    	// ------------------------------------------ 
	    repository.save(parentEntity);
        
	    return parentEntity;
    }
    

	/*
	 * Unassign the Bank
	 * 
	 * @param	parentId		UUID
	 * @return	Consent
	 */
	public Consent unAssignBank( UUID parentId ) {
		Consent parentEntity = repository.findById(parentId).get();

		LOGGER.info("unAssigning Bank on " + parentEntity.toString() );
		
	    // ------------------------------------------
		// null out the Bank on the parent entithy
		// ------------------------------------------     
	    parentEntity.setBank(null);

	    // ------------------------------------------
		// save the parent entity
		// ------------------------------------------ 
	    repository.save(parentEntity);
    
	    return parentEntity;
	}

    /*
     * Assign a ThirdPartyProvider
     * 
     * @param	parentId	UUID
     * @param	assignment 	ThirdPartyProvider 
     * @return	Consent
     */
    public Consent assignThirdPartyProvider( UUID parentId, ThirdPartyProvider assignment ) {
	    LOGGER.info("assigning ThirdPartyProvider as " + assignment.toString() );

	    Consent parentEntity = repository.findById( parentId ).get();
	    assignment = registry.project( ThirdPartyProvider.class, assignment.getThirdPartyProviderId());

	    // ------------------------------------------
		// assign the ThirdPartyProvider to the parent entity
		// ------------------------------------------ 
	    parentEntity.setThirdPartyProvider( assignment );

	    // ------------------------------------------
    	// save the parent entity
    	// ------------------------------------------ 
	    repository.save(parentEntity);
        
	    return parentEntity;
    }
    

	/*
	 * Unassign the ThirdPartyProvider
	 * 
	 * @param	parentId		UUID
	 * @return	Consent
	 */
	public Consent unAssignThirdPartyProvider( UUID parentId ) {
		Consent parentEntity = repository.findById(parentId).get();

		LOGGER.info("unAssigning ThirdPartyProvider on " + parentEntity.toString() );
		
	    // ------------------------------------------
		// null out the ThirdPartyProvider on the parent entithy
		// ------------------------------------------     
	    parentEntity.setThirdPartyProvider(null);

	    // ------------------------------------------
		// save the parent entity
		// ------------------------------------------ 
	    repository.save(parentEntity);
    
	    return parentEntity;
	}


    /*
     * Add to the AuthorizedAccounts
     * 
     * @param	parentID	UUID
     * @param	addTo		childType
     * @return	Consent
     */
    public Consent addToAuthorizedAccounts( UUID parentId, Account addTo ) {
	    LOGGER.info("handling AssignAuthorizedAccountsToConsentEvent - " );
	    
	    Consent parentEntity = repository.findById(parentId).get();
	    Account child = registry.project( Account.class, addTo.getAccountId());
	    
	    parentEntity.getAuthorizedAccounts().add( child );

	    // ------------------------------------------
    	// save 
    	// ------------------------------------------ 
	    repository.save(parentEntity);
        
	    return parentEntity;
    }
    

    /*
     * Remove from the AuthorizedAccounts
     * 
     * @param	parentID	UUID
     * @param	removeFrom	childType
     * @return	Consent
     */
	public Consent removeFromAuthorizedAccounts( UUID parentId, Account removeFrom ) {
	    LOGGER.info("handling RemoveAuthorizedAccountsFromConsentEvent " );
	
	    Consent parentEntity = repository.findById(parentId).get();
	    Account child = registry.project( Account.class, removeFrom.getAccountId());
	    
	    parentEntity.getAuthorizedAccounts().remove( child );
	
	    // ------------------------------------------
		// save
		// ------------------------------------------ 
	    update(parentEntity);
	    
	    return parentEntity;
	}



    /**
     * Method to retrieve the Consent via an FindConsentQuery
     * @return 	query	FindConsentQuery
     */
    @SuppressWarnings("unused")
    public Consent find( UUID id ) {
    	LOGGER.info("handling find using " + id.toString() );
    	try {
    		return repository.findById(id).get();
    	}
    	catch( IllegalArgumentException exc ) {
    		LOGGER.warn( "Failed to find a Consent - {0}", exc.getMessage() );
    	}
    	return null;
    }
    
    /**
     * Method to retrieve a collection of all Consents
     *
     * @param	query	FindAllConsentQuery 
     * @return 	List<Consent> 
     */
    @SuppressWarnings("unused")
    public List<Consent> findAll( FindAllConsentQuery query ) {
    	LOGGER.info("handling findAll using " + query.toString() );
    	try {
    		return repository.findAll();
    	}
    	catch( IllegalArgumentException exc ) {
    		LOGGER.warn( "Failed to find all Consent - {0}", exc.getMessage() );
    	}
    	return null;
    }


    //--------------------------------------------------
    // attributes
    // --------------------------------------------------
	@Autowired
    protected final ConsentRepository repository;
	protected final ProjectorRegistry registry;


    private static final Logger LOGGER 	= LoggerFactory.getLogger(ConsentEntityProjector.class.getName());

}
