/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Spring Boot 3.5
 *
 * Domain Model:
 * Banking Industry Domain Model
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone National Bank Confidential
 *
 * 2026 Turnstone National Bank
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone National Bank - General Release
 */
package com.harbormaster.projector;

import java.util.*;
import java.util.stream.Collectors;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.stereotype.Component;

import org.springframework.data.domain.Pageable;
import org.springframework.data.domain.PageRequest;
import org.springframework.stereotype.Component;

import com.harbormaster.api.*;
import com.harbormaster.entity.*;
import com.harbormaster.exception.*;
import com.harbormaster.repository.*;

/**
 * <h2>ExternalAccountEntity Projector</h2>
 * <p>
 * The ExternalAccount Entity Projector is responsible for maintaining the write model for
 * ExternalAccount entities. It subscribes to domain events published by the ExternalAccount
 * Aggregate and updates query-optimized projections used by REST APIs,
 * dashboards, and reporting services.
 * </p>
 * <p>
 * A Projector contains no business logic and never validates commands or
 * modifies the authoritative state of the domain.
 * </p>
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Spring Boot 3.5</td></tr>
 *          <tr><td>published</td><td>09/08/2026</td></tr>
 *          <tr><td>design pattern</td><td>ServiceLayer</td></tr>
 *          <tr><td>architecture style</td><td>Layered</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>Banking Industry Domain Model</td></tr>
 *          <tr><td>description</td><td>HCIDL model capturing core banking, payments, lending, cards, KYC, and FX capabilities.</td></tr>
 *          <tr><td>industry</td><td>Banking</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Services Used</h3>
 *
 *      <ul>
 *          <li>ExternalAccountRepository</li>
 *          <li>ProjectorRegistry</li>
 *      </ul>
 *
 * <p>@author Harbormaster Dev Team</p>
 */
@Component("externalAccount-entity-projector")
public class ExternalAccountEntityProjector implements EntityProjector<ExternalAccount>{
		
	// core constructor
	public ExternalAccountEntityProjector(ProjectorRegistry registry,
										ExternalAccountRepository repository ) {
        this.registry 	= registry;
		this.repository = repository;
    }

	@Override
	public Class<ExternalAccount> getEntityClass() {
		return ExternalAccount.class;
	}

    /*
	 * Insert a ExternalAccount
	 * 
     * @param	entity ExternalAccount
     */
    public ExternalAccount create( ExternalAccount entity) {
	    LOGGER.info("creating " + entity.toString() );
	   
    	// ------------------------------------------
    	// persist a new one
    	// ------------------------------------------ 
	    return repository.save(entity);
        
    }

	/*
	 * Update a ExternalAccount
	 * 
     * @param	entity ExternalAccount
     */
    public ExternalAccount update( ExternalAccount entity) {
	    LOGGER.info("updating " + entity.toString() );

	    // ------------------------------------------
    	// save with an existing instance
    	// ------------------------------------------ 
		return repository.save(entity);

    }
    
	/*
	 * Delete a ExternalAccount
	 * 
     * @param	id		UUID
     */
    public ExternalAccount delete( UUID id ) {
	    LOGGER.info("deleting " + id.toString() );

    	// ------------------------------------------
    	// locate the entity by the provided id
    	// ------------------------------------------
	    ExternalAccount entity = repository.findById(id).get();
	    
    	// ------------------------------------------
    	// delete what is discovered 
    	// ------------------------------------------
    	repository.delete( entity );
    	
    	return entity;
    }    

    /*
     * Assign a Customer
     * 
     * @param	parentId	UUID
     * @param	assignment 	Customer 
     * @return	ExternalAccount
     */
    public ExternalAccount assignCustomer( UUID parentId, Customer assignment ) {
	    LOGGER.info("assigning Customer as " + assignment.toString() );

	    ExternalAccount parentEntity = repository.findById( parentId ).get();
	    assignment = registry.project( Customer.class, assignment.getCustomerId());

	    // ------------------------------------------
		// assign the Customer to the parent entity
		// ------------------------------------------ 
	    parentEntity.setCustomer( assignment );

	    // ------------------------------------------
    	// save the parent entity
    	// ------------------------------------------ 
	    repository.save(parentEntity);
        
	    return parentEntity;
    }
    

	/*
	 * Unassign the Customer
	 * 
	 * @param	parentId		UUID
	 * @return	ExternalAccount
	 */
	public ExternalAccount unAssignCustomer( UUID parentId ) {
		ExternalAccount parentEntity = repository.findById(parentId).get();

		LOGGER.info("unAssigning Customer on " + parentEntity.toString() );
		
	    // ------------------------------------------
		// null out the Customer on the parent entithy
		// ------------------------------------------     
	    parentEntity.setCustomer(null);

	    // ------------------------------------------
		// save the parent entity
		// ------------------------------------------ 
	    repository.save(parentEntity);
    
	    return parentEntity;
	}


    /*
     * Add to the Transactions
     * 
     * @param	parentID	UUID
     * @param	addTo		childType
     * @return	ExternalAccount
     */
    public ExternalAccount addToTransactions( UUID parentId, Transaction addTo ) {
	    LOGGER.info("handling AssignTransactionsToExternalAccountEvent - " );
	    
	    ExternalAccount parentEntity = repository.findById(parentId).get();
	    Transaction child = registry.project( Transaction.class, addTo.getTransactionId());
	    
	    parentEntity.getTransactions().add( child );

	    // ------------------------------------------
    	// save 
    	// ------------------------------------------ 
	    repository.save(parentEntity);
        
	    return parentEntity;
    }
    

    /*
     * Remove from the Transactions
     * 
     * @param	parentID	UUID
     * @param	removeFrom	childType
     * @return	ExternalAccount
     */
	public ExternalAccount removeFromTransactions( UUID parentId, Transaction removeFrom ) {
	    LOGGER.info("handling RemoveTransactionsFromExternalAccountEvent " );
	
	    ExternalAccount parentEntity = repository.findById(parentId).get();
	    Transaction child = registry.project( Transaction.class, removeFrom.getTransactionId());
	    
	    parentEntity.getTransactions().remove( child );
	
	    // ------------------------------------------
		// save
		// ------------------------------------------ 
	    update(parentEntity);
	    
	    return parentEntity;
	}



    /**
     * Method to retrieve the ExternalAccount via an FindExternalAccountQuery
     * @return 	query	FindExternalAccountQuery
     */
    @SuppressWarnings("unused")
    public ExternalAccount find( UUID id ) {
    	LOGGER.info("handling find using " + id.toString() );
    	try {
    		return repository.findById(id).get();
    	}
    	catch( IllegalArgumentException exc ) {
    		LOGGER.warn( "Failed to find a ExternalAccount - {0}", exc.getMessage() );
    	}
    	return null;
    }
    
    /**
     * Method to retrieve a collection of all ExternalAccounts
     *
     * @param	query	FindAllExternalAccountQuery 
     * @return 	List<ExternalAccount> 
     */
    @SuppressWarnings("unused")
    public List<ExternalAccount> findAll( FindAllExternalAccountQuery query ) {
    	LOGGER.info("handling findAll using " + query.toString() );
    	try {
    		return repository.findAll();
    	}
    	catch( IllegalArgumentException exc ) {
    		LOGGER.warn( "Failed to find all ExternalAccount - {0}", exc.getMessage() );
    	}
    	return null;
    }


    //--------------------------------------------------
    // attributes
    // --------------------------------------------------
	@Autowired
    protected final ExternalAccountRepository repository;
	protected final ProjectorRegistry registry;


    private static final Logger LOGGER 	= LoggerFactory.getLogger(ExternalAccountEntityProjector.class.getName());

}
