/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Spring Boot 3.5
 *
 * Domain Model:
 * Banking Industry Domain Model
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone National Bank Confidential
 *
 * 2026 Turnstone National Bank
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone National Bank - General Release
 */
package com.harbormaster.projector;

import java.util.*;
import java.util.stream.Collectors;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.stereotype.Component;

import org.springframework.data.domain.Pageable;
import org.springframework.data.domain.PageRequest;
import org.springframework.stereotype.Component;

import com.harbormaster.api.*;
import com.harbormaster.entity.*;
import com.harbormaster.exception.*;
import com.harbormaster.repository.*;

/**
 * <h2>KycProfileEntity Projector</h2>
 * <p>
 * The KycProfile Entity Projector is responsible for maintaining the write model for
 * KycProfile entities. It subscribes to domain events published by the KycProfile
 * Aggregate and updates query-optimized projections used by REST APIs,
 * dashboards, and reporting services.
 * </p>
 * <p>
 * A Projector contains no business logic and never validates commands or
 * modifies the authoritative state of the domain.
 * </p>
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Spring Boot 3.5</td></tr>
 *          <tr><td>published</td><td>09/08/2026</td></tr>
 *          <tr><td>design pattern</td><td>ServiceLayer</td></tr>
 *          <tr><td>architecture style</td><td>Layered</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>Banking Industry Domain Model</td></tr>
 *          <tr><td>description</td><td>HCIDL model capturing core banking, payments, lending, cards, KYC, and FX capabilities.</td></tr>
 *          <tr><td>industry</td><td>Banking</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Services Used</h3>
 *
 *      <ul>
 *          <li>KycProfileRepository</li>
 *          <li>ProjectorRegistry</li>
 *      </ul>
 *
 * <p>@author Harbormaster Dev Team</p>
 */
@Component("kycProfile-entity-projector")
public class KycProfileEntityProjector implements EntityProjector<KycProfile>{
		
	// core constructor
	public KycProfileEntityProjector(ProjectorRegistry registry,
										KycProfileRepository repository ) {
        this.registry 	= registry;
		this.repository = repository;
    }

	@Override
	public Class<KycProfile> getEntityClass() {
		return KycProfile.class;
	}

    /*
	 * Insert a KycProfile
	 * 
     * @param	entity KycProfile
     */
    public KycProfile create( KycProfile entity) {
	    LOGGER.info("creating " + entity.toString() );
	   
    	// ------------------------------------------
    	// persist a new one
    	// ------------------------------------------ 
	    return repository.save(entity);
        
    }

	/*
	 * Update a KycProfile
	 * 
     * @param	entity KycProfile
     */
    public KycProfile update( KycProfile entity) {
	    LOGGER.info("updating " + entity.toString() );

	    // ------------------------------------------
    	// save with an existing instance
    	// ------------------------------------------ 
		return repository.save(entity);

    }
    
	/*
	 * Delete a KycProfile
	 * 
     * @param	id		UUID
     */
    public KycProfile delete( UUID id ) {
	    LOGGER.info("deleting " + id.toString() );

    	// ------------------------------------------
    	// locate the entity by the provided id
    	// ------------------------------------------
	    KycProfile entity = repository.findById(id).get();
	    
    	// ------------------------------------------
    	// delete what is discovered 
    	// ------------------------------------------
    	repository.delete( entity );
    	
    	return entity;
    }    

    /*
     * Assign a Customer
     * 
     * @param	parentId	UUID
     * @param	assignment 	Customer 
     * @return	KycProfile
     */
    public KycProfile assignCustomer( UUID parentId, Customer assignment ) {
	    LOGGER.info("assigning Customer as " + assignment.toString() );

	    KycProfile parentEntity = repository.findById( parentId ).get();
	    assignment = registry.project( Customer.class, assignment.getCustomerId());

	    // ------------------------------------------
		// assign the Customer to the parent entity
		// ------------------------------------------ 
	    parentEntity.setCustomer( assignment );

	    // ------------------------------------------
    	// save the parent entity
    	// ------------------------------------------ 
	    repository.save(parentEntity);
        
	    return parentEntity;
    }
    

	/*
	 * Unassign the Customer
	 * 
	 * @param	parentId		UUID
	 * @return	KycProfile
	 */
	public KycProfile unAssignCustomer( UUID parentId ) {
		KycProfile parentEntity = repository.findById(parentId).get();

		LOGGER.info("unAssigning Customer on " + parentEntity.toString() );
		
	    // ------------------------------------------
		// null out the Customer on the parent entithy
		// ------------------------------------------     
	    parentEntity.setCustomer(null);

	    // ------------------------------------------
		// save the parent entity
		// ------------------------------------------ 
	    repository.save(parentEntity);
    
	    return parentEntity;
	}


    /*
     * Add to the IdentityDocuments
     * 
     * @param	parentID	UUID
     * @param	addTo		childType
     * @return	KycProfile
     */
    public KycProfile addToIdentityDocuments( UUID parentId, IdentityDocument addTo ) {
	    LOGGER.info("handling AssignIdentityDocumentsToKycProfileEvent - " );
	    
	    KycProfile parentEntity = repository.findById(parentId).get();
	    IdentityDocument child = registry.project( IdentityDocument.class, addTo.getIdentityDocumentId());
	    
	    parentEntity.getIdentityDocuments().add( child );

	    // ------------------------------------------
    	// save 
    	// ------------------------------------------ 
	    repository.save(parentEntity);
        
	    return parentEntity;
    }
    

    /*
     * Remove from the IdentityDocuments
     * 
     * @param	parentID	UUID
     * @param	removeFrom	childType
     * @return	KycProfile
     */
	public KycProfile removeFromIdentityDocuments( UUID parentId, IdentityDocument removeFrom ) {
	    LOGGER.info("handling RemoveIdentityDocumentsFromKycProfileEvent " );
	
	    KycProfile parentEntity = repository.findById(parentId).get();
	    IdentityDocument child = registry.project( IdentityDocument.class, removeFrom.getIdentityDocumentId());
	    
	    parentEntity.getIdentityDocuments().remove( child );
	
	    // ------------------------------------------
		// save
		// ------------------------------------------ 
	    update(parentEntity);
	    
	    return parentEntity;
	}

    /*
     * Add to the RiskAssessments
     * 
     * @param	parentID	UUID
     * @param	addTo		childType
     * @return	KycProfile
     */
    public KycProfile addToRiskAssessments( UUID parentId, RiskAssessment addTo ) {
	    LOGGER.info("handling AssignRiskAssessmentsToKycProfileEvent - " );
	    
	    KycProfile parentEntity = repository.findById(parentId).get();
	    RiskAssessment child = registry.project( RiskAssessment.class, addTo.getRiskAssessmentId());
	    
	    parentEntity.getRiskAssessments().add( child );

	    // ------------------------------------------
    	// save 
    	// ------------------------------------------ 
	    repository.save(parentEntity);
        
	    return parentEntity;
    }
    

    /*
     * Remove from the RiskAssessments
     * 
     * @param	parentID	UUID
     * @param	removeFrom	childType
     * @return	KycProfile
     */
	public KycProfile removeFromRiskAssessments( UUID parentId, RiskAssessment removeFrom ) {
	    LOGGER.info("handling RemoveRiskAssessmentsFromKycProfileEvent " );
	
	    KycProfile parentEntity = repository.findById(parentId).get();
	    RiskAssessment child = registry.project( RiskAssessment.class, removeFrom.getRiskAssessmentId());
	    
	    parentEntity.getRiskAssessments().remove( child );
	
	    // ------------------------------------------
		// save
		// ------------------------------------------ 
	    update(parentEntity);
	    
	    return parentEntity;
	}

    /*
     * Add to the Screenings
     * 
     * @param	parentID	UUID
     * @param	addTo		childType
     * @return	KycProfile
     */
    public KycProfile addToScreenings( UUID parentId, ScreeningResult addTo ) {
	    LOGGER.info("handling AssignScreeningsToKycProfileEvent - " );
	    
	    KycProfile parentEntity = repository.findById(parentId).get();
	    ScreeningResult child = registry.project( ScreeningResult.class, addTo.getScreeningResultId());
	    
	    parentEntity.getScreenings().add( child );

	    // ------------------------------------------
    	// save 
    	// ------------------------------------------ 
	    repository.save(parentEntity);
        
	    return parentEntity;
    }
    

    /*
     * Remove from the Screenings
     * 
     * @param	parentID	UUID
     * @param	removeFrom	childType
     * @return	KycProfile
     */
	public KycProfile removeFromScreenings( UUID parentId, ScreeningResult removeFrom ) {
	    LOGGER.info("handling RemoveScreeningsFromKycProfileEvent " );
	
	    KycProfile parentEntity = repository.findById(parentId).get();
	    ScreeningResult child = registry.project( ScreeningResult.class, removeFrom.getScreeningResultId());
	    
	    parentEntity.getScreenings().remove( child );
	
	    // ------------------------------------------
		// save
		// ------------------------------------------ 
	    update(parentEntity);
	    
	    return parentEntity;
	}



    /**
     * Method to retrieve the KycProfile via an FindKycProfileQuery
     * @return 	query	FindKycProfileQuery
     */
    @SuppressWarnings("unused")
    public KycProfile find( UUID id ) {
    	LOGGER.info("handling find using " + id.toString() );
    	try {
    		return repository.findById(id).get();
    	}
    	catch( IllegalArgumentException exc ) {
    		LOGGER.warn( "Failed to find a KycProfile - {0}", exc.getMessage() );
    	}
    	return null;
    }
    
    /**
     * Method to retrieve a collection of all KycProfiles
     *
     * @param	query	FindAllKycProfileQuery 
     * @return 	List<KycProfile> 
     */
    @SuppressWarnings("unused")
    public List<KycProfile> findAll( FindAllKycProfileQuery query ) {
    	LOGGER.info("handling findAll using " + query.toString() );
    	try {
    		return repository.findAll();
    	}
    	catch( IllegalArgumentException exc ) {
    		LOGGER.warn( "Failed to find all KycProfile - {0}", exc.getMessage() );
    	}
    	return null;
    }


    //--------------------------------------------------
    // attributes
    // --------------------------------------------------
	@Autowired
    protected final KycProfileRepository repository;
	protected final ProjectorRegistry registry;


    private static final Logger LOGGER 	= LoggerFactory.getLogger(KycProfileEntityProjector.class.getName());

}
