/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Spring Boot 3.5
 *
 * Domain Model:
 * Banking Industry Domain Model
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone National Bank Confidential
 *
 * 2026 Turnstone National Bank
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone National Bank - General Release
 */
package com.harbormaster.projector;

import java.util.*;
import java.util.stream.Collectors;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.stereotype.Component;

import org.springframework.data.domain.Pageable;
import org.springframework.data.domain.PageRequest;
import org.springframework.stereotype.Component;

import com.harbormaster.api.*;
import com.harbormaster.entity.*;
import com.harbormaster.exception.*;
import com.harbormaster.repository.*;

/**
 * <h2>LoanPaymentEntity Projector</h2>
 * <p>
 * The LoanPayment Entity Projector is responsible for maintaining the write model for
 * LoanPayment entities. It subscribes to domain events published by the LoanPayment
 * Aggregate and updates query-optimized projections used by REST APIs,
 * dashboards, and reporting services.
 * </p>
 * <p>
 * A Projector contains no business logic and never validates commands or
 * modifies the authoritative state of the domain.
 * </p>
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Spring Boot 3.5</td></tr>
 *          <tr><td>published</td><td>09/08/2026</td></tr>
 *          <tr><td>design pattern</td><td>ServiceLayer</td></tr>
 *          <tr><td>architecture style</td><td>Layered</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>Banking Industry Domain Model</td></tr>
 *          <tr><td>description</td><td>HCIDL model capturing core banking, payments, lending, cards, KYC, and FX capabilities.</td></tr>
 *          <tr><td>industry</td><td>Banking</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Services Used</h3>
 *
 *      <ul>
 *          <li>LoanPaymentRepository</li>
 *          <li>ProjectorRegistry</li>
 *      </ul>
 *
 * <p>@author Harbormaster Dev Team</p>
 */
@Component("loanPayment-entity-projector")
public class LoanPaymentEntityProjector implements EntityProjector<LoanPayment>{
		
	// core constructor
	public LoanPaymentEntityProjector(ProjectorRegistry registry,
										LoanPaymentRepository repository ) {
        this.registry 	= registry;
		this.repository = repository;
    }

	@Override
	public Class<LoanPayment> getEntityClass() {
		return LoanPayment.class;
	}

    /*
	 * Insert a LoanPayment
	 * 
     * @param	entity LoanPayment
     */
    public LoanPayment create( LoanPayment entity) {
	    LOGGER.info("creating " + entity.toString() );
	   
    	// ------------------------------------------
    	// persist a new one
    	// ------------------------------------------ 
	    return repository.save(entity);
        
    }

	/*
	 * Update a LoanPayment
	 * 
     * @param	entity LoanPayment
     */
    public LoanPayment update( LoanPayment entity) {
	    LOGGER.info("updating " + entity.toString() );

	    // ------------------------------------------
    	// save with an existing instance
    	// ------------------------------------------ 
		return repository.save(entity);

    }
    
	/*
	 * Delete a LoanPayment
	 * 
     * @param	id		UUID
     */
    public LoanPayment delete( UUID id ) {
	    LOGGER.info("deleting " + id.toString() );

    	// ------------------------------------------
    	// locate the entity by the provided id
    	// ------------------------------------------
	    LoanPayment entity = repository.findById(id).get();
	    
    	// ------------------------------------------
    	// delete what is discovered 
    	// ------------------------------------------
    	repository.delete( entity );
    	
    	return entity;
    }    

    /*
     * Assign a LoanAccount
     * 
     * @param	parentId	UUID
     * @param	assignment 	LoanAccount 
     * @return	LoanPayment
     */
    public LoanPayment assignLoanAccount( UUID parentId, LoanAccount assignment ) {
	    LOGGER.info("assigning LoanAccount as " + assignment.toString() );

	    LoanPayment parentEntity = repository.findById( parentId ).get();
	    assignment = registry.project( LoanAccount.class, assignment.getLoanAccountId());

	    // ------------------------------------------
		// assign the LoanAccount to the parent entity
		// ------------------------------------------ 
	    parentEntity.setLoanAccount( assignment );

	    // ------------------------------------------
    	// save the parent entity
    	// ------------------------------------------ 
	    repository.save(parentEntity);
        
	    return parentEntity;
    }
    

	/*
	 * Unassign the LoanAccount
	 * 
	 * @param	parentId		UUID
	 * @return	LoanPayment
	 */
	public LoanPayment unAssignLoanAccount( UUID parentId ) {
		LoanPayment parentEntity = repository.findById(parentId).get();

		LOGGER.info("unAssigning LoanAccount on " + parentEntity.toString() );
		
	    // ------------------------------------------
		// null out the LoanAccount on the parent entithy
		// ------------------------------------------     
	    parentEntity.setLoanAccount(null);

	    // ------------------------------------------
		// save the parent entity
		// ------------------------------------------ 
	    repository.save(parentEntity);
    
	    return parentEntity;
	}

    /*
     * Assign a Transaction
     * 
     * @param	parentId	UUID
     * @param	assignment 	Transaction 
     * @return	LoanPayment
     */
    public LoanPayment assignTransaction( UUID parentId, Transaction assignment ) {
	    LOGGER.info("assigning Transaction as " + assignment.toString() );

	    LoanPayment parentEntity = repository.findById( parentId ).get();
	    assignment = registry.project( Transaction.class, assignment.getTransactionId());

	    // ------------------------------------------
		// assign the Transaction to the parent entity
		// ------------------------------------------ 
	    parentEntity.setTransaction( assignment );

	    // ------------------------------------------
    	// save the parent entity
    	// ------------------------------------------ 
	    repository.save(parentEntity);
        
	    return parentEntity;
    }
    

	/*
	 * Unassign the Transaction
	 * 
	 * @param	parentId		UUID
	 * @return	LoanPayment
	 */
	public LoanPayment unAssignTransaction( UUID parentId ) {
		LoanPayment parentEntity = repository.findById(parentId).get();

		LOGGER.info("unAssigning Transaction on " + parentEntity.toString() );
		
	    // ------------------------------------------
		// null out the Transaction on the parent entithy
		// ------------------------------------------     
	    parentEntity.setTransaction(null);

	    // ------------------------------------------
		// save the parent entity
		// ------------------------------------------ 
	    repository.save(parentEntity);
    
	    return parentEntity;
	}




    /**
     * Method to retrieve the LoanPayment via an FindLoanPaymentQuery
     * @return 	query	FindLoanPaymentQuery
     */
    @SuppressWarnings("unused")
    public LoanPayment find( UUID id ) {
    	LOGGER.info("handling find using " + id.toString() );
    	try {
    		return repository.findById(id).get();
    	}
    	catch( IllegalArgumentException exc ) {
    		LOGGER.warn( "Failed to find a LoanPayment - {0}", exc.getMessage() );
    	}
    	return null;
    }
    
    /**
     * Method to retrieve a collection of all LoanPayments
     *
     * @param	query	FindAllLoanPaymentQuery 
     * @return 	List<LoanPayment> 
     */
    @SuppressWarnings("unused")
    public List<LoanPayment> findAll( FindAllLoanPaymentQuery query ) {
    	LOGGER.info("handling findAll using " + query.toString() );
    	try {
    		return repository.findAll();
    	}
    	catch( IllegalArgumentException exc ) {
    		LOGGER.warn( "Failed to find all LoanPayment - {0}", exc.getMessage() );
    	}
    	return null;
    }


    //--------------------------------------------------
    // attributes
    // --------------------------------------------------
	@Autowired
    protected final LoanPaymentRepository repository;
	protected final ProjectorRegistry registry;


    private static final Logger LOGGER 	= LoggerFactory.getLogger(LoanPaymentEntityProjector.class.getName());

}
