/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Spring Boot 3.5
 *
 * Domain Model:
 * Banking Industry Domain Model
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone National Bank Confidential
 *
 * 2026 Turnstone National Bank
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone National Bank - General Release
 */
package com.harbormaster.projector;

import java.util.HashMap;
import java.util.Map;
import java.util.UUID;

import org.springframework.stereotype.Component;
import org.springframework.context.ApplicationContext;

import com.harbormaster.entity.*;

/**
 * <h2>Projector Registry</h2>
 * <p>
 * The Projector Registry exists as a design pattern where recursion is possible during internal object binding.
 * In a project leveraging another projector in the case of association handling.  The registry completely decouples project's
 * offering a single source of access and truth of a projector.
 *
 * Since all Projectors implement interface EntityProjector, at startup the application context is queried for a Map of supporting instances
 *
 * </p>
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Spring Boot 3.5</td></tr>
 *          <tr><td>published</td><td>09/08/2026</td></tr>
 *          <tr><td>design pattern</td><td>ServiceLayer</td></tr>
 *          <tr><td>architecture style</td><td>Layered</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>Banking Industry Domain Model</td></tr>
 *          <tr><td>description</td><td>HCIDL model capturing core banking, payments, lending, cards, KYC, and FX capabilities.</td></tr>
 *          <tr><td>industry</td><td>Banking</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <p>@author Harbormaster Dev Team</p>
 */
@Component
public class ProjectorRegistry {

    private final Map<Class<?>, EntityProjector<?>> registry = new HashMap<>();

    public ProjectorRegistry(ApplicationContext context) {

        Map<String, EntityProjector> beans =
                context.getBeansOfType(EntityProjector.class);

        for (EntityProjector<?> projector : beans.values()) {
            registry.put(projector.getEntityClass(), projector);
        }
    }

    @SuppressWarnings("unchecked")
    public <T> EntityProjector<T> get(Class<T> entityType) {
        return (EntityProjector<T>) registry.get(entityType);
    }

    public <T> T project(Class<T> entityType, UUID id) {
        EntityProjector<T> projector = get(entityType);

        if (projector == null) {
            throw new IllegalArgumentException(
                    "No projector registered for " + entityType.getName());
        }

        return projector.find(id);
    }
}