/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Spring Boot 3.5
 *
 * Domain Model:
 * Banking Industry Domain Model
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone National Bank Confidential
 *
 * 2026 Turnstone National Bank
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone National Bank - General Release
 */
package com.harbormaster.projector;

import java.util.*;
import java.util.stream.Collectors;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.stereotype.Component;

import org.springframework.data.domain.Pageable;
import org.springframework.data.domain.PageRequest;
import org.springframework.stereotype.Component;

import com.harbormaster.api.*;
import com.harbormaster.entity.*;
import com.harbormaster.exception.*;
import com.harbormaster.repository.*;

/**
 * <h2>ThirdPartyProviderEntity Projector</h2>
 * <p>
 * The ThirdPartyProvider Entity Projector is responsible for maintaining the write model for
 * ThirdPartyProvider entities. It subscribes to domain events published by the ThirdPartyProvider
 * Aggregate and updates query-optimized projections used by REST APIs,
 * dashboards, and reporting services.
 * </p>
 * <p>
 * A Projector contains no business logic and never validates commands or
 * modifies the authoritative state of the domain.
 * </p>
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Spring Boot 3.5</td></tr>
 *          <tr><td>published</td><td>09/08/2026</td></tr>
 *          <tr><td>design pattern</td><td>ServiceLayer</td></tr>
 *          <tr><td>architecture style</td><td>Layered</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>Banking Industry Domain Model</td></tr>
 *          <tr><td>description</td><td>HCIDL model capturing core banking, payments, lending, cards, KYC, and FX capabilities.</td></tr>
 *          <tr><td>industry</td><td>Banking</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Services Used</h3>
 *
 *      <ul>
 *          <li>ThirdPartyProviderRepository</li>
 *          <li>ProjectorRegistry</li>
 *      </ul>
 *
 * <p>@author Harbormaster Dev Team</p>
 */
@Component("thirdPartyProvider-entity-projector")
public class ThirdPartyProviderEntityProjector implements EntityProjector<ThirdPartyProvider>{
		
	// core constructor
	public ThirdPartyProviderEntityProjector(ProjectorRegistry registry,
										ThirdPartyProviderRepository repository ) {
        this.registry 	= registry;
		this.repository = repository;
    }

	@Override
	public Class<ThirdPartyProvider> getEntityClass() {
		return ThirdPartyProvider.class;
	}

    /*
	 * Insert a ThirdPartyProvider
	 * 
     * @param	entity ThirdPartyProvider
     */
    public ThirdPartyProvider create( ThirdPartyProvider entity) {
	    LOGGER.info("creating " + entity.toString() );
	   
    	// ------------------------------------------
    	// persist a new one
    	// ------------------------------------------ 
	    return repository.save(entity);
        
    }

	/*
	 * Update a ThirdPartyProvider
	 * 
     * @param	entity ThirdPartyProvider
     */
    public ThirdPartyProvider update( ThirdPartyProvider entity) {
	    LOGGER.info("updating " + entity.toString() );

	    // ------------------------------------------
    	// save with an existing instance
    	// ------------------------------------------ 
		return repository.save(entity);

    }
    
	/*
	 * Delete a ThirdPartyProvider
	 * 
     * @param	id		UUID
     */
    public ThirdPartyProvider delete( UUID id ) {
	    LOGGER.info("deleting " + id.toString() );

    	// ------------------------------------------
    	// locate the entity by the provided id
    	// ------------------------------------------
	    ThirdPartyProvider entity = repository.findById(id).get();
	    
    	// ------------------------------------------
    	// delete what is discovered 
    	// ------------------------------------------
    	repository.delete( entity );
    	
    	return entity;
    }    

    /*
     * Assign a Bank
     * 
     * @param	parentId	UUID
     * @param	assignment 	Bank 
     * @return	ThirdPartyProvider
     */
    public ThirdPartyProvider assignBank( UUID parentId, Bank assignment ) {
	    LOGGER.info("assigning Bank as " + assignment.toString() );

	    ThirdPartyProvider parentEntity = repository.findById( parentId ).get();
	    assignment = registry.project( Bank.class, assignment.getBankId());

	    // ------------------------------------------
		// assign the Bank to the parent entity
		// ------------------------------------------ 
	    parentEntity.setBank( assignment );

	    // ------------------------------------------
    	// save the parent entity
    	// ------------------------------------------ 
	    repository.save(parentEntity);
        
	    return parentEntity;
    }
    

	/*
	 * Unassign the Bank
	 * 
	 * @param	parentId		UUID
	 * @return	ThirdPartyProvider
	 */
	public ThirdPartyProvider unAssignBank( UUID parentId ) {
		ThirdPartyProvider parentEntity = repository.findById(parentId).get();

		LOGGER.info("unAssigning Bank on " + parentEntity.toString() );
		
	    // ------------------------------------------
		// null out the Bank on the parent entithy
		// ------------------------------------------     
	    parentEntity.setBank(null);

	    // ------------------------------------------
		// save the parent entity
		// ------------------------------------------ 
	    repository.save(parentEntity);
    
	    return parentEntity;
	}


    /*
     * Add to the Consents
     * 
     * @param	parentID	UUID
     * @param	addTo		childType
     * @return	ThirdPartyProvider
     */
    public ThirdPartyProvider addToConsents( UUID parentId, Consent addTo ) {
	    LOGGER.info("handling AssignConsentsToThirdPartyProviderEvent - " );
	    
	    ThirdPartyProvider parentEntity = repository.findById(parentId).get();
	    Consent child = registry.project( Consent.class, addTo.getConsentId());
	    
	    parentEntity.getConsents().add( child );

	    // ------------------------------------------
    	// save 
    	// ------------------------------------------ 
	    repository.save(parentEntity);
        
	    return parentEntity;
    }
    

    /*
     * Remove from the Consents
     * 
     * @param	parentID	UUID
     * @param	removeFrom	childType
     * @return	ThirdPartyProvider
     */
	public ThirdPartyProvider removeFromConsents( UUID parentId, Consent removeFrom ) {
	    LOGGER.info("handling RemoveConsentsFromThirdPartyProviderEvent " );
	
	    ThirdPartyProvider parentEntity = repository.findById(parentId).get();
	    Consent child = registry.project( Consent.class, removeFrom.getConsentId());
	    
	    parentEntity.getConsents().remove( child );
	
	    // ------------------------------------------
		// save
		// ------------------------------------------ 
	    update(parentEntity);
	    
	    return parentEntity;
	}



    /**
     * Method to retrieve the ThirdPartyProvider via an FindThirdPartyProviderQuery
     * @return 	query	FindThirdPartyProviderQuery
     */
    @SuppressWarnings("unused")
    public ThirdPartyProvider find( UUID id ) {
    	LOGGER.info("handling find using " + id.toString() );
    	try {
    		return repository.findById(id).get();
    	}
    	catch( IllegalArgumentException exc ) {
    		LOGGER.warn( "Failed to find a ThirdPartyProvider - {0}", exc.getMessage() );
    	}
    	return null;
    }
    
    /**
     * Method to retrieve a collection of all ThirdPartyProviders
     *
     * @param	query	FindAllThirdPartyProviderQuery 
     * @return 	List<ThirdPartyProvider> 
     */
    @SuppressWarnings("unused")
    public List<ThirdPartyProvider> findAll( FindAllThirdPartyProviderQuery query ) {
    	LOGGER.info("handling findAll using " + query.toString() );
    	try {
    		return repository.findAll();
    	}
    	catch( IllegalArgumentException exc ) {
    		LOGGER.warn( "Failed to find all ThirdPartyProvider - {0}", exc.getMessage() );
    	}
    	return null;
    }


    //--------------------------------------------------
    // attributes
    // --------------------------------------------------
	@Autowired
    protected final ThirdPartyProviderRepository repository;
	protected final ProjectorRegistry registry;


    private static final Logger LOGGER 	= LoggerFactory.getLogger(ThirdPartyProviderEntityProjector.class.getName());

}
