/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Spring Boot 3.5
 *
 * Domain Model:
 * Banking Industry Domain Model
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone National Bank Confidential
 *
 * 2026 Turnstone National Bank
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone National Bank - General Release
 */
		package com.harbormaster.validator;

import org.springframework.stereotype.Component;
import org.springframework.util.Assert;

import com.harbormaster.api.*;
import com.harbormaster.exception.*;

/**
 * <h2>AccountValidation</h2>
 * <p>
 * The Account Validation  handles state validation of a Account include direct attributes and single/multiple associations.
 * </p>
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Spring Boot 3.5</td></tr>
 *          <tr><td>published</td><td>09/08/2026</td></tr>
 *          <tr><td>design pattern</td><td>ServiceLayer</td></tr>
 *          <tr><td>architecture style</td><td>Layered</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>Banking Industry Domain Model</td></tr>
 *          <tr><td>description</td><td>HCIDL model capturing core banking, payments, lending, cards, KYC, and FX capabilities.</td></tr>
 *          <tr><td>industry</td><td>Banking</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Commands Validated</h3>
 *      <ul>
 *      <li>CreateAccountCommand</li>
 *      <li>UpdateAccountCommand</li>
 *      <li>DeleteAccountCommand</li>
 *set( false = false )
  *       <li>AssignBankToAccountCommand</li>
 *       <li>UnAssignBankFromAccountCommand</li>
  *       <li>AssignBranchToAccountCommand</li>
 *       <li>UnAssignBranchFromAccountCommand</li>
  *       <li>AssignProductToAccountCommand</li>
 *       <li>UnAssignProductFromAccountCommand</li>
   *       <li>AssignOwnersToAccountCommand</li>
 *       <li>RemoveOwnersFromAccountCommand</li>
 *   </ul>
 *
  *       <li>AssignTransactionsToAccountCommand</li>
 *       <li>RemoveTransactionsFromAccountCommand</li>
 *   </ul>
 *
  *       <li>AssignStatementsToAccountCommand</li>
 *       <li>RemoveStatementsFromAccountCommand</li>
 *   </ul>
 *
  *       <li>AssignStandingInstructionsToAccountCommand</li>
 *       <li>RemoveStandingInstructionsFromAccountCommand</li>
 *   </ul>
 *
  *       <li>AssignFeeChargesToAccountCommand</li>
 *       <li>RemoveFeeChargesFromAccountCommand</li>
 *   </ul>
 *
  * <p>
 * @author Harbormaster Dev Team
 * </p>
 */
@Component
public class AccountValidator {

	/**
	 * default constructor
	 */
	protected AccountValidator() {
	}


	/**
	 * handles creation validation for a Account
	 */
	public void validate( CreateAccountCommand account )throws ValidationException {
		if ( account == null )
		throw new ValidationException( "Account", "validating CreateAccountCommand" );
		if ( account.getAccountNumber() == null )
		throw new ValidationException( "Account", "validating access on getAccountNumber" );
		if ( account.getIban() == null )
		throw new ValidationException( "Account", "validating access on getIban" );
		if ( account.getAccountName() == null )
		throw new ValidationException( "Account", "validating access on getAccountName" );
		if ( account.getCurrency() == null )
		throw new ValidationException( "Account", "validating access on getCurrency" );
		if ( account.getOpenedOn() == null )
		throw new ValidationException( "Account", "validating access on getOpenedOn" );
		if ( account.getClosedOn() == null )
		throw new ValidationException( "Account", "validating access on getClosedOn" );
	}

	/**
	 * handles update validation for a Account
	 */
	public void validate( UpdateAccountCommand account ) throws ValidationException {
		if ( account == null )
		throw new ValidationException( "Account", "validating UpdateAccountCommand" );
		if ( account.getAccountNumber() == null )
		throw new ValidationException( "Account", "validating method getAccountNumber" );
		if ( account.getIban() == null )
		throw new ValidationException( "Account", "validating method getIban" );
		if ( account.getAccountName() == null )
		throw new ValidationException( "Account", "validating method getAccountName" );
		if ( account.getCurrency() == null )
		throw new ValidationException( "Account", "validating method getCurrency" );
		if ( account.getOpenedOn() == null )
		throw new ValidationException( "Account", "validating method getOpenedOn" );
		if ( account.getClosedOn() == null )
		throw new ValidationException( "Account", "validating method getClosedOn" );
	}

/**
 * handles delete validation for a Account
 */
	public void validate( DeleteAccountCommand account ) throws ValidationException {
		if ( account == null )
			throw new ValidationException( "Account", "validating DeleteAccountCommand" );
	}

/**
 * handles fetchOne validation for a Account
 */
	public void validate( AccountFetchOneSummary summary ) throws ValidationException {
		if ( summary == null )
			throw new ValidationException( "Account", "validating summary" );
	}

	/**
	 * handles assign Bank validation for a Account
	 *
	 * @param	command AssignBankToAccountCommand
	 */
	public void validate( AssignBankToAccountCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "Account", "validating AssignBankToAccountCommand" );

		if ( command.getAccountId() == null )
		throw new ValidationException( "Account", "validating identifier on AssignBankToAccountCommand" );

		if ( command.getAssignment() == null )
			throw new ValidationException( "Account", "validating assignment" );
	}

	/**
	 * handles unassign Bank validation for a Account
	 *
	 * @param	command UnAssignBankFromAccountCommand
	 */
	public void validate( UnAssignBankFromAccountCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "Account", "validating UnAssignBankFromAccountCommand" );

		if ( command.getAccountId() == null )
		throw new ValidationException( "Account", "validating identity on UnAssignBankFromAccountCommand" );
	}
	/**
	 * handles assign Branch validation for a Account
	 *
	 * @param	command AssignBranchToAccountCommand
	 */
	public void validate( AssignBranchToAccountCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "Account", "validating AssignBranchToAccountCommand" );

		if ( command.getAccountId() == null )
		throw new ValidationException( "Account", "validating identifier on AssignBranchToAccountCommand" );

		if ( command.getAssignment() == null )
			throw new ValidationException( "Account", "validating assignment" );
	}

	/**
	 * handles unassign Branch validation for a Account
	 *
	 * @param	command UnAssignBranchFromAccountCommand
	 */
	public void validate( UnAssignBranchFromAccountCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "Account", "validating UnAssignBranchFromAccountCommand" );

		if ( command.getAccountId() == null )
		throw new ValidationException( "Account", "validating identity on UnAssignBranchFromAccountCommand" );
	}
	/**
	 * handles assign Product validation for a Account
	 *
	 * @param	command AssignProductToAccountCommand
	 */
	public void validate( AssignProductToAccountCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "Account", "validating AssignProductToAccountCommand" );

		if ( command.getAccountId() == null )
		throw new ValidationException( "Account", "validating identifier on AssignProductToAccountCommand" );

		if ( command.getAssignment() == null )
			throw new ValidationException( "Account", "validating assignment" );
	}

	/**
	 * handles unassign Product validation for a Account
	 *
	 * @param	command UnAssignProductFromAccountCommand
	 */
	public void validate( UnAssignProductFromAccountCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "Account", "validating UnAssignProductFromAccountCommand" );

		if ( command.getAccountId() == null )
		throw new ValidationException( "Account", "validating identity on UnAssignProductFromAccountCommand" );
	}

	/**
	 * handles add to Owners validation for a Account
	 *
	 * @param	command AssignOwnersToAccountCommand
	 */
	public void validate( AssignOwnersToAccountCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "Account", "validating AssignOwnersToAccountCommand" );

		if ( command.getAccountId() == null )
		throw new ValidationException( "Account", "validating identity on AssignOwnersToAccountCommand" );

		if ( command.getAddTo() == null )
			throw new ValidationException( "Account", "validating addTo attribute on AssignOwnersToAccountCommand" );

	}

	/**
	 * handles remove from Owners validation for a Account
	 *
	 * @param	command RemoveOwnersFromAccountCommand
	 */
	public void validate( RemoveOwnersFromAccountCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException("Account", "validating RemoveOwnersFromAccountCommand" );

		if( command.getAccountId() == null )
			throw new ValidationException("Account", "validating id on RemoveOwnersFromAccountCommand" );

		if( command.getRemoveFrom() == null )
			throw new ValidationException("Account", "validating remove from RemoveOwnersFromAccountCommand" );

		if( command.getRemoveFrom().getCustomerId() == null )
			throw new ValidationException("Account", "validating id on remove from RemoveOwnersFromAccountCommand" );
	}

	/**
	 * handles add to Transactions validation for a Account
	 *
	 * @param	command AssignTransactionsToAccountCommand
	 */
	public void validate( AssignTransactionsToAccountCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "Account", "validating AssignTransactionsToAccountCommand" );

		if ( command.getAccountId() == null )
		throw new ValidationException( "Account", "validating identity on AssignTransactionsToAccountCommand" );

		if ( command.getAddTo() == null )
			throw new ValidationException( "Account", "validating addTo attribute on AssignTransactionsToAccountCommand" );

	}

	/**
	 * handles remove from Transactions validation for a Account
	 *
	 * @param	command RemoveTransactionsFromAccountCommand
	 */
	public void validate( RemoveTransactionsFromAccountCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException("Account", "validating RemoveTransactionsFromAccountCommand" );

		if( command.getAccountId() == null )
			throw new ValidationException("Account", "validating id on RemoveTransactionsFromAccountCommand" );

		if( command.getRemoveFrom() == null )
			throw new ValidationException("Account", "validating remove from RemoveTransactionsFromAccountCommand" );

		if( command.getRemoveFrom().getTransactionId() == null )
			throw new ValidationException("Account", "validating id on remove from RemoveTransactionsFromAccountCommand" );
	}

	/**
	 * handles add to Statements validation for a Account
	 *
	 * @param	command AssignStatementsToAccountCommand
	 */
	public void validate( AssignStatementsToAccountCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "Account", "validating AssignStatementsToAccountCommand" );

		if ( command.getAccountId() == null )
		throw new ValidationException( "Account", "validating identity on AssignStatementsToAccountCommand" );

		if ( command.getAddTo() == null )
			throw new ValidationException( "Account", "validating addTo attribute on AssignStatementsToAccountCommand" );

	}

	/**
	 * handles remove from Statements validation for a Account
	 *
	 * @param	command RemoveStatementsFromAccountCommand
	 */
	public void validate( RemoveStatementsFromAccountCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException("Account", "validating RemoveStatementsFromAccountCommand" );

		if( command.getAccountId() == null )
			throw new ValidationException("Account", "validating id on RemoveStatementsFromAccountCommand" );

		if( command.getRemoveFrom() == null )
			throw new ValidationException("Account", "validating remove from RemoveStatementsFromAccountCommand" );

		if( command.getRemoveFrom().getAccountStatementId() == null )
			throw new ValidationException("Account", "validating id on remove from RemoveStatementsFromAccountCommand" );
	}

	/**
	 * handles add to StandingInstructions validation for a Account
	 *
	 * @param	command AssignStandingInstructionsToAccountCommand
	 */
	public void validate( AssignStandingInstructionsToAccountCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "Account", "validating AssignStandingInstructionsToAccountCommand" );

		if ( command.getAccountId() == null )
		throw new ValidationException( "Account", "validating identity on AssignStandingInstructionsToAccountCommand" );

		if ( command.getAddTo() == null )
			throw new ValidationException( "Account", "validating addTo attribute on AssignStandingInstructionsToAccountCommand" );

	}

	/**
	 * handles remove from StandingInstructions validation for a Account
	 *
	 * @param	command RemoveStandingInstructionsFromAccountCommand
	 */
	public void validate( RemoveStandingInstructionsFromAccountCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException("Account", "validating RemoveStandingInstructionsFromAccountCommand" );

		if( command.getAccountId() == null )
			throw new ValidationException("Account", "validating id on RemoveStandingInstructionsFromAccountCommand" );

		if( command.getRemoveFrom() == null )
			throw new ValidationException("Account", "validating remove from RemoveStandingInstructionsFromAccountCommand" );

		if( command.getRemoveFrom().getStandingInstructionId() == null )
			throw new ValidationException("Account", "validating id on remove from RemoveStandingInstructionsFromAccountCommand" );
	}

	/**
	 * handles add to FeeCharges validation for a Account
	 *
	 * @param	command AssignFeeChargesToAccountCommand
	 */
	public void validate( AssignFeeChargesToAccountCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "Account", "validating AssignFeeChargesToAccountCommand" );

		if ( command.getAccountId() == null )
		throw new ValidationException( "Account", "validating identity on AssignFeeChargesToAccountCommand" );

		if ( command.getAddTo() == null )
			throw new ValidationException( "Account", "validating addTo attribute on AssignFeeChargesToAccountCommand" );

	}

	/**
	 * handles remove from FeeCharges validation for a Account
	 *
	 * @param	command RemoveFeeChargesFromAccountCommand
	 */
	public void validate( RemoveFeeChargesFromAccountCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException("Account", "validating RemoveFeeChargesFromAccountCommand" );

		if( command.getAccountId() == null )
			throw new ValidationException("Account", "validating id on RemoveFeeChargesFromAccountCommand" );

		if( command.getRemoveFrom() == null )
			throw new ValidationException("Account", "validating remove from RemoveFeeChargesFromAccountCommand" );

		if( command.getRemoveFrom().getFeeChargeId() == null )
			throw new ValidationException("Account", "validating id on remove from RemoveFeeChargesFromAccountCommand" );
	}


}
