/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Spring Boot 3.5
 *
 * Domain Model:
 * Banking Industry Domain Model
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone National Bank Confidential
 *
 * 2026 Turnstone National Bank
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone National Bank - General Release
 */
		package com.harbormaster.validator;

import org.springframework.stereotype.Component;
import org.springframework.util.Assert;

import com.harbormaster.api.*;
import com.harbormaster.exception.*;

/**
 * <h2>ConsentValidation</h2>
 * <p>
 * The Consent Validation  handles state validation of a Consent include direct attributes and single/multiple associations.
 * </p>
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Spring Boot 3.5</td></tr>
 *          <tr><td>published</td><td>09/08/2026</td></tr>
 *          <tr><td>design pattern</td><td>ServiceLayer</td></tr>
 *          <tr><td>architecture style</td><td>Layered</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>Banking Industry Domain Model</td></tr>
 *          <tr><td>description</td><td>HCIDL model capturing core banking, payments, lending, cards, KYC, and FX capabilities.</td></tr>
 *          <tr><td>industry</td><td>Banking</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Commands Validated</h3>
 *      <ul>
 *      <li>CreateConsentCommand</li>
 *      <li>UpdateConsentCommand</li>
 *      <li>DeleteConsentCommand</li>
 *set( false = false )
  *       <li>AssignCustomerToConsentCommand</li>
 *       <li>UnAssignCustomerFromConsentCommand</li>
  *       <li>AssignBankToConsentCommand</li>
 *       <li>UnAssignBankFromConsentCommand</li>
  *       <li>AssignThirdPartyProviderToConsentCommand</li>
 *       <li>UnAssignThirdPartyProviderFromConsentCommand</li>
   *       <li>AssignAuthorizedAccountsToConsentCommand</li>
 *       <li>RemoveAuthorizedAccountsFromConsentCommand</li>
 *   </ul>
 *
  * <p>
 * @author Harbormaster Dev Team
 * </p>
 */
@Component
public class ConsentValidator {

	/**
	 * default constructor
	 */
	protected ConsentValidator() {
	}


	/**
	 * handles creation validation for a Consent
	 */
	public void validate( CreateConsentCommand consent )throws ValidationException {
		if ( consent == null )
		throw new ValidationException( "Consent", "validating CreateConsentCommand" );
		if ( consent.getGrantedOn() == null )
		throw new ValidationException( "Consent", "validating access on getGrantedOn" );
		if ( consent.getExpiresOn() == null )
		throw new ValidationException( "Consent", "validating access on getExpiresOn" );
	}

	/**
	 * handles update validation for a Consent
	 */
	public void validate( UpdateConsentCommand consent ) throws ValidationException {
		if ( consent == null )
		throw new ValidationException( "Consent", "validating UpdateConsentCommand" );
		if ( consent.getGrantedOn() == null )
		throw new ValidationException( "Consent", "validating method getGrantedOn" );
		if ( consent.getExpiresOn() == null )
		throw new ValidationException( "Consent", "validating method getExpiresOn" );
	}

/**
 * handles delete validation for a Consent
 */
	public void validate( DeleteConsentCommand consent ) throws ValidationException {
		if ( consent == null )
			throw new ValidationException( "Consent", "validating DeleteConsentCommand" );
	}

/**
 * handles fetchOne validation for a Consent
 */
	public void validate( ConsentFetchOneSummary summary ) throws ValidationException {
		if ( summary == null )
			throw new ValidationException( "Consent", "validating summary" );
	}

	/**
	 * handles assign Customer validation for a Consent
	 *
	 * @param	command AssignCustomerToConsentCommand
	 */
	public void validate( AssignCustomerToConsentCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "Consent", "validating AssignCustomerToConsentCommand" );

		if ( command.getConsentId() == null )
		throw new ValidationException( "Consent", "validating identifier on AssignCustomerToConsentCommand" );

		if ( command.getAssignment() == null )
			throw new ValidationException( "Consent", "validating assignment" );
	}

	/**
	 * handles unassign Customer validation for a Consent
	 *
	 * @param	command UnAssignCustomerFromConsentCommand
	 */
	public void validate( UnAssignCustomerFromConsentCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "Consent", "validating UnAssignCustomerFromConsentCommand" );

		if ( command.getConsentId() == null )
		throw new ValidationException( "Consent", "validating identity on UnAssignCustomerFromConsentCommand" );
	}
	/**
	 * handles assign Bank validation for a Consent
	 *
	 * @param	command AssignBankToConsentCommand
	 */
	public void validate( AssignBankToConsentCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "Consent", "validating AssignBankToConsentCommand" );

		if ( command.getConsentId() == null )
		throw new ValidationException( "Consent", "validating identifier on AssignBankToConsentCommand" );

		if ( command.getAssignment() == null )
			throw new ValidationException( "Consent", "validating assignment" );
	}

	/**
	 * handles unassign Bank validation for a Consent
	 *
	 * @param	command UnAssignBankFromConsentCommand
	 */
	public void validate( UnAssignBankFromConsentCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "Consent", "validating UnAssignBankFromConsentCommand" );

		if ( command.getConsentId() == null )
		throw new ValidationException( "Consent", "validating identity on UnAssignBankFromConsentCommand" );
	}
	/**
	 * handles assign ThirdPartyProvider validation for a Consent
	 *
	 * @param	command AssignThirdPartyProviderToConsentCommand
	 */
	public void validate( AssignThirdPartyProviderToConsentCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "Consent", "validating AssignThirdPartyProviderToConsentCommand" );

		if ( command.getConsentId() == null )
		throw new ValidationException( "Consent", "validating identifier on AssignThirdPartyProviderToConsentCommand" );

		if ( command.getAssignment() == null )
			throw new ValidationException( "Consent", "validating assignment" );
	}

	/**
	 * handles unassign ThirdPartyProvider validation for a Consent
	 *
	 * @param	command UnAssignThirdPartyProviderFromConsentCommand
	 */
	public void validate( UnAssignThirdPartyProviderFromConsentCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "Consent", "validating UnAssignThirdPartyProviderFromConsentCommand" );

		if ( command.getConsentId() == null )
		throw new ValidationException( "Consent", "validating identity on UnAssignThirdPartyProviderFromConsentCommand" );
	}

	/**
	 * handles add to AuthorizedAccounts validation for a Consent
	 *
	 * @param	command AssignAuthorizedAccountsToConsentCommand
	 */
	public void validate( AssignAuthorizedAccountsToConsentCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "Consent", "validating AssignAuthorizedAccountsToConsentCommand" );

		if ( command.getConsentId() == null )
		throw new ValidationException( "Consent", "validating identity on AssignAuthorizedAccountsToConsentCommand" );

		if ( command.getAddTo() == null )
			throw new ValidationException( "Consent", "validating addTo attribute on AssignAuthorizedAccountsToConsentCommand" );

	}

	/**
	 * handles remove from AuthorizedAccounts validation for a Consent
	 *
	 * @param	command RemoveAuthorizedAccountsFromConsentCommand
	 */
	public void validate( RemoveAuthorizedAccountsFromConsentCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException("Consent", "validating RemoveAuthorizedAccountsFromConsentCommand" );

		if( command.getConsentId() == null )
			throw new ValidationException("Consent", "validating id on RemoveAuthorizedAccountsFromConsentCommand" );

		if( command.getRemoveFrom() == null )
			throw new ValidationException("Consent", "validating remove from RemoveAuthorizedAccountsFromConsentCommand" );

		if( command.getRemoveFrom().getAccountId() == null )
			throw new ValidationException("Consent", "validating id on remove from RemoveAuthorizedAccountsFromConsentCommand" );
	}


}
