/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Spring Boot 3.5
 *
 * Domain Model:
 * Banking Industry Domain Model
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone National Bank Confidential
 *
 * 2026 Turnstone National Bank
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone National Bank - General Release
 */
		package com.harbormaster.validator;

import org.springframework.stereotype.Component;
import org.springframework.util.Assert;

import com.harbormaster.api.*;
import com.harbormaster.exception.*;

/**
 * <h2>CustomerValidation</h2>
 * <p>
 * The Customer Validation  handles state validation of a Customer include direct attributes and single/multiple associations.
 * </p>
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Spring Boot 3.5</td></tr>
 *          <tr><td>published</td><td>09/08/2026</td></tr>
 *          <tr><td>design pattern</td><td>ServiceLayer</td></tr>
 *          <tr><td>architecture style</td><td>Layered</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>Banking Industry Domain Model</td></tr>
 *          <tr><td>description</td><td>HCIDL model capturing core banking, payments, lending, cards, KYC, and FX capabilities.</td></tr>
 *          <tr><td>industry</td><td>Banking</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Commands Validated</h3>
 *      <ul>
 *      <li>CreateCustomerCommand</li>
 *      <li>UpdateCustomerCommand</li>
 *      <li>DeleteCustomerCommand</li>
 *set( false = false )
  *       <li>AssignBankToCustomerCommand</li>
 *       <li>UnAssignBankFromCustomerCommand</li>
   *       <li>AssignAccountsToCustomerCommand</li>
 *       <li>RemoveAccountsFromCustomerCommand</li>
 *   </ul>
 *
  *       <li>AssignLoanAccountsToCustomerCommand</li>
 *       <li>RemoveLoanAccountsFromCustomerCommand</li>
 *   </ul>
 *
  *       <li>AssignPaymentCardsToCustomerCommand</li>
 *       <li>RemovePaymentCardsFromCustomerCommand</li>
 *   </ul>
 *
  *       <li>AssignExternalAccountsToCustomerCommand</li>
 *       <li>RemoveExternalAccountsFromCustomerCommand</li>
 *   </ul>
 *
  *       <li>AssignFundsTransfersToCustomerCommand</li>
 *       <li>RemoveFundsTransfersFromCustomerCommand</li>
 *   </ul>
 *
  *       <li>AssignDisputesToCustomerCommand</li>
 *       <li>RemoveDisputesFromCustomerCommand</li>
 *   </ul>
 *
  *       <li>AssignKycProfilesToCustomerCommand</li>
 *       <li>RemoveKycProfilesFromCustomerCommand</li>
 *   </ul>
 *
  *       <li>AssignConsentsToCustomerCommand</li>
 *       <li>RemoveConsentsFromCustomerCommand</li>
 *   </ul>
 *
  * <p>
 * @author Harbormaster Dev Team
 * </p>
 */
@Component
public class CustomerValidator {

	/**
	 * default constructor
	 */
	protected CustomerValidator() {
	}


	/**
	 * handles creation validation for a Customer
	 */
	public void validate( CreateCustomerCommand customer )throws ValidationException {
		if ( customer == null )
		throw new ValidationException( "Customer", "validating CreateCustomerCommand" );
		if ( customer.getFirstName() == null )
		throw new ValidationException( "Customer", "validating access on getFirstName" );
		if ( customer.getLastName() == null )
		throw new ValidationException( "Customer", "validating access on getLastName" );
		if ( customer.getLegalName() == null )
		throw new ValidationException( "Customer", "validating access on getLegalName" );
		if ( customer.getDateOfBirth() == null )
		throw new ValidationException( "Customer", "validating access on getDateOfBirth" );
		if ( customer.getTaxId() == null )
		throw new ValidationException( "Customer", "validating access on getTaxId" );
		if ( customer.getEmail() == null )
		throw new ValidationException( "Customer", "validating access on getEmail" );
		if ( customer.getPhone() == null )
		throw new ValidationException( "Customer", "validating access on getPhone" );
		if ( customer.getAddress() == null )
		throw new ValidationException( "Customer", "validating access on getAddress" );
	}

	/**
	 * handles update validation for a Customer
	 */
	public void validate( UpdateCustomerCommand customer ) throws ValidationException {
		if ( customer == null )
		throw new ValidationException( "Customer", "validating UpdateCustomerCommand" );
		if ( customer.getFirstName() == null )
		throw new ValidationException( "Customer", "validating method getFirstName" );
		if ( customer.getLastName() == null )
		throw new ValidationException( "Customer", "validating method getLastName" );
		if ( customer.getLegalName() == null )
		throw new ValidationException( "Customer", "validating method getLegalName" );
		if ( customer.getDateOfBirth() == null )
		throw new ValidationException( "Customer", "validating method getDateOfBirth" );
		if ( customer.getTaxId() == null )
		throw new ValidationException( "Customer", "validating method getTaxId" );
		if ( customer.getEmail() == null )
		throw new ValidationException( "Customer", "validating method getEmail" );
		if ( customer.getPhone() == null )
		throw new ValidationException( "Customer", "validating method getPhone" );
		if ( customer.getAddress() == null )
		throw new ValidationException( "Customer", "validating method getAddress" );
	}

/**
 * handles delete validation for a Customer
 */
	public void validate( DeleteCustomerCommand customer ) throws ValidationException {
		if ( customer == null )
			throw new ValidationException( "Customer", "validating DeleteCustomerCommand" );
	}

/**
 * handles fetchOne validation for a Customer
 */
	public void validate( CustomerFetchOneSummary summary ) throws ValidationException {
		if ( summary == null )
			throw new ValidationException( "Customer", "validating summary" );
	}

	/**
	 * handles assign Bank validation for a Customer
	 *
	 * @param	command AssignBankToCustomerCommand
	 */
	public void validate( AssignBankToCustomerCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "Customer", "validating AssignBankToCustomerCommand" );

		if ( command.getCustomerId() == null )
		throw new ValidationException( "Customer", "validating identifier on AssignBankToCustomerCommand" );

		if ( command.getAssignment() == null )
			throw new ValidationException( "Customer", "validating assignment" );
	}

	/**
	 * handles unassign Bank validation for a Customer
	 *
	 * @param	command UnAssignBankFromCustomerCommand
	 */
	public void validate( UnAssignBankFromCustomerCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "Customer", "validating UnAssignBankFromCustomerCommand" );

		if ( command.getCustomerId() == null )
		throw new ValidationException( "Customer", "validating identity on UnAssignBankFromCustomerCommand" );
	}

	/**
	 * handles add to Accounts validation for a Customer
	 *
	 * @param	command AssignAccountsToCustomerCommand
	 */
	public void validate( AssignAccountsToCustomerCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "Customer", "validating AssignAccountsToCustomerCommand" );

		if ( command.getCustomerId() == null )
		throw new ValidationException( "Customer", "validating identity on AssignAccountsToCustomerCommand" );

		if ( command.getAddTo() == null )
			throw new ValidationException( "Customer", "validating addTo attribute on AssignAccountsToCustomerCommand" );

	}

	/**
	 * handles remove from Accounts validation for a Customer
	 *
	 * @param	command RemoveAccountsFromCustomerCommand
	 */
	public void validate( RemoveAccountsFromCustomerCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException("Customer", "validating RemoveAccountsFromCustomerCommand" );

		if( command.getCustomerId() == null )
			throw new ValidationException("Customer", "validating id on RemoveAccountsFromCustomerCommand" );

		if( command.getRemoveFrom() == null )
			throw new ValidationException("Customer", "validating remove from RemoveAccountsFromCustomerCommand" );

		if( command.getRemoveFrom().getAccountId() == null )
			throw new ValidationException("Customer", "validating id on remove from RemoveAccountsFromCustomerCommand" );
	}

	/**
	 * handles add to LoanAccounts validation for a Customer
	 *
	 * @param	command AssignLoanAccountsToCustomerCommand
	 */
	public void validate( AssignLoanAccountsToCustomerCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "Customer", "validating AssignLoanAccountsToCustomerCommand" );

		if ( command.getCustomerId() == null )
		throw new ValidationException( "Customer", "validating identity on AssignLoanAccountsToCustomerCommand" );

		if ( command.getAddTo() == null )
			throw new ValidationException( "Customer", "validating addTo attribute on AssignLoanAccountsToCustomerCommand" );

	}

	/**
	 * handles remove from LoanAccounts validation for a Customer
	 *
	 * @param	command RemoveLoanAccountsFromCustomerCommand
	 */
	public void validate( RemoveLoanAccountsFromCustomerCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException("Customer", "validating RemoveLoanAccountsFromCustomerCommand" );

		if( command.getCustomerId() == null )
			throw new ValidationException("Customer", "validating id on RemoveLoanAccountsFromCustomerCommand" );

		if( command.getRemoveFrom() == null )
			throw new ValidationException("Customer", "validating remove from RemoveLoanAccountsFromCustomerCommand" );

		if( command.getRemoveFrom().getLoanAccountId() == null )
			throw new ValidationException("Customer", "validating id on remove from RemoveLoanAccountsFromCustomerCommand" );
	}

	/**
	 * handles add to PaymentCards validation for a Customer
	 *
	 * @param	command AssignPaymentCardsToCustomerCommand
	 */
	public void validate( AssignPaymentCardsToCustomerCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "Customer", "validating AssignPaymentCardsToCustomerCommand" );

		if ( command.getCustomerId() == null )
		throw new ValidationException( "Customer", "validating identity on AssignPaymentCardsToCustomerCommand" );

		if ( command.getAddTo() == null )
			throw new ValidationException( "Customer", "validating addTo attribute on AssignPaymentCardsToCustomerCommand" );

	}

	/**
	 * handles remove from PaymentCards validation for a Customer
	 *
	 * @param	command RemovePaymentCardsFromCustomerCommand
	 */
	public void validate( RemovePaymentCardsFromCustomerCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException("Customer", "validating RemovePaymentCardsFromCustomerCommand" );

		if( command.getCustomerId() == null )
			throw new ValidationException("Customer", "validating id on RemovePaymentCardsFromCustomerCommand" );

		if( command.getRemoveFrom() == null )
			throw new ValidationException("Customer", "validating remove from RemovePaymentCardsFromCustomerCommand" );

		if( command.getRemoveFrom().getPaymentCardId() == null )
			throw new ValidationException("Customer", "validating id on remove from RemovePaymentCardsFromCustomerCommand" );
	}

	/**
	 * handles add to ExternalAccounts validation for a Customer
	 *
	 * @param	command AssignExternalAccountsToCustomerCommand
	 */
	public void validate( AssignExternalAccountsToCustomerCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "Customer", "validating AssignExternalAccountsToCustomerCommand" );

		if ( command.getCustomerId() == null )
		throw new ValidationException( "Customer", "validating identity on AssignExternalAccountsToCustomerCommand" );

		if ( command.getAddTo() == null )
			throw new ValidationException( "Customer", "validating addTo attribute on AssignExternalAccountsToCustomerCommand" );

	}

	/**
	 * handles remove from ExternalAccounts validation for a Customer
	 *
	 * @param	command RemoveExternalAccountsFromCustomerCommand
	 */
	public void validate( RemoveExternalAccountsFromCustomerCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException("Customer", "validating RemoveExternalAccountsFromCustomerCommand" );

		if( command.getCustomerId() == null )
			throw new ValidationException("Customer", "validating id on RemoveExternalAccountsFromCustomerCommand" );

		if( command.getRemoveFrom() == null )
			throw new ValidationException("Customer", "validating remove from RemoveExternalAccountsFromCustomerCommand" );

		if( command.getRemoveFrom().getExternalAccountId() == null )
			throw new ValidationException("Customer", "validating id on remove from RemoveExternalAccountsFromCustomerCommand" );
	}

	/**
	 * handles add to FundsTransfers validation for a Customer
	 *
	 * @param	command AssignFundsTransfersToCustomerCommand
	 */
	public void validate( AssignFundsTransfersToCustomerCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "Customer", "validating AssignFundsTransfersToCustomerCommand" );

		if ( command.getCustomerId() == null )
		throw new ValidationException( "Customer", "validating identity on AssignFundsTransfersToCustomerCommand" );

		if ( command.getAddTo() == null )
			throw new ValidationException( "Customer", "validating addTo attribute on AssignFundsTransfersToCustomerCommand" );

	}

	/**
	 * handles remove from FundsTransfers validation for a Customer
	 *
	 * @param	command RemoveFundsTransfersFromCustomerCommand
	 */
	public void validate( RemoveFundsTransfersFromCustomerCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException("Customer", "validating RemoveFundsTransfersFromCustomerCommand" );

		if( command.getCustomerId() == null )
			throw new ValidationException("Customer", "validating id on RemoveFundsTransfersFromCustomerCommand" );

		if( command.getRemoveFrom() == null )
			throw new ValidationException("Customer", "validating remove from RemoveFundsTransfersFromCustomerCommand" );

		if( command.getRemoveFrom().getFundsTransferId() == null )
			throw new ValidationException("Customer", "validating id on remove from RemoveFundsTransfersFromCustomerCommand" );
	}

	/**
	 * handles add to Disputes validation for a Customer
	 *
	 * @param	command AssignDisputesToCustomerCommand
	 */
	public void validate( AssignDisputesToCustomerCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "Customer", "validating AssignDisputesToCustomerCommand" );

		if ( command.getCustomerId() == null )
		throw new ValidationException( "Customer", "validating identity on AssignDisputesToCustomerCommand" );

		if ( command.getAddTo() == null )
			throw new ValidationException( "Customer", "validating addTo attribute on AssignDisputesToCustomerCommand" );

	}

	/**
	 * handles remove from Disputes validation for a Customer
	 *
	 * @param	command RemoveDisputesFromCustomerCommand
	 */
	public void validate( RemoveDisputesFromCustomerCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException("Customer", "validating RemoveDisputesFromCustomerCommand" );

		if( command.getCustomerId() == null )
			throw new ValidationException("Customer", "validating id on RemoveDisputesFromCustomerCommand" );

		if( command.getRemoveFrom() == null )
			throw new ValidationException("Customer", "validating remove from RemoveDisputesFromCustomerCommand" );

		if( command.getRemoveFrom().getDisputeId() == null )
			throw new ValidationException("Customer", "validating id on remove from RemoveDisputesFromCustomerCommand" );
	}

	/**
	 * handles add to KycProfiles validation for a Customer
	 *
	 * @param	command AssignKycProfilesToCustomerCommand
	 */
	public void validate( AssignKycProfilesToCustomerCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "Customer", "validating AssignKycProfilesToCustomerCommand" );

		if ( command.getCustomerId() == null )
		throw new ValidationException( "Customer", "validating identity on AssignKycProfilesToCustomerCommand" );

		if ( command.getAddTo() == null )
			throw new ValidationException( "Customer", "validating addTo attribute on AssignKycProfilesToCustomerCommand" );

	}

	/**
	 * handles remove from KycProfiles validation for a Customer
	 *
	 * @param	command RemoveKycProfilesFromCustomerCommand
	 */
	public void validate( RemoveKycProfilesFromCustomerCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException("Customer", "validating RemoveKycProfilesFromCustomerCommand" );

		if( command.getCustomerId() == null )
			throw new ValidationException("Customer", "validating id on RemoveKycProfilesFromCustomerCommand" );

		if( command.getRemoveFrom() == null )
			throw new ValidationException("Customer", "validating remove from RemoveKycProfilesFromCustomerCommand" );

		if( command.getRemoveFrom().getKycProfileId() == null )
			throw new ValidationException("Customer", "validating id on remove from RemoveKycProfilesFromCustomerCommand" );
	}

	/**
	 * handles add to Consents validation for a Customer
	 *
	 * @param	command AssignConsentsToCustomerCommand
	 */
	public void validate( AssignConsentsToCustomerCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "Customer", "validating AssignConsentsToCustomerCommand" );

		if ( command.getCustomerId() == null )
		throw new ValidationException( "Customer", "validating identity on AssignConsentsToCustomerCommand" );

		if ( command.getAddTo() == null )
			throw new ValidationException( "Customer", "validating addTo attribute on AssignConsentsToCustomerCommand" );

	}

	/**
	 * handles remove from Consents validation for a Customer
	 *
	 * @param	command RemoveConsentsFromCustomerCommand
	 */
	public void validate( RemoveConsentsFromCustomerCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException("Customer", "validating RemoveConsentsFromCustomerCommand" );

		if( command.getCustomerId() == null )
			throw new ValidationException("Customer", "validating id on RemoveConsentsFromCustomerCommand" );

		if( command.getRemoveFrom() == null )
			throw new ValidationException("Customer", "validating remove from RemoveConsentsFromCustomerCommand" );

		if( command.getRemoveFrom().getConsentId() == null )
			throw new ValidationException("Customer", "validating id on remove from RemoveConsentsFromCustomerCommand" );
	}


}
