/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Spring Boot 3.5
 *
 * Domain Model:
 * Banking Industry Domain Model
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone National Bank Confidential
 *
 * 2026 Turnstone National Bank
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone National Bank - General Release
 */
		package com.harbormaster.validator;

import org.springframework.stereotype.Component;
import org.springframework.util.Assert;

import com.harbormaster.api.*;
import com.harbormaster.exception.*;

/**
 * <h2>FundsTransferValidation</h2>
 * <p>
 * The FundsTransfer Validation  handles state validation of a FundsTransfer include direct attributes and single/multiple associations.
 * </p>
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Spring Boot 3.5</td></tr>
 *          <tr><td>published</td><td>09/08/2026</td></tr>
 *          <tr><td>design pattern</td><td>ServiceLayer</td></tr>
 *          <tr><td>architecture style</td><td>Layered</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>Banking Industry Domain Model</td></tr>
 *          <tr><td>description</td><td>HCIDL model capturing core banking, payments, lending, cards, KYC, and FX capabilities.</td></tr>
 *          <tr><td>industry</td><td>Banking</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Commands Validated</h3>
 *      <ul>
 *      <li>CreateFundsTransferCommand</li>
 *      <li>UpdateFundsTransferCommand</li>
 *      <li>DeleteFundsTransferCommand</li>
 *set( false = false )
  *       <li>AssignSourceAccountToFundsTransferCommand</li>
 *       <li>UnAssignSourceAccountFromFundsTransferCommand</li>
  *       <li>AssignDestinationAccountToFundsTransferCommand</li>
 *       <li>UnAssignDestinationAccountFromFundsTransferCommand</li>
  *       <li>AssignExternalBeneficiaryToFundsTransferCommand</li>
 *       <li>UnAssignExternalBeneficiaryFromFundsTransferCommand</li>
  *       <li>AssignInitiatedByToFundsTransferCommand</li>
 *       <li>UnAssignInitiatedByFromFundsTransferCommand</li>
   *       <li>AssignTransactionsToFundsTransferCommand</li>
 *       <li>RemoveTransactionsFromFundsTransferCommand</li>
 *   </ul>
 *
  * <p>
 * @author Harbormaster Dev Team
 * </p>
 */
@Component
public class FundsTransferValidator {

	/**
	 * default constructor
	 */
	protected FundsTransferValidator() {
	}


	/**
	 * handles creation validation for a FundsTransfer
	 */
	public void validate( CreateFundsTransferCommand fundsTransfer )throws ValidationException {
		if ( fundsTransfer == null )
		throw new ValidationException( "FundsTransfer", "validating CreateFundsTransferCommand" );
		if ( fundsTransfer.getTransferReference() == null )
		throw new ValidationException( "FundsTransfer", "validating access on getTransferReference" );
		if ( fundsTransfer.getAmount() == null )
		throw new ValidationException( "FundsTransfer", "validating access on getAmount" );
		if ( fundsTransfer.getRequestedDate() == null )
		throw new ValidationException( "FundsTransfer", "validating access on getRequestedDate" );
		if ( fundsTransfer.getExecutionDate() == null )
		throw new ValidationException( "FundsTransfer", "validating access on getExecutionDate" );
		if ( fundsTransfer.getPurpose() == null )
		throw new ValidationException( "FundsTransfer", "validating access on getPurpose" );
		if ( fundsTransfer.getFeeAmount() == null )
		throw new ValidationException( "FundsTransfer", "validating access on getFeeAmount" );
	}

	/**
	 * handles update validation for a FundsTransfer
	 */
	public void validate( UpdateFundsTransferCommand fundsTransfer ) throws ValidationException {
		if ( fundsTransfer == null )
		throw new ValidationException( "FundsTransfer", "validating UpdateFundsTransferCommand" );
		if ( fundsTransfer.getTransferReference() == null )
		throw new ValidationException( "FundsTransfer", "validating method getTransferReference" );
		if ( fundsTransfer.getAmount() == null )
		throw new ValidationException( "FundsTransfer", "validating method getAmount" );
		if ( fundsTransfer.getRequestedDate() == null )
		throw new ValidationException( "FundsTransfer", "validating method getRequestedDate" );
		if ( fundsTransfer.getExecutionDate() == null )
		throw new ValidationException( "FundsTransfer", "validating method getExecutionDate" );
		if ( fundsTransfer.getPurpose() == null )
		throw new ValidationException( "FundsTransfer", "validating method getPurpose" );
		if ( fundsTransfer.getFeeAmount() == null )
		throw new ValidationException( "FundsTransfer", "validating method getFeeAmount" );
	}

/**
 * handles delete validation for a FundsTransfer
 */
	public void validate( DeleteFundsTransferCommand fundsTransfer ) throws ValidationException {
		if ( fundsTransfer == null )
			throw new ValidationException( "FundsTransfer", "validating DeleteFundsTransferCommand" );
	}

/**
 * handles fetchOne validation for a FundsTransfer
 */
	public void validate( FundsTransferFetchOneSummary summary ) throws ValidationException {
		if ( summary == null )
			throw new ValidationException( "FundsTransfer", "validating summary" );
	}

	/**
	 * handles assign SourceAccount validation for a FundsTransfer
	 *
	 * @param	command AssignSourceAccountToFundsTransferCommand
	 */
	public void validate( AssignSourceAccountToFundsTransferCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "FundsTransfer", "validating AssignSourceAccountToFundsTransferCommand" );

		if ( command.getFundsTransferId() == null )
		throw new ValidationException( "FundsTransfer", "validating identifier on AssignSourceAccountToFundsTransferCommand" );

		if ( command.getAssignment() == null )
			throw new ValidationException( "FundsTransfer", "validating assignment" );
	}

	/**
	 * handles unassign SourceAccount validation for a FundsTransfer
	 *
	 * @param	command UnAssignSourceAccountFromFundsTransferCommand
	 */
	public void validate( UnAssignSourceAccountFromFundsTransferCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "FundsTransfer", "validating UnAssignSourceAccountFromFundsTransferCommand" );

		if ( command.getFundsTransferId() == null )
		throw new ValidationException( "FundsTransfer", "validating identity on UnAssignSourceAccountFromFundsTransferCommand" );
	}
	/**
	 * handles assign DestinationAccount validation for a FundsTransfer
	 *
	 * @param	command AssignDestinationAccountToFundsTransferCommand
	 */
	public void validate( AssignDestinationAccountToFundsTransferCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "FundsTransfer", "validating AssignDestinationAccountToFundsTransferCommand" );

		if ( command.getFundsTransferId() == null )
		throw new ValidationException( "FundsTransfer", "validating identifier on AssignDestinationAccountToFundsTransferCommand" );

		if ( command.getAssignment() == null )
			throw new ValidationException( "FundsTransfer", "validating assignment" );
	}

	/**
	 * handles unassign DestinationAccount validation for a FundsTransfer
	 *
	 * @param	command UnAssignDestinationAccountFromFundsTransferCommand
	 */
	public void validate( UnAssignDestinationAccountFromFundsTransferCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "FundsTransfer", "validating UnAssignDestinationAccountFromFundsTransferCommand" );

		if ( command.getFundsTransferId() == null )
		throw new ValidationException( "FundsTransfer", "validating identity on UnAssignDestinationAccountFromFundsTransferCommand" );
	}
	/**
	 * handles assign ExternalBeneficiary validation for a FundsTransfer
	 *
	 * @param	command AssignExternalBeneficiaryToFundsTransferCommand
	 */
	public void validate( AssignExternalBeneficiaryToFundsTransferCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "FundsTransfer", "validating AssignExternalBeneficiaryToFundsTransferCommand" );

		if ( command.getFundsTransferId() == null )
		throw new ValidationException( "FundsTransfer", "validating identifier on AssignExternalBeneficiaryToFundsTransferCommand" );

		if ( command.getAssignment() == null )
			throw new ValidationException( "FundsTransfer", "validating assignment" );
	}

	/**
	 * handles unassign ExternalBeneficiary validation for a FundsTransfer
	 *
	 * @param	command UnAssignExternalBeneficiaryFromFundsTransferCommand
	 */
	public void validate( UnAssignExternalBeneficiaryFromFundsTransferCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "FundsTransfer", "validating UnAssignExternalBeneficiaryFromFundsTransferCommand" );

		if ( command.getFundsTransferId() == null )
		throw new ValidationException( "FundsTransfer", "validating identity on UnAssignExternalBeneficiaryFromFundsTransferCommand" );
	}
	/**
	 * handles assign InitiatedBy validation for a FundsTransfer
	 *
	 * @param	command AssignInitiatedByToFundsTransferCommand
	 */
	public void validate( AssignInitiatedByToFundsTransferCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "FundsTransfer", "validating AssignInitiatedByToFundsTransferCommand" );

		if ( command.getFundsTransferId() == null )
		throw new ValidationException( "FundsTransfer", "validating identifier on AssignInitiatedByToFundsTransferCommand" );

		if ( command.getAssignment() == null )
			throw new ValidationException( "FundsTransfer", "validating assignment" );
	}

	/**
	 * handles unassign InitiatedBy validation for a FundsTransfer
	 *
	 * @param	command UnAssignInitiatedByFromFundsTransferCommand
	 */
	public void validate( UnAssignInitiatedByFromFundsTransferCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "FundsTransfer", "validating UnAssignInitiatedByFromFundsTransferCommand" );

		if ( command.getFundsTransferId() == null )
		throw new ValidationException( "FundsTransfer", "validating identity on UnAssignInitiatedByFromFundsTransferCommand" );
	}

	/**
	 * handles add to Transactions validation for a FundsTransfer
	 *
	 * @param	command AssignTransactionsToFundsTransferCommand
	 */
	public void validate( AssignTransactionsToFundsTransferCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "FundsTransfer", "validating AssignTransactionsToFundsTransferCommand" );

		if ( command.getFundsTransferId() == null )
		throw new ValidationException( "FundsTransfer", "validating identity on AssignTransactionsToFundsTransferCommand" );

		if ( command.getAddTo() == null )
			throw new ValidationException( "FundsTransfer", "validating addTo attribute on AssignTransactionsToFundsTransferCommand" );

	}

	/**
	 * handles remove from Transactions validation for a FundsTransfer
	 *
	 * @param	command RemoveTransactionsFromFundsTransferCommand
	 */
	public void validate( RemoveTransactionsFromFundsTransferCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException("FundsTransfer", "validating RemoveTransactionsFromFundsTransferCommand" );

		if( command.getFundsTransferId() == null )
			throw new ValidationException("FundsTransfer", "validating id on RemoveTransactionsFromFundsTransferCommand" );

		if( command.getRemoveFrom() == null )
			throw new ValidationException("FundsTransfer", "validating remove from RemoveTransactionsFromFundsTransferCommand" );

		if( command.getRemoveFrom().getTransactionId() == null )
			throw new ValidationException("FundsTransfer", "validating id on remove from RemoveTransactionsFromFundsTransferCommand" );
	}


}
