/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Spring Boot 3.5
 *
 * Domain Model:
 * Banking Industry Domain Model
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone National Bank Confidential
 *
 * 2026 Turnstone National Bank
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone National Bank - General Release
 */
		package com.harbormaster.validator;

import org.springframework.stereotype.Component;
import org.springframework.util.Assert;

import com.harbormaster.api.*;
import com.harbormaster.exception.*;

/**
 * <h2>KycProfileValidation</h2>
 * <p>
 * The KycProfile Validation  handles state validation of a KycProfile include direct attributes and single/multiple associations.
 * </p>
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Spring Boot 3.5</td></tr>
 *          <tr><td>published</td><td>09/08/2026</td></tr>
 *          <tr><td>design pattern</td><td>ServiceLayer</td></tr>
 *          <tr><td>architecture style</td><td>Layered</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>Banking Industry Domain Model</td></tr>
 *          <tr><td>description</td><td>HCIDL model capturing core banking, payments, lending, cards, KYC, and FX capabilities.</td></tr>
 *          <tr><td>industry</td><td>Banking</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Commands Validated</h3>
 *      <ul>
 *      <li>CreateKycProfileCommand</li>
 *      <li>UpdateKycProfileCommand</li>
 *      <li>DeleteKycProfileCommand</li>
 *set( false = false )
  *       <li>AssignCustomerToKycProfileCommand</li>
 *       <li>UnAssignCustomerFromKycProfileCommand</li>
   *       <li>AssignIdentityDocumentsToKycProfileCommand</li>
 *       <li>RemoveIdentityDocumentsFromKycProfileCommand</li>
 *   </ul>
 *
  *       <li>AssignRiskAssessmentsToKycProfileCommand</li>
 *       <li>RemoveRiskAssessmentsFromKycProfileCommand</li>
 *   </ul>
 *
  *       <li>AssignScreeningsToKycProfileCommand</li>
 *       <li>RemoveScreeningsFromKycProfileCommand</li>
 *   </ul>
 *
  * <p>
 * @author Harbormaster Dev Team
 * </p>
 */
@Component
public class KycProfileValidator {

	/**
	 * default constructor
	 */
	protected KycProfileValidator() {
	}


	/**
	 * handles creation validation for a KycProfile
	 */
	public void validate( CreateKycProfileCommand kycProfile )throws ValidationException {
		if ( kycProfile == null )
		throw new ValidationException( "KycProfile", "validating CreateKycProfileCommand" );
		if ( kycProfile.getProfileId() == null )
		throw new ValidationException( "KycProfile", "validating access on getProfileId" );
		if ( kycProfile.getLastReviewedOn() == null )
		throw new ValidationException( "KycProfile", "validating access on getLastReviewedOn" );
	}

	/**
	 * handles update validation for a KycProfile
	 */
	public void validate( UpdateKycProfileCommand kycProfile ) throws ValidationException {
		if ( kycProfile == null )
		throw new ValidationException( "KycProfile", "validating UpdateKycProfileCommand" );
		if ( kycProfile.getProfileId() == null )
		throw new ValidationException( "KycProfile", "validating method getProfileId" );
		if ( kycProfile.getLastReviewedOn() == null )
		throw new ValidationException( "KycProfile", "validating method getLastReviewedOn" );
	}

/**
 * handles delete validation for a KycProfile
 */
	public void validate( DeleteKycProfileCommand kycProfile ) throws ValidationException {
		if ( kycProfile == null )
			throw new ValidationException( "KycProfile", "validating DeleteKycProfileCommand" );
	}

/**
 * handles fetchOne validation for a KycProfile
 */
	public void validate( KycProfileFetchOneSummary summary ) throws ValidationException {
		if ( summary == null )
			throw new ValidationException( "KycProfile", "validating summary" );
	}

	/**
	 * handles assign Customer validation for a KycProfile
	 *
	 * @param	command AssignCustomerToKycProfileCommand
	 */
	public void validate( AssignCustomerToKycProfileCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "KycProfile", "validating AssignCustomerToKycProfileCommand" );

		if ( command.getKycProfileId() == null )
		throw new ValidationException( "KycProfile", "validating identifier on AssignCustomerToKycProfileCommand" );

		if ( command.getAssignment() == null )
			throw new ValidationException( "KycProfile", "validating assignment" );
	}

	/**
	 * handles unassign Customer validation for a KycProfile
	 *
	 * @param	command UnAssignCustomerFromKycProfileCommand
	 */
	public void validate( UnAssignCustomerFromKycProfileCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "KycProfile", "validating UnAssignCustomerFromKycProfileCommand" );

		if ( command.getKycProfileId() == null )
		throw new ValidationException( "KycProfile", "validating identity on UnAssignCustomerFromKycProfileCommand" );
	}

	/**
	 * handles add to IdentityDocuments validation for a KycProfile
	 *
	 * @param	command AssignIdentityDocumentsToKycProfileCommand
	 */
	public void validate( AssignIdentityDocumentsToKycProfileCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "KycProfile", "validating AssignIdentityDocumentsToKycProfileCommand" );

		if ( command.getKycProfileId() == null )
		throw new ValidationException( "KycProfile", "validating identity on AssignIdentityDocumentsToKycProfileCommand" );

		if ( command.getAddTo() == null )
			throw new ValidationException( "KycProfile", "validating addTo attribute on AssignIdentityDocumentsToKycProfileCommand" );

	}

	/**
	 * handles remove from IdentityDocuments validation for a KycProfile
	 *
	 * @param	command RemoveIdentityDocumentsFromKycProfileCommand
	 */
	public void validate( RemoveIdentityDocumentsFromKycProfileCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException("KycProfile", "validating RemoveIdentityDocumentsFromKycProfileCommand" );

		if( command.getKycProfileId() == null )
			throw new ValidationException("KycProfile", "validating id on RemoveIdentityDocumentsFromKycProfileCommand" );

		if( command.getRemoveFrom() == null )
			throw new ValidationException("KycProfile", "validating remove from RemoveIdentityDocumentsFromKycProfileCommand" );

		if( command.getRemoveFrom().getIdentityDocumentId() == null )
			throw new ValidationException("KycProfile", "validating id on remove from RemoveIdentityDocumentsFromKycProfileCommand" );
	}

	/**
	 * handles add to RiskAssessments validation for a KycProfile
	 *
	 * @param	command AssignRiskAssessmentsToKycProfileCommand
	 */
	public void validate( AssignRiskAssessmentsToKycProfileCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "KycProfile", "validating AssignRiskAssessmentsToKycProfileCommand" );

		if ( command.getKycProfileId() == null )
		throw new ValidationException( "KycProfile", "validating identity on AssignRiskAssessmentsToKycProfileCommand" );

		if ( command.getAddTo() == null )
			throw new ValidationException( "KycProfile", "validating addTo attribute on AssignRiskAssessmentsToKycProfileCommand" );

	}

	/**
	 * handles remove from RiskAssessments validation for a KycProfile
	 *
	 * @param	command RemoveRiskAssessmentsFromKycProfileCommand
	 */
	public void validate( RemoveRiskAssessmentsFromKycProfileCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException("KycProfile", "validating RemoveRiskAssessmentsFromKycProfileCommand" );

		if( command.getKycProfileId() == null )
			throw new ValidationException("KycProfile", "validating id on RemoveRiskAssessmentsFromKycProfileCommand" );

		if( command.getRemoveFrom() == null )
			throw new ValidationException("KycProfile", "validating remove from RemoveRiskAssessmentsFromKycProfileCommand" );

		if( command.getRemoveFrom().getRiskAssessmentId() == null )
			throw new ValidationException("KycProfile", "validating id on remove from RemoveRiskAssessmentsFromKycProfileCommand" );
	}

	/**
	 * handles add to Screenings validation for a KycProfile
	 *
	 * @param	command AssignScreeningsToKycProfileCommand
	 */
	public void validate( AssignScreeningsToKycProfileCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "KycProfile", "validating AssignScreeningsToKycProfileCommand" );

		if ( command.getKycProfileId() == null )
		throw new ValidationException( "KycProfile", "validating identity on AssignScreeningsToKycProfileCommand" );

		if ( command.getAddTo() == null )
			throw new ValidationException( "KycProfile", "validating addTo attribute on AssignScreeningsToKycProfileCommand" );

	}

	/**
	 * handles remove from Screenings validation for a KycProfile
	 *
	 * @param	command RemoveScreeningsFromKycProfileCommand
	 */
	public void validate( RemoveScreeningsFromKycProfileCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException("KycProfile", "validating RemoveScreeningsFromKycProfileCommand" );

		if( command.getKycProfileId() == null )
			throw new ValidationException("KycProfile", "validating id on RemoveScreeningsFromKycProfileCommand" );

		if( command.getRemoveFrom() == null )
			throw new ValidationException("KycProfile", "validating remove from RemoveScreeningsFromKycProfileCommand" );

		if( command.getRemoveFrom().getScreeningResultId() == null )
			throw new ValidationException("KycProfile", "validating id on remove from RemoveScreeningsFromKycProfileCommand" );
	}


}
