/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Spring Boot 3.5
 *
 * Domain Model:
 * Banking Industry Domain Model
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone National Bank Confidential
 *
 * 2026 Turnstone National Bank
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone National Bank - General Release
 */
		package com.harbormaster.validator;

import org.springframework.stereotype.Component;
import org.springframework.util.Assert;

import com.harbormaster.api.*;
import com.harbormaster.exception.*;

/**
 * <h2>PaymentCardValidation</h2>
 * <p>
 * The PaymentCard Validation  handles state validation of a PaymentCard include direct attributes and single/multiple associations.
 * </p>
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Spring Boot 3.5</td></tr>
 *          <tr><td>published</td><td>09/08/2026</td></tr>
 *          <tr><td>design pattern</td><td>ServiceLayer</td></tr>
 *          <tr><td>architecture style</td><td>Layered</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>Banking Industry Domain Model</td></tr>
 *          <tr><td>description</td><td>HCIDL model capturing core banking, payments, lending, cards, KYC, and FX capabilities.</td></tr>
 *          <tr><td>industry</td><td>Banking</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Commands Validated</h3>
 *      <ul>
 *      <li>CreatePaymentCardCommand</li>
 *      <li>UpdatePaymentCardCommand</li>
 *      <li>DeletePaymentCardCommand</li>
 *set( false = false )
  *       <li>AssignBankToPaymentCardCommand</li>
 *       <li>UnAssignBankFromPaymentCardCommand</li>
  *       <li>AssignAccountToPaymentCardCommand</li>
 *       <li>UnAssignAccountFromPaymentCardCommand</li>
  *       <li>AssignCustomerToPaymentCardCommand</li>
 *       <li>UnAssignCustomerFromPaymentCardCommand</li>
   *       <li>AssignTransactionsToPaymentCardCommand</li>
 *       <li>RemoveTransactionsFromPaymentCardCommand</li>
 *   </ul>
 *
  * <p>
 * @author Harbormaster Dev Team
 * </p>
 */
@Component
public class PaymentCardValidator {

	/**
	 * default constructor
	 */
	protected PaymentCardValidator() {
	}


	/**
	 * handles creation validation for a PaymentCard
	 */
	public void validate( CreatePaymentCardCommand paymentCard )throws ValidationException {
		if ( paymentCard == null )
		throw new ValidationException( "PaymentCard", "validating CreatePaymentCardCommand" );
		if ( paymentCard.getCardNumber() == null )
		throw new ValidationException( "PaymentCard", "validating access on getCardNumber" );
		if ( paymentCard.getEmbossedName() == null )
		throw new ValidationException( "PaymentCard", "validating access on getEmbossedName" );
		if ( paymentCard.getExpiryMonth() == null )
		throw new ValidationException( "PaymentCard", "validating access on getExpiryMonth" );
		if ( paymentCard.getExpiryYear() == null )
		throw new ValidationException( "PaymentCard", "validating access on getExpiryYear" );
	}

	/**
	 * handles update validation for a PaymentCard
	 */
	public void validate( UpdatePaymentCardCommand paymentCard ) throws ValidationException {
		if ( paymentCard == null )
		throw new ValidationException( "PaymentCard", "validating UpdatePaymentCardCommand" );
		if ( paymentCard.getCardNumber() == null )
		throw new ValidationException( "PaymentCard", "validating method getCardNumber" );
		if ( paymentCard.getEmbossedName() == null )
		throw new ValidationException( "PaymentCard", "validating method getEmbossedName" );
		if ( paymentCard.getExpiryMonth() == null )
		throw new ValidationException( "PaymentCard", "validating method getExpiryMonth" );
		if ( paymentCard.getExpiryYear() == null )
		throw new ValidationException( "PaymentCard", "validating method getExpiryYear" );
	}

/**
 * handles delete validation for a PaymentCard
 */
	public void validate( DeletePaymentCardCommand paymentCard ) throws ValidationException {
		if ( paymentCard == null )
			throw new ValidationException( "PaymentCard", "validating DeletePaymentCardCommand" );
	}

/**
 * handles fetchOne validation for a PaymentCard
 */
	public void validate( PaymentCardFetchOneSummary summary ) throws ValidationException {
		if ( summary == null )
			throw new ValidationException( "PaymentCard", "validating summary" );
	}

	/**
	 * handles assign Bank validation for a PaymentCard
	 *
	 * @param	command AssignBankToPaymentCardCommand
	 */
	public void validate( AssignBankToPaymentCardCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "PaymentCard", "validating AssignBankToPaymentCardCommand" );

		if ( command.getPaymentCardId() == null )
		throw new ValidationException( "PaymentCard", "validating identifier on AssignBankToPaymentCardCommand" );

		if ( command.getAssignment() == null )
			throw new ValidationException( "PaymentCard", "validating assignment" );
	}

	/**
	 * handles unassign Bank validation for a PaymentCard
	 *
	 * @param	command UnAssignBankFromPaymentCardCommand
	 */
	public void validate( UnAssignBankFromPaymentCardCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "PaymentCard", "validating UnAssignBankFromPaymentCardCommand" );

		if ( command.getPaymentCardId() == null )
		throw new ValidationException( "PaymentCard", "validating identity on UnAssignBankFromPaymentCardCommand" );
	}
	/**
	 * handles assign Account validation for a PaymentCard
	 *
	 * @param	command AssignAccountToPaymentCardCommand
	 */
	public void validate( AssignAccountToPaymentCardCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "PaymentCard", "validating AssignAccountToPaymentCardCommand" );

		if ( command.getPaymentCardId() == null )
		throw new ValidationException( "PaymentCard", "validating identifier on AssignAccountToPaymentCardCommand" );

		if ( command.getAssignment() == null )
			throw new ValidationException( "PaymentCard", "validating assignment" );
	}

	/**
	 * handles unassign Account validation for a PaymentCard
	 *
	 * @param	command UnAssignAccountFromPaymentCardCommand
	 */
	public void validate( UnAssignAccountFromPaymentCardCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "PaymentCard", "validating UnAssignAccountFromPaymentCardCommand" );

		if ( command.getPaymentCardId() == null )
		throw new ValidationException( "PaymentCard", "validating identity on UnAssignAccountFromPaymentCardCommand" );
	}
	/**
	 * handles assign Customer validation for a PaymentCard
	 *
	 * @param	command AssignCustomerToPaymentCardCommand
	 */
	public void validate( AssignCustomerToPaymentCardCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "PaymentCard", "validating AssignCustomerToPaymentCardCommand" );

		if ( command.getPaymentCardId() == null )
		throw new ValidationException( "PaymentCard", "validating identifier on AssignCustomerToPaymentCardCommand" );

		if ( command.getAssignment() == null )
			throw new ValidationException( "PaymentCard", "validating assignment" );
	}

	/**
	 * handles unassign Customer validation for a PaymentCard
	 *
	 * @param	command UnAssignCustomerFromPaymentCardCommand
	 */
	public void validate( UnAssignCustomerFromPaymentCardCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "PaymentCard", "validating UnAssignCustomerFromPaymentCardCommand" );

		if ( command.getPaymentCardId() == null )
		throw new ValidationException( "PaymentCard", "validating identity on UnAssignCustomerFromPaymentCardCommand" );
	}

	/**
	 * handles add to Transactions validation for a PaymentCard
	 *
	 * @param	command AssignTransactionsToPaymentCardCommand
	 */
	public void validate( AssignTransactionsToPaymentCardCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "PaymentCard", "validating AssignTransactionsToPaymentCardCommand" );

		if ( command.getPaymentCardId() == null )
		throw new ValidationException( "PaymentCard", "validating identity on AssignTransactionsToPaymentCardCommand" );

		if ( command.getAddTo() == null )
			throw new ValidationException( "PaymentCard", "validating addTo attribute on AssignTransactionsToPaymentCardCommand" );

	}

	/**
	 * handles remove from Transactions validation for a PaymentCard
	 *
	 * @param	command RemoveTransactionsFromPaymentCardCommand
	 */
	public void validate( RemoveTransactionsFromPaymentCardCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException("PaymentCard", "validating RemoveTransactionsFromPaymentCardCommand" );

		if( command.getPaymentCardId() == null )
			throw new ValidationException("PaymentCard", "validating id on RemoveTransactionsFromPaymentCardCommand" );

		if( command.getRemoveFrom() == null )
			throw new ValidationException("PaymentCard", "validating remove from RemoveTransactionsFromPaymentCardCommand" );

		if( command.getRemoveFrom().getTransactionId() == null )
			throw new ValidationException("PaymentCard", "validating id on remove from RemoveTransactionsFromPaymentCardCommand" );
	}


}
