/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Spring Boot 3.5
 *
 * Domain Model:
 * Banking Industry Domain Model
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone National Bank Confidential
 *
 * 2026 Turnstone National Bank
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone National Bank - General Release
 */
		package com.harbormaster.validator;

import org.springframework.stereotype.Component;
import org.springframework.util.Assert;

import com.harbormaster.api.*;
import com.harbormaster.exception.*;

/**
 * <h2>ThirdPartyProviderValidation</h2>
 * <p>
 * The ThirdPartyProvider Validation  handles state validation of a ThirdPartyProvider include direct attributes and single/multiple associations.
 * </p>
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Spring Boot 3.5</td></tr>
 *          <tr><td>published</td><td>09/08/2026</td></tr>
 *          <tr><td>design pattern</td><td>ServiceLayer</td></tr>
 *          <tr><td>architecture style</td><td>Layered</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>Banking Industry Domain Model</td></tr>
 *          <tr><td>description</td><td>HCIDL model capturing core banking, payments, lending, cards, KYC, and FX capabilities.</td></tr>
 *          <tr><td>industry</td><td>Banking</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Commands Validated</h3>
 *      <ul>
 *      <li>CreateThirdPartyProviderCommand</li>
 *      <li>UpdateThirdPartyProviderCommand</li>
 *      <li>DeleteThirdPartyProviderCommand</li>
 *set( false = false )
  *       <li>AssignBankToThirdPartyProviderCommand</li>
 *       <li>UnAssignBankFromThirdPartyProviderCommand</li>
   *       <li>AssignConsentsToThirdPartyProviderCommand</li>
 *       <li>RemoveConsentsFromThirdPartyProviderCommand</li>
 *   </ul>
 *
  * <p>
 * @author Harbormaster Dev Team
 * </p>
 */
@Component
public class ThirdPartyProviderValidator {

	/**
	 * default constructor
	 */
	protected ThirdPartyProviderValidator() {
	}


	/**
	 * handles creation validation for a ThirdPartyProvider
	 */
	public void validate( CreateThirdPartyProviderCommand thirdPartyProvider )throws ValidationException {
		if ( thirdPartyProvider == null )
		throw new ValidationException( "ThirdPartyProvider", "validating CreateThirdPartyProviderCommand" );
		if ( thirdPartyProvider.getName() == null )
		throw new ValidationException( "ThirdPartyProvider", "validating access on getName" );
		if ( thirdPartyProvider.getRegistrationId() == null )
		throw new ValidationException( "ThirdPartyProvider", "validating access on getRegistrationId" );
		if ( thirdPartyProvider.getWebsite() == null )
		throw new ValidationException( "ThirdPartyProvider", "validating access on getWebsite" );
	}

	/**
	 * handles update validation for a ThirdPartyProvider
	 */
	public void validate( UpdateThirdPartyProviderCommand thirdPartyProvider ) throws ValidationException {
		if ( thirdPartyProvider == null )
		throw new ValidationException( "ThirdPartyProvider", "validating UpdateThirdPartyProviderCommand" );
		if ( thirdPartyProvider.getName() == null )
		throw new ValidationException( "ThirdPartyProvider", "validating method getName" );
		if ( thirdPartyProvider.getRegistrationId() == null )
		throw new ValidationException( "ThirdPartyProvider", "validating method getRegistrationId" );
		if ( thirdPartyProvider.getWebsite() == null )
		throw new ValidationException( "ThirdPartyProvider", "validating method getWebsite" );
	}

/**
 * handles delete validation for a ThirdPartyProvider
 */
	public void validate( DeleteThirdPartyProviderCommand thirdPartyProvider ) throws ValidationException {
		if ( thirdPartyProvider == null )
			throw new ValidationException( "ThirdPartyProvider", "validating DeleteThirdPartyProviderCommand" );
	}

/**
 * handles fetchOne validation for a ThirdPartyProvider
 */
	public void validate( ThirdPartyProviderFetchOneSummary summary ) throws ValidationException {
		if ( summary == null )
			throw new ValidationException( "ThirdPartyProvider", "validating summary" );
	}

	/**
	 * handles assign Bank validation for a ThirdPartyProvider
	 *
	 * @param	command AssignBankToThirdPartyProviderCommand
	 */
	public void validate( AssignBankToThirdPartyProviderCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "ThirdPartyProvider", "validating AssignBankToThirdPartyProviderCommand" );

		if ( command.getThirdPartyProviderId() == null )
		throw new ValidationException( "ThirdPartyProvider", "validating identifier on AssignBankToThirdPartyProviderCommand" );

		if ( command.getAssignment() == null )
			throw new ValidationException( "ThirdPartyProvider", "validating assignment" );
	}

	/**
	 * handles unassign Bank validation for a ThirdPartyProvider
	 *
	 * @param	command UnAssignBankFromThirdPartyProviderCommand
	 */
	public void validate( UnAssignBankFromThirdPartyProviderCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "ThirdPartyProvider", "validating UnAssignBankFromThirdPartyProviderCommand" );

		if ( command.getThirdPartyProviderId() == null )
		throw new ValidationException( "ThirdPartyProvider", "validating identity on UnAssignBankFromThirdPartyProviderCommand" );
	}

	/**
	 * handles add to Consents validation for a ThirdPartyProvider
	 *
	 * @param	command AssignConsentsToThirdPartyProviderCommand
	 */
	public void validate( AssignConsentsToThirdPartyProviderCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "ThirdPartyProvider", "validating AssignConsentsToThirdPartyProviderCommand" );

		if ( command.getThirdPartyProviderId() == null )
		throw new ValidationException( "ThirdPartyProvider", "validating identity on AssignConsentsToThirdPartyProviderCommand" );

		if ( command.getAddTo() == null )
			throw new ValidationException( "ThirdPartyProvider", "validating addTo attribute on AssignConsentsToThirdPartyProviderCommand" );

	}

	/**
	 * handles remove from Consents validation for a ThirdPartyProvider
	 *
	 * @param	command RemoveConsentsFromThirdPartyProviderCommand
	 */
	public void validate( RemoveConsentsFromThirdPartyProviderCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException("ThirdPartyProvider", "validating RemoveConsentsFromThirdPartyProviderCommand" );

		if( command.getThirdPartyProviderId() == null )
			throw new ValidationException("ThirdPartyProvider", "validating id on RemoveConsentsFromThirdPartyProviderCommand" );

		if( command.getRemoveFrom() == null )
			throw new ValidationException("ThirdPartyProvider", "validating remove from RemoveConsentsFromThirdPartyProviderCommand" );

		if( command.getRemoveFrom().getConsentId() == null )
			throw new ValidationException("ThirdPartyProvider", "validating id on remove from RemoveConsentsFromThirdPartyProviderCommand" );
	}


}
