/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Spring Boot 3.5
 *
 * Domain Model:
 * Banking Industry Domain Model
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone National Bank Confidential
 *
 * 2026 Turnstone National Bank
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone National Bank - General Release
 */
package com.harbormaster.controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;

import java.util.*;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.harbormaster.api.*;
import com.harbormaster.service.*;
import com.harbormaster.entity.*;
import com.harbormaster.exception.*;

/**
 * AccountStatementRestController as REST API
 *
 * <p>Exposes REST endpoints for the AccountStatement entity.</p>
 *
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Spring Boot 3.5</td></tr>
 *          <tr><td>published</td><td>09/08/2026</td></tr>
 *          <tr><td>design pattern</td><td>ServiceLayer</td></tr>
 *          <tr><td>architecture style</td><td>Layered</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>Banking Industry Domain Model</td></tr>
 *          <tr><td>description</td><td>HCIDL model capturing core banking, payments, lending, cards, KYC, and FX capabilities.</td></tr>
 *          <tr><td>industry</td><td>Banking</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Services Used</h3>
 *
 *  	AccountStatementService
 *
 * <h3>Produces</h3>
 *
 *      <p>application/json</p>
 *
 * <h3>Commands Accepted</h3>
 *      <ul>
 *      <li>CreateAccountStatementCommand</li>
 *      <li></li>UpdateAccountStatementCommand</li>
 *      <liDeleteAccountStatementCommand</li>
 *      </ul>
 *
 * <p>@author Harbormaster Dev Team</p>
 *
 */
@CrossOrigin
@RestController
@RequestMapping("/AccountStatement")
public class AccountStatementRestController extends BaseSpringRestController {

	public AccountStatementRestController( AccountStatementService service ) {
		this.service = service;
	}
    /**
     * Handles create a AccountStatement.  if not key provided, calls create, otherwise calls save
     * @param		AccountStatement	accountStatement
     * @return		AccountStatement 
     */
	@PostMapping("/create")
    public AccountStatement create( @RequestBody(required=true) CreateAccountStatementCommand command ) {
    	AccountStatement entity = null;

		entity = service.createAccountStatement( command );
		LOGGER.info( "Successfully created AccountStatement with Id " + entity.getAccountStatementId()  );

		return entity;
    }

    /**
     * Handles updating a AccountStatement.  if no key provided, calls create, otherwise calls save
     * @param		AccountStatement accountStatement
     * @return		AccountStatement
     */
	@PutMapping("/update")
    public AccountStatement update( @RequestBody(required=true) UpdateAccountStatementCommand command ) {
		AccountStatement entity = null;

		entity = service.updateAccountStatement(command);
		LOGGER.info( "Successfully updated AccountStatement with Id " + command.getAccountStatementId()  );

		return entity;
	}
 
    /**
     * Handles deleting a AccountStatement entity
     * @param		command ${class.getDeleteCommandAlias()}
     */
    @DeleteMapping("/delete")    
    public void delete( @RequestBody(required=true) DeleteAccountStatementCommand command ) {                
		service.delete( command );
		LOGGER.info( "Successfully deleted AccountStatement with Id " + command.getAccountStatementId()  );
	}
	
    /**
     * Handles loading a AccountStatement using a UUID
     * @param		UUID uuid 
     * @return		AccountStatement
     */    
    @GetMapping("/load")
    public AccountStatement load( @RequestParam(required=true) UUID uuid ) {
    	AccountStatement entity = service.getAccountStatement( new AccountStatementFetchOneSummary( uuid ) );

		LOGGER.info( "Successfully loaded AccountStatement with Id " + uuid   );

        return entity;
    }

    /**
     * Handles loading all AccountStatement business objects
     * @return		Set<AccountStatement>
     */
    @GetMapping("/")
    public List<AccountStatement> loadAll() {                
    	List<AccountStatement> accountStatementList = null;

		accountStatementList = service.getAllAccountStatement();
		LOGGER.info( "successfully loaded all AccountStatements" );

        return accountStatementList;
                            
    }

    /**
     * save Account on AccountStatement
     * @param		command AssignAccountToAccountStatementCommand
     */     
	@PutMapping("/assignAccount")
	public void assignAccount( @RequestBody AssignAccountToAccountStatementCommand command ) {
		service.assignAccount( command );
		LOGGER.info( "Successfully assigned Account with Id " + command.getAccountStatementId()  );
	}

    /**
     * unassign Account on AccountStatement
     * @param		 command UnAssignAccountFromAccountStatementCommand
     */     
	@PutMapping("/unAssignAccount")
	public void unAssignAccount( @RequestBody(required=true)  UnAssignAccountFromAccountStatementCommand command ) {
		service.unAssignAccount( command );
		LOGGER.info( "Successfully unassigned Account with Id " + command.getAccountStatementId()  );
	}
	




//************************************************************************    
// Attributes
//************************************************************************
    protected AccountStatement accountStatement = null;
	protected AccountStatementService service = null;
    private static final Logger LOGGER = LoggerFactory.getLogger(AccountStatementRestController.class.getName());
    
}
