/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Spring Boot 3.5
 *
 * Domain Model:
 * Banking Industry Domain Model
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone National Bank Confidential
 *
 * 2026 Turnstone National Bank
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone National Bank - General Release
 */
package com.harbormaster.controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;

import java.util.*;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.harbormaster.api.*;
import com.harbormaster.service.*;
import com.harbormaster.entity.*;
import com.harbormaster.exception.*;

/**
 * BranchRestController as REST API
 *
 * <p>Exposes REST endpoints for the Branch entity.</p>
 *
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Spring Boot 3.5</td></tr>
 *          <tr><td>published</td><td>09/08/2026</td></tr>
 *          <tr><td>design pattern</td><td>ServiceLayer</td></tr>
 *          <tr><td>architecture style</td><td>Layered</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>Banking Industry Domain Model</td></tr>
 *          <tr><td>description</td><td>HCIDL model capturing core banking, payments, lending, cards, KYC, and FX capabilities.</td></tr>
 *          <tr><td>industry</td><td>Banking</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Services Used</h3>
 *
 *  	BranchService
 *
 * <h3>Produces</h3>
 *
 *      <p>application/json</p>
 *
 * <h3>Commands Accepted</h3>
 *      <ul>
 *      <li>CreateBranchCommand</li>
 *      <li></li>UpdateBranchCommand</li>
 *      <liDeleteBranchCommand</li>
 *      </ul>
 *
 * <p>@author Harbormaster Dev Team</p>
 *
 */
@CrossOrigin
@RestController
@RequestMapping("/Branch")
public class BranchRestController extends BaseSpringRestController {

	public BranchRestController( BranchService service ) {
		this.service = service;
	}
    /**
     * Handles create a Branch.  if not key provided, calls create, otherwise calls save
     * @param		Branch	branch
     * @return		Branch 
     */
	@PostMapping("/create")
    public Branch create( @RequestBody(required=true) CreateBranchCommand command ) {
    	Branch entity = null;

		entity = service.createBranch( command );
		LOGGER.info( "Successfully created Branch with Id " + entity.getBranchId()  );

		return entity;
    }

    /**
     * Handles updating a Branch.  if no key provided, calls create, otherwise calls save
     * @param		Branch branch
     * @return		Branch
     */
	@PutMapping("/update")
    public Branch update( @RequestBody(required=true) UpdateBranchCommand command ) {
		Branch entity = null;

		entity = service.updateBranch(command);
		LOGGER.info( "Successfully updated Branch with Id " + command.getBranchId()  );

		return entity;
	}
 
    /**
     * Handles deleting a Branch entity
     * @param		command ${class.getDeleteCommandAlias()}
     */
    @DeleteMapping("/delete")    
    public void delete( @RequestBody(required=true) DeleteBranchCommand command ) {                
		service.delete( command );
		LOGGER.info( "Successfully deleted Branch with Id " + command.getBranchId()  );
	}
	
    /**
     * Handles loading a Branch using a UUID
     * @param		UUID uuid 
     * @return		Branch
     */    
    @GetMapping("/load")
    public Branch load( @RequestParam(required=true) UUID uuid ) {
    	Branch entity = service.getBranch( new BranchFetchOneSummary( uuid ) );

		LOGGER.info( "Successfully loaded Branch with Id " + uuid   );

        return entity;
    }

    /**
     * Handles loading all Branch business objects
     * @return		Set<Branch>
     */
    @GetMapping("/")
    public List<Branch> loadAll() {                
    	List<Branch> branchList = null;

		branchList = service.getAllBranch();
		LOGGER.info( "successfully loaded all Branchs" );

        return branchList;
                            
    }

    /**
     * save Bank on Branch
     * @param		command AssignBankToBranchCommand
     */     
	@PutMapping("/assignBank")
	public void assignBank( @RequestBody AssignBankToBranchCommand command ) {
		service.assignBank( command );
		LOGGER.info( "Successfully assigned Bank with Id " + command.getBranchId()  );
	}

    /**
     * unassign Bank on Branch
     * @param		 command UnAssignBankFromBranchCommand
     */     
	@PutMapping("/unAssignBank")
	public void unAssignBank( @RequestBody(required=true)  UnAssignBankFromBranchCommand command ) {
		service.unAssignBank( command );
		LOGGER.info( "Successfully unassigned Bank with Id " + command.getBranchId()  );
	}
	

    /**
     * save Accounts on Branch
     * @param		command AssignAccountsToBranchCommand
     */     
	@PutMapping("/addToAccounts")
	public void addToAccounts( @RequestBody(required=true) AssignAccountsToBranchCommand command ) {
		service.addToAccounts( command );
		LOGGER.info( "Successfully added Accounts with Id " + command.getBranchId()  );
	}

    /**
     * remove Accounts on Branch
     * @param		command RemoveAccountsFromBranchCommand
     */     	
	@PutMapping("/removeFromAccounts")
	public void removeFromAccounts( 	@RequestBody(required=true) RemoveAccountsFromBranchCommand command )
	{		
		service.removeFromAccounts( command );
		LOGGER.info( "Successfully removed Accounts with Id " + command.getBranchId()  );
	}

    /**
     * save LoanAccounts on Branch
     * @param		command AssignLoanAccountsToBranchCommand
     */     
	@PutMapping("/addToLoanAccounts")
	public void addToLoanAccounts( @RequestBody(required=true) AssignLoanAccountsToBranchCommand command ) {
		service.addToLoanAccounts( command );
		LOGGER.info( "Successfully added LoanAccounts with Id " + command.getBranchId()  );
	}

    /**
     * remove LoanAccounts on Branch
     * @param		command RemoveLoanAccountsFromBranchCommand
     */     	
	@PutMapping("/removeFromLoanAccounts")
	public void removeFromLoanAccounts( 	@RequestBody(required=true) RemoveLoanAccountsFromBranchCommand command )
	{		
		service.removeFromLoanAccounts( command );
		LOGGER.info( "Successfully removed LoanAccounts with Id " + command.getBranchId()  );
	}

    /**
     * save Atms on Branch
     * @param		command AssignAtmsToBranchCommand
     */     
	@PutMapping("/addToAtms")
	public void addToAtms( @RequestBody(required=true) AssignAtmsToBranchCommand command ) {
		service.addToAtms( command );
		LOGGER.info( "Successfully added Atms with Id " + command.getBranchId()  );
	}

    /**
     * remove Atms on Branch
     * @param		command RemoveAtmsFromBranchCommand
     */     	
	@PutMapping("/removeFromAtms")
	public void removeFromAtms( 	@RequestBody(required=true) RemoveAtmsFromBranchCommand command )
	{		
		service.removeFromAtms( command );
		LOGGER.info( "Successfully removed Atms with Id " + command.getBranchId()  );
	}




//************************************************************************    
// Attributes
//************************************************************************
    protected Branch branch = null;
	protected BranchService service = null;
    private static final Logger LOGGER = LoggerFactory.getLogger(BranchRestController.class.getName());
    
}
