/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Spring Boot 3.5
 *
 * Domain Model:
 * Banking Industry Domain Model
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone National Bank Confidential
 *
 * 2026 Turnstone National Bank
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone National Bank - General Release
 */
package com.harbormaster.controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;

import java.util.*;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.harbormaster.api.*;
import com.harbormaster.service.*;
import com.harbormaster.entity.*;
import com.harbormaster.exception.*;

/**
 * DisputeRestController as REST API
 *
 * <p>Exposes REST endpoints for the Dispute entity.</p>
 *
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Spring Boot 3.5</td></tr>
 *          <tr><td>published</td><td>09/08/2026</td></tr>
 *          <tr><td>design pattern</td><td>ServiceLayer</td></tr>
 *          <tr><td>architecture style</td><td>Layered</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>Banking Industry Domain Model</td></tr>
 *          <tr><td>description</td><td>HCIDL model capturing core banking, payments, lending, cards, KYC, and FX capabilities.</td></tr>
 *          <tr><td>industry</td><td>Banking</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Services Used</h3>
 *
 *  	DisputeService
 *
 * <h3>Produces</h3>
 *
 *      <p>application/json</p>
 *
 * <h3>Commands Accepted</h3>
 *      <ul>
 *      <li>CreateDisputeCommand</li>
 *      <li></li>UpdateDisputeCommand</li>
 *      <liDeleteDisputeCommand</li>
 *      </ul>
 *
 * <p>@author Harbormaster Dev Team</p>
 *
 */
@CrossOrigin
@RestController
@RequestMapping("/Dispute")
public class DisputeRestController extends BaseSpringRestController {

	public DisputeRestController( DisputeService service ) {
		this.service = service;
	}
    /**
     * Handles create a Dispute.  if not key provided, calls create, otherwise calls save
     * @param		Dispute	dispute
     * @return		Dispute 
     */
	@PostMapping("/create")
    public Dispute create( @RequestBody(required=true) CreateDisputeCommand command ) {
    	Dispute entity = null;

		entity = service.createDispute( command );
		LOGGER.info( "Successfully created Dispute with Id " + entity.getDisputeId()  );

		return entity;
    }

    /**
     * Handles updating a Dispute.  if no key provided, calls create, otherwise calls save
     * @param		Dispute dispute
     * @return		Dispute
     */
	@PutMapping("/update")
    public Dispute update( @RequestBody(required=true) UpdateDisputeCommand command ) {
		Dispute entity = null;

		entity = service.updateDispute(command);
		LOGGER.info( "Successfully updated Dispute with Id " + command.getDisputeId()  );

		return entity;
	}
 
    /**
     * Handles deleting a Dispute entity
     * @param		command ${class.getDeleteCommandAlias()}
     */
    @DeleteMapping("/delete")    
    public void delete( @RequestBody(required=true) DeleteDisputeCommand command ) {                
		service.delete( command );
		LOGGER.info( "Successfully deleted Dispute with Id " + command.getDisputeId()  );
	}
	
    /**
     * Handles loading a Dispute using a UUID
     * @param		UUID uuid 
     * @return		Dispute
     */    
    @GetMapping("/load")
    public Dispute load( @RequestParam(required=true) UUID uuid ) {
    	Dispute entity = service.getDispute( new DisputeFetchOneSummary( uuid ) );

		LOGGER.info( "Successfully loaded Dispute with Id " + uuid   );

        return entity;
    }

    /**
     * Handles loading all Dispute business objects
     * @return		Set<Dispute>
     */
    @GetMapping("/")
    public List<Dispute> loadAll() {                
    	List<Dispute> disputeList = null;

		disputeList = service.getAllDispute();
		LOGGER.info( "successfully loaded all Disputes" );

        return disputeList;
                            
    }

    /**
     * save Transaction on Dispute
     * @param		command AssignTransactionToDisputeCommand
     */     
	@PutMapping("/assignTransaction")
	public void assignTransaction( @RequestBody AssignTransactionToDisputeCommand command ) {
		service.assignTransaction( command );
		LOGGER.info( "Successfully assigned Transaction with Id " + command.getDisputeId()  );
	}

    /**
     * unassign Transaction on Dispute
     * @param		 command UnAssignTransactionFromDisputeCommand
     */     
	@PutMapping("/unAssignTransaction")
	public void unAssignTransaction( @RequestBody(required=true)  UnAssignTransactionFromDisputeCommand command ) {
		service.unAssignTransaction( command );
		LOGGER.info( "Successfully unassigned Transaction with Id " + command.getDisputeId()  );
	}
	
    /**
     * save Customer on Dispute
     * @param		command AssignCustomerToDisputeCommand
     */     
	@PutMapping("/assignCustomer")
	public void assignCustomer( @RequestBody AssignCustomerToDisputeCommand command ) {
		service.assignCustomer( command );
		LOGGER.info( "Successfully assigned Customer with Id " + command.getDisputeId()  );
	}

    /**
     * unassign Customer on Dispute
     * @param		 command UnAssignCustomerFromDisputeCommand
     */     
	@PutMapping("/unAssignCustomer")
	public void unAssignCustomer( @RequestBody(required=true)  UnAssignCustomerFromDisputeCommand command ) {
		service.unAssignCustomer( command );
		LOGGER.info( "Successfully unassigned Customer with Id " + command.getDisputeId()  );
	}
	
    /**
     * save Account on Dispute
     * @param		command AssignAccountToDisputeCommand
     */     
	@PutMapping("/assignAccount")
	public void assignAccount( @RequestBody AssignAccountToDisputeCommand command ) {
		service.assignAccount( command );
		LOGGER.info( "Successfully assigned Account with Id " + command.getDisputeId()  );
	}

    /**
     * unassign Account on Dispute
     * @param		 command UnAssignAccountFromDisputeCommand
     */     
	@PutMapping("/unAssignAccount")
	public void unAssignAccount( @RequestBody(required=true)  UnAssignAccountFromDisputeCommand command ) {
		service.unAssignAccount( command );
		LOGGER.info( "Successfully unassigned Account with Id " + command.getDisputeId()  );
	}
	
    /**
     * save PaymentCard on Dispute
     * @param		command AssignPaymentCardToDisputeCommand
     */     
	@PutMapping("/assignPaymentCard")
	public void assignPaymentCard( @RequestBody AssignPaymentCardToDisputeCommand command ) {
		service.assignPaymentCard( command );
		LOGGER.info( "Successfully assigned PaymentCard with Id " + command.getDisputeId()  );
	}

    /**
     * unassign PaymentCard on Dispute
     * @param		 command UnAssignPaymentCardFromDisputeCommand
     */     
	@PutMapping("/unAssignPaymentCard")
	public void unAssignPaymentCard( @RequestBody(required=true)  UnAssignPaymentCardFromDisputeCommand command ) {
		service.unAssignPaymentCard( command );
		LOGGER.info( "Successfully unassigned PaymentCard with Id " + command.getDisputeId()  );
	}
	




//************************************************************************    
// Attributes
//************************************************************************
    protected Dispute dispute = null;
	protected DisputeService service = null;
    private static final Logger LOGGER = LoggerFactory.getLogger(DisputeRestController.class.getName());
    
}
