/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Spring Boot 3.5
 *
 * Domain Model:
 * Banking Industry Domain Model
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone National Bank Confidential
 *
 * 2026 Turnstone National Bank
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone National Bank - General Release
 */
package com.harbormaster.controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;

import java.util.*;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.harbormaster.api.*;
import com.harbormaster.service.*;
import com.harbormaster.entity.*;
import com.harbormaster.exception.*;

/**
 * FundsTransferRestController as REST API
 *
 * <p>Exposes REST endpoints for the FundsTransfer entity.</p>
 *
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Spring Boot 3.5</td></tr>
 *          <tr><td>published</td><td>09/08/2026</td></tr>
 *          <tr><td>design pattern</td><td>ServiceLayer</td></tr>
 *          <tr><td>architecture style</td><td>Layered</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>Banking Industry Domain Model</td></tr>
 *          <tr><td>description</td><td>HCIDL model capturing core banking, payments, lending, cards, KYC, and FX capabilities.</td></tr>
 *          <tr><td>industry</td><td>Banking</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Services Used</h3>
 *
 *  	FundsTransferService
 *
 * <h3>Produces</h3>
 *
 *      <p>application/json</p>
 *
 * <h3>Commands Accepted</h3>
 *      <ul>
 *      <li>CreateFundsTransferCommand</li>
 *      <li></li>UpdateFundsTransferCommand</li>
 *      <liDeleteFundsTransferCommand</li>
 *      </ul>
 *
 * <p>@author Harbormaster Dev Team</p>
 *
 */
@CrossOrigin
@RestController
@RequestMapping("/FundsTransfer")
public class FundsTransferRestController extends BaseSpringRestController {

	public FundsTransferRestController( FundsTransferService service ) {
		this.service = service;
	}
    /**
     * Handles create a FundsTransfer.  if not key provided, calls create, otherwise calls save
     * @param		FundsTransfer	fundsTransfer
     * @return		FundsTransfer 
     */
	@PostMapping("/create")
    public FundsTransfer create( @RequestBody(required=true) CreateFundsTransferCommand command ) {
    	FundsTransfer entity = null;

		entity = service.createFundsTransfer( command );
		LOGGER.info( "Successfully created FundsTransfer with Id " + entity.getFundsTransferId()  );

		return entity;
    }

    /**
     * Handles updating a FundsTransfer.  if no key provided, calls create, otherwise calls save
     * @param		FundsTransfer fundsTransfer
     * @return		FundsTransfer
     */
	@PutMapping("/update")
    public FundsTransfer update( @RequestBody(required=true) UpdateFundsTransferCommand command ) {
		FundsTransfer entity = null;

		entity = service.updateFundsTransfer(command);
		LOGGER.info( "Successfully updated FundsTransfer with Id " + command.getFundsTransferId()  );

		return entity;
	}
 
    /**
     * Handles deleting a FundsTransfer entity
     * @param		command ${class.getDeleteCommandAlias()}
     */
    @DeleteMapping("/delete")    
    public void delete( @RequestBody(required=true) DeleteFundsTransferCommand command ) {                
		service.delete( command );
		LOGGER.info( "Successfully deleted FundsTransfer with Id " + command.getFundsTransferId()  );
	}
	
    /**
     * Handles loading a FundsTransfer using a UUID
     * @param		UUID uuid 
     * @return		FundsTransfer
     */    
    @GetMapping("/load")
    public FundsTransfer load( @RequestParam(required=true) UUID uuid ) {
    	FundsTransfer entity = service.getFundsTransfer( new FundsTransferFetchOneSummary( uuid ) );

		LOGGER.info( "Successfully loaded FundsTransfer with Id " + uuid   );

        return entity;
    }

    /**
     * Handles loading all FundsTransfer business objects
     * @return		Set<FundsTransfer>
     */
    @GetMapping("/")
    public List<FundsTransfer> loadAll() {                
    	List<FundsTransfer> fundsTransferList = null;

		fundsTransferList = service.getAllFundsTransfer();
		LOGGER.info( "successfully loaded all FundsTransfers" );

        return fundsTransferList;
                            
    }

    /**
     * save SourceAccount on FundsTransfer
     * @param		command AssignSourceAccountToFundsTransferCommand
     */     
	@PutMapping("/assignSourceAccount")
	public void assignSourceAccount( @RequestBody AssignSourceAccountToFundsTransferCommand command ) {
		service.assignSourceAccount( command );
		LOGGER.info( "Successfully assigned SourceAccount with Id " + command.getFundsTransferId()  );
	}

    /**
     * unassign SourceAccount on FundsTransfer
     * @param		 command UnAssignSourceAccountFromFundsTransferCommand
     */     
	@PutMapping("/unAssignSourceAccount")
	public void unAssignSourceAccount( @RequestBody(required=true)  UnAssignSourceAccountFromFundsTransferCommand command ) {
		service.unAssignSourceAccount( command );
		LOGGER.info( "Successfully unassigned SourceAccount with Id " + command.getFundsTransferId()  );
	}
	
    /**
     * save DestinationAccount on FundsTransfer
     * @param		command AssignDestinationAccountToFundsTransferCommand
     */     
	@PutMapping("/assignDestinationAccount")
	public void assignDestinationAccount( @RequestBody AssignDestinationAccountToFundsTransferCommand command ) {
		service.assignDestinationAccount( command );
		LOGGER.info( "Successfully assigned DestinationAccount with Id " + command.getFundsTransferId()  );
	}

    /**
     * unassign DestinationAccount on FundsTransfer
     * @param		 command UnAssignDestinationAccountFromFundsTransferCommand
     */     
	@PutMapping("/unAssignDestinationAccount")
	public void unAssignDestinationAccount( @RequestBody(required=true)  UnAssignDestinationAccountFromFundsTransferCommand command ) {
		service.unAssignDestinationAccount( command );
		LOGGER.info( "Successfully unassigned DestinationAccount with Id " + command.getFundsTransferId()  );
	}
	
    /**
     * save ExternalBeneficiary on FundsTransfer
     * @param		command AssignExternalBeneficiaryToFundsTransferCommand
     */     
	@PutMapping("/assignExternalBeneficiary")
	public void assignExternalBeneficiary( @RequestBody AssignExternalBeneficiaryToFundsTransferCommand command ) {
		service.assignExternalBeneficiary( command );
		LOGGER.info( "Successfully assigned ExternalBeneficiary with Id " + command.getFundsTransferId()  );
	}

    /**
     * unassign ExternalBeneficiary on FundsTransfer
     * @param		 command UnAssignExternalBeneficiaryFromFundsTransferCommand
     */     
	@PutMapping("/unAssignExternalBeneficiary")
	public void unAssignExternalBeneficiary( @RequestBody(required=true)  UnAssignExternalBeneficiaryFromFundsTransferCommand command ) {
		service.unAssignExternalBeneficiary( command );
		LOGGER.info( "Successfully unassigned ExternalBeneficiary with Id " + command.getFundsTransferId()  );
	}
	
    /**
     * save InitiatedBy on FundsTransfer
     * @param		command AssignInitiatedByToFundsTransferCommand
     */     
	@PutMapping("/assignInitiatedBy")
	public void assignInitiatedBy( @RequestBody AssignInitiatedByToFundsTransferCommand command ) {
		service.assignInitiatedBy( command );
		LOGGER.info( "Successfully assigned InitiatedBy with Id " + command.getFundsTransferId()  );
	}

    /**
     * unassign InitiatedBy on FundsTransfer
     * @param		 command UnAssignInitiatedByFromFundsTransferCommand
     */     
	@PutMapping("/unAssignInitiatedBy")
	public void unAssignInitiatedBy( @RequestBody(required=true)  UnAssignInitiatedByFromFundsTransferCommand command ) {
		service.unAssignInitiatedBy( command );
		LOGGER.info( "Successfully unassigned InitiatedBy with Id " + command.getFundsTransferId()  );
	}
	

    /**
     * save Transactions on FundsTransfer
     * @param		command AssignTransactionsToFundsTransferCommand
     */     
	@PutMapping("/addToTransactions")
	public void addToTransactions( @RequestBody(required=true) AssignTransactionsToFundsTransferCommand command ) {
		service.addToTransactions( command );
		LOGGER.info( "Successfully added Transactions with Id " + command.getFundsTransferId()  );
	}

    /**
     * remove Transactions on FundsTransfer
     * @param		command RemoveTransactionsFromFundsTransferCommand
     */     	
	@PutMapping("/removeFromTransactions")
	public void removeFromTransactions( 	@RequestBody(required=true) RemoveTransactionsFromFundsTransferCommand command )
	{		
		service.removeFromTransactions( command );
		LOGGER.info( "Successfully removed Transactions with Id " + command.getFundsTransferId()  );
	}




//************************************************************************    
// Attributes
//************************************************************************
    protected FundsTransfer fundsTransfer = null;
	protected FundsTransferService service = null;
    private static final Logger LOGGER = LoggerFactory.getLogger(FundsTransferRestController.class.getName());
    
}
