/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Spring Boot 3.5
 *
 * Domain Model:
 * Banking Industry Domain Model
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone National Bank Confidential
 *
 * 2026 Turnstone National Bank
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone National Bank - General Release
 */
package com.harbormaster.controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;

import java.util.*;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.harbormaster.api.*;
import com.harbormaster.service.*;
import com.harbormaster.entity.*;
import com.harbormaster.exception.*;

/**
 * IdentityDocumentRestController as REST API
 *
 * <p>Exposes REST endpoints for the IdentityDocument entity.</p>
 *
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Spring Boot 3.5</td></tr>
 *          <tr><td>published</td><td>09/08/2026</td></tr>
 *          <tr><td>design pattern</td><td>ServiceLayer</td></tr>
 *          <tr><td>architecture style</td><td>Layered</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>Banking Industry Domain Model</td></tr>
 *          <tr><td>description</td><td>HCIDL model capturing core banking, payments, lending, cards, KYC, and FX capabilities.</td></tr>
 *          <tr><td>industry</td><td>Banking</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Services Used</h3>
 *
 *  	IdentityDocumentService
 *
 * <h3>Produces</h3>
 *
 *      <p>application/json</p>
 *
 * <h3>Commands Accepted</h3>
 *      <ul>
 *      <li>CreateIdentityDocumentCommand</li>
 *      <li></li>UpdateIdentityDocumentCommand</li>
 *      <liDeleteIdentityDocumentCommand</li>
 *      </ul>
 *
 * <p>@author Harbormaster Dev Team</p>
 *
 */
@CrossOrigin
@RestController
@RequestMapping("/IdentityDocument")
public class IdentityDocumentRestController extends BaseSpringRestController {

	public IdentityDocumentRestController( IdentityDocumentService service ) {
		this.service = service;
	}
    /**
     * Handles create a IdentityDocument.  if not key provided, calls create, otherwise calls save
     * @param		IdentityDocument	identityDocument
     * @return		IdentityDocument 
     */
	@PostMapping("/create")
    public IdentityDocument create( @RequestBody(required=true) CreateIdentityDocumentCommand command ) {
    	IdentityDocument entity = null;

		entity = service.createIdentityDocument( command );
		LOGGER.info( "Successfully created IdentityDocument with Id " + entity.getIdentityDocumentId()  );

		return entity;
    }

    /**
     * Handles updating a IdentityDocument.  if no key provided, calls create, otherwise calls save
     * @param		IdentityDocument identityDocument
     * @return		IdentityDocument
     */
	@PutMapping("/update")
    public IdentityDocument update( @RequestBody(required=true) UpdateIdentityDocumentCommand command ) {
		IdentityDocument entity = null;

		entity = service.updateIdentityDocument(command);
		LOGGER.info( "Successfully updated IdentityDocument with Id " + command.getIdentityDocumentId()  );

		return entity;
	}
 
    /**
     * Handles deleting a IdentityDocument entity
     * @param		command ${class.getDeleteCommandAlias()}
     */
    @DeleteMapping("/delete")    
    public void delete( @RequestBody(required=true) DeleteIdentityDocumentCommand command ) {                
		service.delete( command );
		LOGGER.info( "Successfully deleted IdentityDocument with Id " + command.getIdentityDocumentId()  );
	}
	
    /**
     * Handles loading a IdentityDocument using a UUID
     * @param		UUID uuid 
     * @return		IdentityDocument
     */    
    @GetMapping("/load")
    public IdentityDocument load( @RequestParam(required=true) UUID uuid ) {
    	IdentityDocument entity = service.getIdentityDocument( new IdentityDocumentFetchOneSummary( uuid ) );

		LOGGER.info( "Successfully loaded IdentityDocument with Id " + uuid   );

        return entity;
    }

    /**
     * Handles loading all IdentityDocument business objects
     * @return		Set<IdentityDocument>
     */
    @GetMapping("/")
    public List<IdentityDocument> loadAll() {                
    	List<IdentityDocument> identityDocumentList = null;

		identityDocumentList = service.getAllIdentityDocument();
		LOGGER.info( "successfully loaded all IdentityDocuments" );

        return identityDocumentList;
                            
    }

    /**
     * save KycProfile on IdentityDocument
     * @param		command AssignKycProfileToIdentityDocumentCommand
     */     
	@PutMapping("/assignKycProfile")
	public void assignKycProfile( @RequestBody AssignKycProfileToIdentityDocumentCommand command ) {
		service.assignKycProfile( command );
		LOGGER.info( "Successfully assigned KycProfile with Id " + command.getIdentityDocumentId()  );
	}

    /**
     * unassign KycProfile on IdentityDocument
     * @param		 command UnAssignKycProfileFromIdentityDocumentCommand
     */     
	@PutMapping("/unAssignKycProfile")
	public void unAssignKycProfile( @RequestBody(required=true)  UnAssignKycProfileFromIdentityDocumentCommand command ) {
		service.unAssignKycProfile( command );
		LOGGER.info( "Successfully unassigned KycProfile with Id " + command.getIdentityDocumentId()  );
	}
	




//************************************************************************    
// Attributes
//************************************************************************
    protected IdentityDocument identityDocument = null;
	protected IdentityDocumentService service = null;
    private static final Logger LOGGER = LoggerFactory.getLogger(IdentityDocumentRestController.class.getName());
    
}
