/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Spring Boot 3.5
 *
 * Domain Model:
 * Banking Industry Domain Model
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone National Bank Confidential
 *
 * 2026 Turnstone National Bank
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone National Bank - General Release
 */
package com.harbormaster.controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;

import java.util.*;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.harbormaster.api.*;
import com.harbormaster.service.*;
import com.harbormaster.entity.*;
import com.harbormaster.exception.*;

/**
 * PaymentCardRestController as REST API
 *
 * <p>Exposes REST endpoints for the PaymentCard entity.</p>
 *
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Spring Boot 3.5</td></tr>
 *          <tr><td>published</td><td>09/08/2026</td></tr>
 *          <tr><td>design pattern</td><td>ServiceLayer</td></tr>
 *          <tr><td>architecture style</td><td>Layered</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>Banking Industry Domain Model</td></tr>
 *          <tr><td>description</td><td>HCIDL model capturing core banking, payments, lending, cards, KYC, and FX capabilities.</td></tr>
 *          <tr><td>industry</td><td>Banking</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Services Used</h3>
 *
 *  	PaymentCardService
 *
 * <h3>Produces</h3>
 *
 *      <p>application/json</p>
 *
 * <h3>Commands Accepted</h3>
 *      <ul>
 *      <li>CreatePaymentCardCommand</li>
 *      <li></li>UpdatePaymentCardCommand</li>
 *      <liDeletePaymentCardCommand</li>
 *      </ul>
 *
 * <p>@author Harbormaster Dev Team</p>
 *
 */
@CrossOrigin
@RestController
@RequestMapping("/PaymentCard")
public class PaymentCardRestController extends BaseSpringRestController {

	public PaymentCardRestController( PaymentCardService service ) {
		this.service = service;
	}
    /**
     * Handles create a PaymentCard.  if not key provided, calls create, otherwise calls save
     * @param		PaymentCard	paymentCard
     * @return		PaymentCard 
     */
	@PostMapping("/create")
    public PaymentCard create( @RequestBody(required=true) CreatePaymentCardCommand command ) {
    	PaymentCard entity = null;

		entity = service.createPaymentCard( command );
		LOGGER.info( "Successfully created PaymentCard with Id " + entity.getPaymentCardId()  );

		return entity;
    }

    /**
     * Handles updating a PaymentCard.  if no key provided, calls create, otherwise calls save
     * @param		PaymentCard paymentCard
     * @return		PaymentCard
     */
	@PutMapping("/update")
    public PaymentCard update( @RequestBody(required=true) UpdatePaymentCardCommand command ) {
		PaymentCard entity = null;

		entity = service.updatePaymentCard(command);
		LOGGER.info( "Successfully updated PaymentCard with Id " + command.getPaymentCardId()  );

		return entity;
	}
 
    /**
     * Handles deleting a PaymentCard entity
     * @param		command ${class.getDeleteCommandAlias()}
     */
    @DeleteMapping("/delete")    
    public void delete( @RequestBody(required=true) DeletePaymentCardCommand command ) {                
		service.delete( command );
		LOGGER.info( "Successfully deleted PaymentCard with Id " + command.getPaymentCardId()  );
	}
	
    /**
     * Handles loading a PaymentCard using a UUID
     * @param		UUID uuid 
     * @return		PaymentCard
     */    
    @GetMapping("/load")
    public PaymentCard load( @RequestParam(required=true) UUID uuid ) {
    	PaymentCard entity = service.getPaymentCard( new PaymentCardFetchOneSummary( uuid ) );

		LOGGER.info( "Successfully loaded PaymentCard with Id " + uuid   );

        return entity;
    }

    /**
     * Handles loading all PaymentCard business objects
     * @return		Set<PaymentCard>
     */
    @GetMapping("/")
    public List<PaymentCard> loadAll() {                
    	List<PaymentCard> paymentCardList = null;

		paymentCardList = service.getAllPaymentCard();
		LOGGER.info( "successfully loaded all PaymentCards" );

        return paymentCardList;
                            
    }

    /**
     * save Bank on PaymentCard
     * @param		command AssignBankToPaymentCardCommand
     */     
	@PutMapping("/assignBank")
	public void assignBank( @RequestBody AssignBankToPaymentCardCommand command ) {
		service.assignBank( command );
		LOGGER.info( "Successfully assigned Bank with Id " + command.getPaymentCardId()  );
	}

    /**
     * unassign Bank on PaymentCard
     * @param		 command UnAssignBankFromPaymentCardCommand
     */     
	@PutMapping("/unAssignBank")
	public void unAssignBank( @RequestBody(required=true)  UnAssignBankFromPaymentCardCommand command ) {
		service.unAssignBank( command );
		LOGGER.info( "Successfully unassigned Bank with Id " + command.getPaymentCardId()  );
	}
	
    /**
     * save Account on PaymentCard
     * @param		command AssignAccountToPaymentCardCommand
     */     
	@PutMapping("/assignAccount")
	public void assignAccount( @RequestBody AssignAccountToPaymentCardCommand command ) {
		service.assignAccount( command );
		LOGGER.info( "Successfully assigned Account with Id " + command.getPaymentCardId()  );
	}

    /**
     * unassign Account on PaymentCard
     * @param		 command UnAssignAccountFromPaymentCardCommand
     */     
	@PutMapping("/unAssignAccount")
	public void unAssignAccount( @RequestBody(required=true)  UnAssignAccountFromPaymentCardCommand command ) {
		service.unAssignAccount( command );
		LOGGER.info( "Successfully unassigned Account with Id " + command.getPaymentCardId()  );
	}
	
    /**
     * save Customer on PaymentCard
     * @param		command AssignCustomerToPaymentCardCommand
     */     
	@PutMapping("/assignCustomer")
	public void assignCustomer( @RequestBody AssignCustomerToPaymentCardCommand command ) {
		service.assignCustomer( command );
		LOGGER.info( "Successfully assigned Customer with Id " + command.getPaymentCardId()  );
	}

    /**
     * unassign Customer on PaymentCard
     * @param		 command UnAssignCustomerFromPaymentCardCommand
     */     
	@PutMapping("/unAssignCustomer")
	public void unAssignCustomer( @RequestBody(required=true)  UnAssignCustomerFromPaymentCardCommand command ) {
		service.unAssignCustomer( command );
		LOGGER.info( "Successfully unassigned Customer with Id " + command.getPaymentCardId()  );
	}
	

    /**
     * save Transactions on PaymentCard
     * @param		command AssignTransactionsToPaymentCardCommand
     */     
	@PutMapping("/addToTransactions")
	public void addToTransactions( @RequestBody(required=true) AssignTransactionsToPaymentCardCommand command ) {
		service.addToTransactions( command );
		LOGGER.info( "Successfully added Transactions with Id " + command.getPaymentCardId()  );
	}

    /**
     * remove Transactions on PaymentCard
     * @param		command RemoveTransactionsFromPaymentCardCommand
     */     	
	@PutMapping("/removeFromTransactions")
	public void removeFromTransactions( 	@RequestBody(required=true) RemoveTransactionsFromPaymentCardCommand command )
	{		
		service.removeFromTransactions( command );
		LOGGER.info( "Successfully removed Transactions with Id " + command.getPaymentCardId()  );
	}




//************************************************************************    
// Attributes
//************************************************************************
    protected PaymentCard paymentCard = null;
	protected PaymentCardService service = null;
    private static final Logger LOGGER = LoggerFactory.getLogger(PaymentCardRestController.class.getName());
    
}
