/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Spring Boot 3.5
 *
 * Domain Model:
 * Banking Industry Domain Model
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone National Bank Confidential
 *
 * 2026 Turnstone National Bank
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone National Bank - General Release
 */
package com.harbormaster.controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;

import java.util.*;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.harbormaster.api.*;
import com.harbormaster.service.*;
import com.harbormaster.entity.*;
import com.harbormaster.exception.*;

/**
 * ScreeningResultRestController as REST API
 *
 * <p>Exposes REST endpoints for the ScreeningResult entity.</p>
 *
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Spring Boot 3.5</td></tr>
 *          <tr><td>published</td><td>09/08/2026</td></tr>
 *          <tr><td>design pattern</td><td>ServiceLayer</td></tr>
 *          <tr><td>architecture style</td><td>Layered</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>Banking Industry Domain Model</td></tr>
 *          <tr><td>description</td><td>HCIDL model capturing core banking, payments, lending, cards, KYC, and FX capabilities.</td></tr>
 *          <tr><td>industry</td><td>Banking</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Services Used</h3>
 *
 *  	ScreeningResultService
 *
 * <h3>Produces</h3>
 *
 *      <p>application/json</p>
 *
 * <h3>Commands Accepted</h3>
 *      <ul>
 *      <li>CreateScreeningResultCommand</li>
 *      <li></li>UpdateScreeningResultCommand</li>
 *      <liDeleteScreeningResultCommand</li>
 *      </ul>
 *
 * <p>@author Harbormaster Dev Team</p>
 *
 */
@CrossOrigin
@RestController
@RequestMapping("/ScreeningResult")
public class ScreeningResultRestController extends BaseSpringRestController {

	public ScreeningResultRestController( ScreeningResultService service ) {
		this.service = service;
	}
    /**
     * Handles create a ScreeningResult.  if not key provided, calls create, otherwise calls save
     * @param		ScreeningResult	screeningResult
     * @return		ScreeningResult 
     */
	@PostMapping("/create")
    public ScreeningResult create( @RequestBody(required=true) CreateScreeningResultCommand command ) {
    	ScreeningResult entity = null;

		entity = service.createScreeningResult( command );
		LOGGER.info( "Successfully created ScreeningResult with Id " + entity.getScreeningResultId()  );

		return entity;
    }

    /**
     * Handles updating a ScreeningResult.  if no key provided, calls create, otherwise calls save
     * @param		ScreeningResult screeningResult
     * @return		ScreeningResult
     */
	@PutMapping("/update")
    public ScreeningResult update( @RequestBody(required=true) UpdateScreeningResultCommand command ) {
		ScreeningResult entity = null;

		entity = service.updateScreeningResult(command);
		LOGGER.info( "Successfully updated ScreeningResult with Id " + command.getScreeningResultId()  );

		return entity;
	}
 
    /**
     * Handles deleting a ScreeningResult entity
     * @param		command ${class.getDeleteCommandAlias()}
     */
    @DeleteMapping("/delete")    
    public void delete( @RequestBody(required=true) DeleteScreeningResultCommand command ) {                
		service.delete( command );
		LOGGER.info( "Successfully deleted ScreeningResult with Id " + command.getScreeningResultId()  );
	}
	
    /**
     * Handles loading a ScreeningResult using a UUID
     * @param		UUID uuid 
     * @return		ScreeningResult
     */    
    @GetMapping("/load")
    public ScreeningResult load( @RequestParam(required=true) UUID uuid ) {
    	ScreeningResult entity = service.getScreeningResult( new ScreeningResultFetchOneSummary( uuid ) );

		LOGGER.info( "Successfully loaded ScreeningResult with Id " + uuid   );

        return entity;
    }

    /**
     * Handles loading all ScreeningResult business objects
     * @return		Set<ScreeningResult>
     */
    @GetMapping("/")
    public List<ScreeningResult> loadAll() {                
    	List<ScreeningResult> screeningResultList = null;

		screeningResultList = service.getAllScreeningResult();
		LOGGER.info( "successfully loaded all ScreeningResults" );

        return screeningResultList;
                            
    }

    /**
     * save KycProfile on ScreeningResult
     * @param		command AssignKycProfileToScreeningResultCommand
     */     
	@PutMapping("/assignKycProfile")
	public void assignKycProfile( @RequestBody AssignKycProfileToScreeningResultCommand command ) {
		service.assignKycProfile( command );
		LOGGER.info( "Successfully assigned KycProfile with Id " + command.getScreeningResultId()  );
	}

    /**
     * unassign KycProfile on ScreeningResult
     * @param		 command UnAssignKycProfileFromScreeningResultCommand
     */     
	@PutMapping("/unAssignKycProfile")
	public void unAssignKycProfile( @RequestBody(required=true)  UnAssignKycProfileFromScreeningResultCommand command ) {
		service.unAssignKycProfile( command );
		LOGGER.info( "Successfully unassigned KycProfile with Id " + command.getScreeningResultId()  );
	}
	




//************************************************************************    
// Attributes
//************************************************************************
    protected ScreeningResult screeningResult = null;
	protected ScreeningResultService service = null;
    private static final Logger LOGGER = LoggerFactory.getLogger(ScreeningResultRestController.class.getName());
    
}
