/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Spring Boot 3.5
 *
 * Domain Model:
 * Banking Industry Domain Model
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone National Bank Confidential
 *
 * 2026 Turnstone National Bank
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone National Bank - General Release
 */
package com.harbormaster.controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;

import java.util.*;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.harbormaster.api.*;
import com.harbormaster.service.*;
import com.harbormaster.entity.*;
import com.harbormaster.exception.*;

/**
 * StandingInstructionRestController as REST API
 *
 * <p>Exposes REST endpoints for the StandingInstruction entity.</p>
 *
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Spring Boot 3.5</td></tr>
 *          <tr><td>published</td><td>09/08/2026</td></tr>
 *          <tr><td>design pattern</td><td>ServiceLayer</td></tr>
 *          <tr><td>architecture style</td><td>Layered</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>Banking Industry Domain Model</td></tr>
 *          <tr><td>description</td><td>HCIDL model capturing core banking, payments, lending, cards, KYC, and FX capabilities.</td></tr>
 *          <tr><td>industry</td><td>Banking</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Services Used</h3>
 *
 *  	StandingInstructionService
 *
 * <h3>Produces</h3>
 *
 *      <p>application/json</p>
 *
 * <h3>Commands Accepted</h3>
 *      <ul>
 *      <li>CreateStandingInstructionCommand</li>
 *      <li></li>UpdateStandingInstructionCommand</li>
 *      <liDeleteStandingInstructionCommand</li>
 *      </ul>
 *
 * <p>@author Harbormaster Dev Team</p>
 *
 */
@CrossOrigin
@RestController
@RequestMapping("/StandingInstruction")
public class StandingInstructionRestController extends BaseSpringRestController {

	public StandingInstructionRestController( StandingInstructionService service ) {
		this.service = service;
	}
    /**
     * Handles create a StandingInstruction.  if not key provided, calls create, otherwise calls save
     * @param		StandingInstruction	standingInstruction
     * @return		StandingInstruction 
     */
	@PostMapping("/create")
    public StandingInstruction create( @RequestBody(required=true) CreateStandingInstructionCommand command ) {
    	StandingInstruction entity = null;

		entity = service.createStandingInstruction( command );
		LOGGER.info( "Successfully created StandingInstruction with Id " + entity.getStandingInstructionId()  );

		return entity;
    }

    /**
     * Handles updating a StandingInstruction.  if no key provided, calls create, otherwise calls save
     * @param		StandingInstruction standingInstruction
     * @return		StandingInstruction
     */
	@PutMapping("/update")
    public StandingInstruction update( @RequestBody(required=true) UpdateStandingInstructionCommand command ) {
		StandingInstruction entity = null;

		entity = service.updateStandingInstruction(command);
		LOGGER.info( "Successfully updated StandingInstruction with Id " + command.getStandingInstructionId()  );

		return entity;
	}
 
    /**
     * Handles deleting a StandingInstruction entity
     * @param		command ${class.getDeleteCommandAlias()}
     */
    @DeleteMapping("/delete")    
    public void delete( @RequestBody(required=true) DeleteStandingInstructionCommand command ) {                
		service.delete( command );
		LOGGER.info( "Successfully deleted StandingInstruction with Id " + command.getStandingInstructionId()  );
	}
	
    /**
     * Handles loading a StandingInstruction using a UUID
     * @param		UUID uuid 
     * @return		StandingInstruction
     */    
    @GetMapping("/load")
    public StandingInstruction load( @RequestParam(required=true) UUID uuid ) {
    	StandingInstruction entity = service.getStandingInstruction( new StandingInstructionFetchOneSummary( uuid ) );

		LOGGER.info( "Successfully loaded StandingInstruction with Id " + uuid   );

        return entity;
    }

    /**
     * Handles loading all StandingInstruction business objects
     * @return		Set<StandingInstruction>
     */
    @GetMapping("/")
    public List<StandingInstruction> loadAll() {                
    	List<StandingInstruction> standingInstructionList = null;

		standingInstructionList = service.getAllStandingInstruction();
		LOGGER.info( "successfully loaded all StandingInstructions" );

        return standingInstructionList;
                            
    }

    /**
     * save Account on StandingInstruction
     * @param		command AssignAccountToStandingInstructionCommand
     */     
	@PutMapping("/assignAccount")
	public void assignAccount( @RequestBody AssignAccountToStandingInstructionCommand command ) {
		service.assignAccount( command );
		LOGGER.info( "Successfully assigned Account with Id " + command.getStandingInstructionId()  );
	}

    /**
     * unassign Account on StandingInstruction
     * @param		 command UnAssignAccountFromStandingInstructionCommand
     */     
	@PutMapping("/unAssignAccount")
	public void unAssignAccount( @RequestBody(required=true)  UnAssignAccountFromStandingInstructionCommand command ) {
		service.unAssignAccount( command );
		LOGGER.info( "Successfully unassigned Account with Id " + command.getStandingInstructionId()  );
	}
	
    /**
     * save Beneficiary on StandingInstruction
     * @param		command AssignBeneficiaryToStandingInstructionCommand
     */     
	@PutMapping("/assignBeneficiary")
	public void assignBeneficiary( @RequestBody AssignBeneficiaryToStandingInstructionCommand command ) {
		service.assignBeneficiary( command );
		LOGGER.info( "Successfully assigned Beneficiary with Id " + command.getStandingInstructionId()  );
	}

    /**
     * unassign Beneficiary on StandingInstruction
     * @param		 command UnAssignBeneficiaryFromStandingInstructionCommand
     */     
	@PutMapping("/unAssignBeneficiary")
	public void unAssignBeneficiary( @RequestBody(required=true)  UnAssignBeneficiaryFromStandingInstructionCommand command ) {
		service.unAssignBeneficiary( command );
		LOGGER.info( "Successfully unassigned Beneficiary with Id " + command.getStandingInstructionId()  );
	}
	




//************************************************************************    
// Attributes
//************************************************************************
    protected StandingInstruction standingInstruction = null;
	protected StandingInstructionService service = null;
    private static final Logger LOGGER = LoggerFactory.getLogger(StandingInstructionRestController.class.getName());
    
}
