/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Spring Boot 3.5
 *
 * Domain Model:
 * Banking Industry Domain Model
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone National Bank Confidential
 *
 * 2026 Turnstone National Bank
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone National Bank - General Release
 */
package com.harbormaster.controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;

import java.util.*;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.harbormaster.api.*;
import com.harbormaster.service.*;
import com.harbormaster.entity.*;
import com.harbormaster.exception.*;

/**
 * TransactionRestController as REST API
 *
 * <p>Exposes REST endpoints for the Transaction entity.</p>
 *
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Spring Boot 3.5</td></tr>
 *          <tr><td>published</td><td>09/08/2026</td></tr>
 *          <tr><td>design pattern</td><td>ServiceLayer</td></tr>
 *          <tr><td>architecture style</td><td>Layered</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>Banking Industry Domain Model</td></tr>
 *          <tr><td>description</td><td>HCIDL model capturing core banking, payments, lending, cards, KYC, and FX capabilities.</td></tr>
 *          <tr><td>industry</td><td>Banking</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Services Used</h3>
 *
 *  	TransactionService
 *
 * <h3>Produces</h3>
 *
 *      <p>application/json</p>
 *
 * <h3>Commands Accepted</h3>
 *      <ul>
 *      <li>CreateTransactionCommand</li>
 *      <li></li>UpdateTransactionCommand</li>
 *      <liDeleteTransactionCommand</li>
 *      </ul>
 *
 * <p>@author Harbormaster Dev Team</p>
 *
 */
@CrossOrigin
@RestController
@RequestMapping("/Transaction")
public class TransactionRestController extends BaseSpringRestController {

	public TransactionRestController( TransactionService service ) {
		this.service = service;
	}
    /**
     * Handles create a Transaction.  if not key provided, calls create, otherwise calls save
     * @param		Transaction	transaction
     * @return		Transaction 
     */
	@PostMapping("/create")
    public Transaction create( @RequestBody(required=true) CreateTransactionCommand command ) {
    	Transaction entity = null;

		entity = service.createTransaction( command );
		LOGGER.info( "Successfully created Transaction with Id " + entity.getTransactionId()  );

		return entity;
    }

    /**
     * Handles updating a Transaction.  if no key provided, calls create, otherwise calls save
     * @param		Transaction transaction
     * @return		Transaction
     */
	@PutMapping("/update")
    public Transaction update( @RequestBody(required=true) UpdateTransactionCommand command ) {
		Transaction entity = null;

		entity = service.updateTransaction(command);
		LOGGER.info( "Successfully updated Transaction with Id " + command.getTransactionId()  );

		return entity;
	}
 
    /**
     * Handles deleting a Transaction entity
     * @param		command ${class.getDeleteCommandAlias()}
     */
    @DeleteMapping("/delete")    
    public void delete( @RequestBody(required=true) DeleteTransactionCommand command ) {                
		service.delete( command );
		LOGGER.info( "Successfully deleted Transaction with Id " + command.getTransactionId()  );
	}
	
    /**
     * Handles loading a Transaction using a UUID
     * @param		UUID uuid 
     * @return		Transaction
     */    
    @GetMapping("/load")
    public Transaction load( @RequestParam(required=true) UUID uuid ) {
    	Transaction entity = service.getTransaction( new TransactionFetchOneSummary( uuid ) );

		LOGGER.info( "Successfully loaded Transaction with Id " + uuid   );

        return entity;
    }

    /**
     * Handles loading all Transaction business objects
     * @return		Set<Transaction>
     */
    @GetMapping("/")
    public List<Transaction> loadAll() {                
    	List<Transaction> transactionList = null;

		transactionList = service.getAllTransaction();
		LOGGER.info( "successfully loaded all Transactions" );

        return transactionList;
                            
    }

    /**
     * save Account on Transaction
     * @param		command AssignAccountToTransactionCommand
     */     
	@PutMapping("/assignAccount")
	public void assignAccount( @RequestBody AssignAccountToTransactionCommand command ) {
		service.assignAccount( command );
		LOGGER.info( "Successfully assigned Account with Id " + command.getTransactionId()  );
	}

    /**
     * unassign Account on Transaction
     * @param		 command UnAssignAccountFromTransactionCommand
     */     
	@PutMapping("/unAssignAccount")
	public void unAssignAccount( @RequestBody(required=true)  UnAssignAccountFromTransactionCommand command ) {
		service.unAssignAccount( command );
		LOGGER.info( "Successfully unassigned Account with Id " + command.getTransactionId()  );
	}
	
    /**
     * save ExternalCounterparty on Transaction
     * @param		command AssignExternalCounterpartyToTransactionCommand
     */     
	@PutMapping("/assignExternalCounterparty")
	public void assignExternalCounterparty( @RequestBody AssignExternalCounterpartyToTransactionCommand command ) {
		service.assignExternalCounterparty( command );
		LOGGER.info( "Successfully assigned ExternalCounterparty with Id " + command.getTransactionId()  );
	}

    /**
     * unassign ExternalCounterparty on Transaction
     * @param		 command UnAssignExternalCounterpartyFromTransactionCommand
     */     
	@PutMapping("/unAssignExternalCounterparty")
	public void unAssignExternalCounterparty( @RequestBody(required=true)  UnAssignExternalCounterpartyFromTransactionCommand command ) {
		service.unAssignExternalCounterparty( command );
		LOGGER.info( "Successfully unassigned ExternalCounterparty with Id " + command.getTransactionId()  );
	}
	
    /**
     * save PaymentCard on Transaction
     * @param		command AssignPaymentCardToTransactionCommand
     */     
	@PutMapping("/assignPaymentCard")
	public void assignPaymentCard( @RequestBody AssignPaymentCardToTransactionCommand command ) {
		service.assignPaymentCard( command );
		LOGGER.info( "Successfully assigned PaymentCard with Id " + command.getTransactionId()  );
	}

    /**
     * unassign PaymentCard on Transaction
     * @param		 command UnAssignPaymentCardFromTransactionCommand
     */     
	@PutMapping("/unAssignPaymentCard")
	public void unAssignPaymentCard( @RequestBody(required=true)  UnAssignPaymentCardFromTransactionCommand command ) {
		service.unAssignPaymentCard( command );
		LOGGER.info( "Successfully unassigned PaymentCard with Id " + command.getTransactionId()  );
	}
	
    /**
     * save FundsTransfer on Transaction
     * @param		command AssignFundsTransferToTransactionCommand
     */     
	@PutMapping("/assignFundsTransfer")
	public void assignFundsTransfer( @RequestBody AssignFundsTransferToTransactionCommand command ) {
		service.assignFundsTransfer( command );
		LOGGER.info( "Successfully assigned FundsTransfer with Id " + command.getTransactionId()  );
	}

    /**
     * unassign FundsTransfer on Transaction
     * @param		 command UnAssignFundsTransferFromTransactionCommand
     */     
	@PutMapping("/unAssignFundsTransfer")
	public void unAssignFundsTransfer( @RequestBody(required=true)  UnAssignFundsTransferFromTransactionCommand command ) {
		service.unAssignFundsTransfer( command );
		LOGGER.info( "Successfully unassigned FundsTransfer with Id " + command.getTransactionId()  );
	}
	
    /**
     * save FxTrade on Transaction
     * @param		command AssignFxTradeToTransactionCommand
     */     
	@PutMapping("/assignFxTrade")
	public void assignFxTrade( @RequestBody AssignFxTradeToTransactionCommand command ) {
		service.assignFxTrade( command );
		LOGGER.info( "Successfully assigned FxTrade with Id " + command.getTransactionId()  );
	}

    /**
     * unassign FxTrade on Transaction
     * @param		 command UnAssignFxTradeFromTransactionCommand
     */     
	@PutMapping("/unAssignFxTrade")
	public void unAssignFxTrade( @RequestBody(required=true)  UnAssignFxTradeFromTransactionCommand command ) {
		service.unAssignFxTrade( command );
		LOGGER.info( "Successfully unassigned FxTrade with Id " + command.getTransactionId()  );
	}
	
    /**
     * save Dispute on Transaction
     * @param		command AssignDisputeToTransactionCommand
     */     
	@PutMapping("/assignDispute")
	public void assignDispute( @RequestBody AssignDisputeToTransactionCommand command ) {
		service.assignDispute( command );
		LOGGER.info( "Successfully assigned Dispute with Id " + command.getTransactionId()  );
	}

    /**
     * unassign Dispute on Transaction
     * @param		 command UnAssignDisputeFromTransactionCommand
     */     
	@PutMapping("/unAssignDispute")
	public void unAssignDispute( @RequestBody(required=true)  UnAssignDisputeFromTransactionCommand command ) {
		service.unAssignDispute( command );
		LOGGER.info( "Successfully unassigned Dispute with Id " + command.getTransactionId()  );
	}
	




//************************************************************************    
// Attributes
//************************************************************************
    protected Transaction transaction = null;
	protected TransactionService service = null;
    private static final Logger LOGGER = LoggerFactory.getLogger(TransactionRestController.class.getName());
    
}
