/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Spring Boot 3.5
 *
 * Domain Model:
 * Banking Industry Domain Model
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone National Bank Confidential
 *
 * 2026 Turnstone National Bank
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone National Bank - General Release
 */
package com.harbormaster.service;

import java.io.IOException;
import java.util.*;
import java.util.concurrent.*;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import org.springframework.stereotype.Service;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.ApplicationContext;


import com.harbormaster.api.*;
import com.harbormaster.entity.*;
import com.harbormaster.exception.*;
import com.harbormaster.repository.*;
import com.harbormaster.validator.*;
import com.harbormaster.projector.*;
import com.harbormaster.security.*;

/**
 *
 * <h2>Account business delegate</h2>
 *
 * <p>
 * This class implements the Business Delegate design pattern for the purpose of:
 * </p>
 * <ol>
 * <li>Reducing coupling between the business tier and a client of the business tier by hiding all business-tier implementation details</li>
 * <li>Improving the available of Account related services in the case of a Account business related service failing.</li>
 * <li>Exposes a simpler, uniform Account interface to the business tier, making it easy for clients to consume a simple Java object.</li>
 * <li>Hides the communication protocol that may be required to fulfill Account business related services.</li>
 * </ol>
 *
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Spring Boot 3.5</td></tr>
 *          <tr><td>published</td><td>09/08/2026</td></tr>
 *          <tr><td>design pattern</td><td>ServiceLayer</td></tr>
 *          <tr><td>architecture style</td><td>Layered</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>Banking Industry Domain Model</td></tr>
 *          <tr><td>description</td><td>HCIDL model capturing core banking, payments, lending, cards, KYC, and FX capabilities.</td></tr>
 *          <tr><td>industry</td><td>Banking</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Services</h3>
 *		<ul>
 * 		<li>QueryGateway</li>
 * 		<li>CommandGateway</li>
 *		<li>QueryUpdateEmitter</li>
 *		</ul>
 *
 * <h3>Produces</h3>
 *
 *      <p>application/json</p>
 *
 * <p>@author Harbormaster Dev Team</p>
 *
 */
@Service
public class AccountService 
		extends BaseService {
//************************************************************************
// Public Methods
//************************************************************************
	/**
	 * Default Constructor
	 */
    public AccountService(CurrentIdentity identity,
				ApplicationContext applicationContext)  {

		this.identity		= identity;
		this.projector 		= new AccountEntityProjector( applicationContext.getBean(ProjectorRegistry.class),
										applicationContext.getBean(AccountRepository.class) );
		this.validator		= applicationContext.getBean(AccountValidator.class) ;
	}


	/**
	 * Creates the provided command.
	 *
	 * @param		command ${class.getCreateCommandAlias()}
	 * @return		Account
	 */
		public Account createAccount( CreateAccountCommand command ) {

		Account entity = new Account();

		// --------------------------------------
		// validate the command
		// --------------------------------------
		validator.validate( command );

            entity.setAccountId( command.getAccountId() );
            entity.setAccountNumber( command.getAccountNumber() );
            entity.setIban( command.getIban() );
            entity.setAccountName( command.getAccountName() );
            entity.setCurrency( command.getCurrency() );
            entity.setOpenedOn( command.getOpenedOn() );
            entity.setClosedOn( command.getClosedOn() );
            entity.setAccountType( command.getAccountType() );
            entity.setOwnershipType( command.getOwnershipType() );
            entity.setStatus( command.getStatus() );

		// ------------------------------------------
		// persist a new one
		// ------------------------------------------
		entity = projector.create(entity);

		LOGGER.info( "done creating of Account {0} ", entity.toString() );

		return entity;
	}

	/**
	 * Update the provided command.
	 * @param		command UpdateAccountCommand
	 * @return		Account
	 */
	public Account updateAccount( UpdateAccountCommand command ) {

		Account entity = new Account();

		// --------------------------------------
		// validate
		// --------------------------------------
		validator.validate( command );

            entity.setAccountId( command.getAccountId() );
            entity.setAccountNumber( command.getAccountNumber() );
            entity.setIban( command.getIban() );
            entity.setAccountName( command.getAccountName() );
            entity.setCurrency( command.getCurrency() );
            entity.setOpenedOn( command.getOpenedOn() );
            entity.setClosedOn( command.getClosedOn() );
            entity.setBank( command.getBank() );
            entity.setBranch( command.getBranch() );
            entity.setProduct( command.getProduct() );
            entity.setOwners( command.getOwners() );
            entity.setTransactions( command.getTransactions() );
            entity.setStatements( command.getStatements() );
            entity.setStandingInstructions( command.getStandingInstructions() );
            entity.setFeeCharges( command.getFeeCharges() );
            entity.setAccountType( command.getAccountType() );
            entity.setOwnershipType( command.getOwnershipType() );
            entity.setStatus( command.getStatus() );

		// ------------------------------------------
		// persist an existing one
		// ------------------------------------------
		entity = projector.update(entity);

		LOGGER.info( "done saving of Account {0} ", entity.toString() );

		return entity;
	}

	/**
	 * Deletes the associatied value object
	 * @param		command DeleteAccountCommand
	 */
	public void delete( DeleteAccountCommand command ) {
		UUID id = null;

		// --------------------------------------
		// validate the command
		// --------------------------------------
		validator.validate( command );

		id = command.getAccountId();

		// ------------------------------------------
		// delete the entity
		// ------------------------------------------
		projector.delete(id);

		LOGGER.info( "done deleting of Account {0} ", id );

	}

	/**
	 * Method to retrieve the Account via AccountFetchOneSummary
	 * @param 	summary AccountFetchOneSummary
	 * @return 	AccountFetchOneResponse
	 */
	public Account getAccount( AccountFetchOneSummary summary ) {

		if( summary == null )
			throw new IllegalStateException( "AccountFetchOneSummary arg cannot be null" );

		Account entity = null;
		UUID id = summary.getAccountId();

		// --------------------------------------
		// validate the fetch one summary
		// --------------------------------------
		validator.validate( summary );

		// --------------------------------------
		// find a Account using the provided id
		// --------------------------------------
		entity = projector.find( id );

		return entity;
	}


	/**
	 * Method to retrieve a collection of all Accounts
	 *
	 * @return 	List<Account>
	 */
    public List<Account> getAllAccount() {
		List<Account> list = projector.findAll( new FindAllAccountQuery() );
		return list;
	}

	/**
	 * assign Bank on Account
	 * @param		command AssignBankToAccountCommand
	 */
	public void assignBank( AssignBankToAccountCommand command ) {
		// --------------------------------------
		// best to validate the command now
		// --------------------------------------
		validator.validate( command );

		// --------------------------------------
		// delegate to the projector
		// --------------------------------------
		projector.assignBank(command.getAccountId(), command.getAssignment());

	}

	/**
	 * unAssign Bank on Account
	 * @param		command UnAssignBankFromAccountCommand
	 */
	public void unAssignBank( UnAssignBankFromAccountCommand command ) {

		// --------------------------------------
		// validate the command
		// --------------------------------------
		validator.validate( command );

		// --------------------------------------
		// delegate to the projector
		// --------------------------------------
		projector.unAssignBank(command.getAccountId());
	}
	
	/**
	 * assign Branch on Account
	 * @param		command AssignBranchToAccountCommand
	 */
	public void assignBranch( AssignBranchToAccountCommand command ) {
		// --------------------------------------
		// best to validate the command now
		// --------------------------------------
		validator.validate( command );

		// --------------------------------------
		// delegate to the projector
		// --------------------------------------
		projector.assignBranch(command.getAccountId(), command.getAssignment());

	}

	/**
	 * unAssign Branch on Account
	 * @param		command UnAssignBranchFromAccountCommand
	 */
	public void unAssignBranch( UnAssignBranchFromAccountCommand command ) {

		// --------------------------------------
		// validate the command
		// --------------------------------------
		validator.validate( command );

		// --------------------------------------
		// delegate to the projector
		// --------------------------------------
		projector.unAssignBranch(command.getAccountId());
	}
	
	/**
	 * assign Product on Account
	 * @param		command AssignProductToAccountCommand
	 */
	public void assignProduct( AssignProductToAccountCommand command ) {
		// --------------------------------------
		// best to validate the command now
		// --------------------------------------
		validator.validate( command );

		// --------------------------------------
		// delegate to the projector
		// --------------------------------------
		projector.assignProduct(command.getAccountId(), command.getAssignment());

	}

	/**
	 * unAssign Product on Account
	 * @param		command UnAssignProductFromAccountCommand
	 */
	public void unAssignProduct( UnAssignProductFromAccountCommand command ) {

		// --------------------------------------
		// validate the command
		// --------------------------------------
		validator.validate( command );

		// --------------------------------------
		// delegate to the projector
		// --------------------------------------
		projector.unAssignProduct(command.getAccountId());
	}
	

	/**
	 * add Customer to Owners
	 * @param		command AssignOwnersToAccountCommand
	 */
	public void addToOwners( AssignOwnersToAccountCommand command ) {

		// --------------------------------------
		// validate the command
		// --------------------------------------
		validator.validate( command );

		// --------------------------------------
		// delegate to the projector
		// --------------------------------------
		projector.addToOwners(command.getAccountId(), command.getAddTo());
	}

	/**
	 * remove Customer from Owners
	 * @param		command RemoveOwnersFromAccountCommand
	 */
	public void removeFromOwners( RemoveOwnersFromAccountCommand command )  {
		// --------------------------------------
		// validate the command
		// --------------------------------------
		validator.validate( command );

		// --------------------------------------
		// delegate to the projector
		// --------------------------------------
		projector.removeFromOwners(command.getAccountId(), command.getRemoveFrom());
	}

	/**
	 * add Transaction to Transactions
	 * @param		command AssignTransactionsToAccountCommand
	 */
	public void addToTransactions( AssignTransactionsToAccountCommand command ) {

		// --------------------------------------
		// validate the command
		// --------------------------------------
		validator.validate( command );

		// --------------------------------------
		// delegate to the projector
		// --------------------------------------
		projector.addToTransactions(command.getAccountId(), command.getAddTo());
	}

	/**
	 * remove Transaction from Transactions
	 * @param		command RemoveTransactionsFromAccountCommand
	 */
	public void removeFromTransactions( RemoveTransactionsFromAccountCommand command )  {
		// --------------------------------------
		// validate the command
		// --------------------------------------
		validator.validate( command );

		// --------------------------------------
		// delegate to the projector
		// --------------------------------------
		projector.removeFromTransactions(command.getAccountId(), command.getRemoveFrom());
	}

	/**
	 * add AccountStatement to Statements
	 * @param		command AssignStatementsToAccountCommand
	 */
	public void addToStatements( AssignStatementsToAccountCommand command ) {

		// --------------------------------------
		// validate the command
		// --------------------------------------
		validator.validate( command );

		// --------------------------------------
		// delegate to the projector
		// --------------------------------------
		projector.addToStatements(command.getAccountId(), command.getAddTo());
	}

	/**
	 * remove AccountStatement from Statements
	 * @param		command RemoveStatementsFromAccountCommand
	 */
	public void removeFromStatements( RemoveStatementsFromAccountCommand command )  {
		// --------------------------------------
		// validate the command
		// --------------------------------------
		validator.validate( command );

		// --------------------------------------
		// delegate to the projector
		// --------------------------------------
		projector.removeFromStatements(command.getAccountId(), command.getRemoveFrom());
	}

	/**
	 * add StandingInstruction to StandingInstructions
	 * @param		command AssignStandingInstructionsToAccountCommand
	 */
	public void addToStandingInstructions( AssignStandingInstructionsToAccountCommand command ) {

		// --------------------------------------
		// validate the command
		// --------------------------------------
		validator.validate( command );

		// --------------------------------------
		// delegate to the projector
		// --------------------------------------
		projector.addToStandingInstructions(command.getAccountId(), command.getAddTo());
	}

	/**
	 * remove StandingInstruction from StandingInstructions
	 * @param		command RemoveStandingInstructionsFromAccountCommand
	 */
	public void removeFromStandingInstructions( RemoveStandingInstructionsFromAccountCommand command )  {
		// --------------------------------------
		// validate the command
		// --------------------------------------
		validator.validate( command );

		// --------------------------------------
		// delegate to the projector
		// --------------------------------------
		projector.removeFromStandingInstructions(command.getAccountId(), command.getRemoveFrom());
	}

	/**
	 * add FeeCharge to FeeCharges
	 * @param		command AssignFeeChargesToAccountCommand
	 */
	public void addToFeeCharges( AssignFeeChargesToAccountCommand command ) {

		// --------------------------------------
		// validate the command
		// --------------------------------------
		validator.validate( command );

		// --------------------------------------
		// delegate to the projector
		// --------------------------------------
		projector.addToFeeCharges(command.getAccountId(), command.getAddTo());
	}

	/**
	 * remove FeeCharge from FeeCharges
	 * @param		command RemoveFeeChargesFromAccountCommand
	 */
	public void removeFromFeeCharges( RemoveFeeChargesFromAccountCommand command )  {
		// --------------------------------------
		// validate the command
		// --------------------------------------
		validator.validate( command );

		// --------------------------------------
		// delegate to the projector
		// --------------------------------------
		projector.removeFromFeeCharges(command.getAccountId(), command.getRemoveFrom());
	}




//************************************************************************
// Attributes
//************************************************************************
	@Autowired
    private final AccountEntityProjector projector;
	private final AccountValidator validator;
	private Account account 	= null;
	private CurrentIdentity identity			= null;
	private static final Logger LOGGER 			=  LoggerFactory.getLogger(AccountService.class);
}
