/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Spring Boot 3.5
 *
 * Domain Model:
 * Banking Industry Domain Model
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone National Bank Confidential
 *
 * 2026 Turnstone National Bank
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone National Bank - General Release
 */
package com.harbormaster.service;

import java.io.IOException;
import java.util.*;
import java.util.concurrent.*;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import org.springframework.stereotype.Service;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.ApplicationContext;


import com.harbormaster.api.*;
import com.harbormaster.entity.*;
import com.harbormaster.exception.*;
import com.harbormaster.repository.*;
import com.harbormaster.validator.*;
import com.harbormaster.projector.*;
import com.harbormaster.security.*;

/**
 *
 * <h2>BankingProduct business delegate</h2>
 *
 * <p>
 * This class implements the Business Delegate design pattern for the purpose of:
 * </p>
 * <ol>
 * <li>Reducing coupling between the business tier and a client of the business tier by hiding all business-tier implementation details</li>
 * <li>Improving the available of BankingProduct related services in the case of a BankingProduct business related service failing.</li>
 * <li>Exposes a simpler, uniform BankingProduct interface to the business tier, making it easy for clients to consume a simple Java object.</li>
 * <li>Hides the communication protocol that may be required to fulfill BankingProduct business related services.</li>
 * </ol>
 *
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Spring Boot 3.5</td></tr>
 *          <tr><td>published</td><td>09/08/2026</td></tr>
 *          <tr><td>design pattern</td><td>ServiceLayer</td></tr>
 *          <tr><td>architecture style</td><td>Layered</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>Banking Industry Domain Model</td></tr>
 *          <tr><td>description</td><td>HCIDL model capturing core banking, payments, lending, cards, KYC, and FX capabilities.</td></tr>
 *          <tr><td>industry</td><td>Banking</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Services</h3>
 *		<ul>
 * 		<li>QueryGateway</li>
 * 		<li>CommandGateway</li>
 *		<li>QueryUpdateEmitter</li>
 *		</ul>
 *
 * <h3>Produces</h3>
 *
 *      <p>application/json</p>
 *
 * <p>@author Harbormaster Dev Team</p>
 *
 */
@Service
public class BankingProductService 
		extends BaseService {
//************************************************************************
// Public Methods
//************************************************************************
	/**
	 * Default Constructor
	 */
    public BankingProductService(CurrentIdentity identity,
				ApplicationContext applicationContext)  {

		this.identity		= identity;
		this.projector 		= new BankingProductEntityProjector( applicationContext.getBean(ProjectorRegistry.class),
										applicationContext.getBean(BankingProductRepository.class) );
		this.validator		= applicationContext.getBean(BankingProductValidator.class) ;
	}


	/**
	 * Creates the provided command.
	 *
	 * @param		command ${class.getCreateCommandAlias()}
	 * @return		BankingProduct
	 */
		public BankingProduct createBankingProduct( CreateBankingProductCommand command ) {

		BankingProduct entity = new BankingProduct();

		// --------------------------------------
		// validate the command
		// --------------------------------------
		validator.validate( command );

            entity.setBankingProductId( command.getBankingProductId() );
            entity.setProductCode( command.getProductCode() );
            entity.setName( command.getName() );
            entity.setDescription( command.getDescription() );
            entity.setProductCategory( command.getProductCategory() );

		// ------------------------------------------
		// persist a new one
		// ------------------------------------------
		entity = projector.create(entity);

		LOGGER.info( "done creating of BankingProduct {0} ", entity.toString() );

		return entity;
	}

	/**
	 * Update the provided command.
	 * @param		command UpdateBankingProductCommand
	 * @return		BankingProduct
	 */
	public BankingProduct updateBankingProduct( UpdateBankingProductCommand command ) {

		BankingProduct entity = new BankingProduct();

		// --------------------------------------
		// validate
		// --------------------------------------
		validator.validate( command );

            entity.setBankingProductId( command.getBankingProductId() );
            entity.setProductCode( command.getProductCode() );
            entity.setName( command.getName() );
            entity.setDescription( command.getDescription() );
            entity.setBank( command.getBank() );
            entity.setAccounts( command.getAccounts() );
            entity.setLoanAccounts( command.getLoanAccounts() );
            entity.setPaymentCards( command.getPaymentCards() );
            entity.setProductCategory( command.getProductCategory() );

		// ------------------------------------------
		// persist an existing one
		// ------------------------------------------
		entity = projector.update(entity);

		LOGGER.info( "done saving of BankingProduct {0} ", entity.toString() );

		return entity;
	}

	/**
	 * Deletes the associatied value object
	 * @param		command DeleteBankingProductCommand
	 */
	public void delete( DeleteBankingProductCommand command ) {
		UUID id = null;

		// --------------------------------------
		// validate the command
		// --------------------------------------
		validator.validate( command );

		id = command.getBankingProductId();

		// ------------------------------------------
		// delete the entity
		// ------------------------------------------
		projector.delete(id);

		LOGGER.info( "done deleting of BankingProduct {0} ", id );

	}

	/**
	 * Method to retrieve the BankingProduct via BankingProductFetchOneSummary
	 * @param 	summary BankingProductFetchOneSummary
	 * @return 	BankingProductFetchOneResponse
	 */
	public BankingProduct getBankingProduct( BankingProductFetchOneSummary summary ) {

		if( summary == null )
			throw new IllegalStateException( "BankingProductFetchOneSummary arg cannot be null" );

		BankingProduct entity = null;
		UUID id = summary.getBankingProductId();

		// --------------------------------------
		// validate the fetch one summary
		// --------------------------------------
		validator.validate( summary );

		// --------------------------------------
		// find a BankingProduct using the provided id
		// --------------------------------------
		entity = projector.find( id );

		return entity;
	}


	/**
	 * Method to retrieve a collection of all BankingProducts
	 *
	 * @return 	List<BankingProduct>
	 */
    public List<BankingProduct> getAllBankingProduct() {
		List<BankingProduct> list = projector.findAll( new FindAllBankingProductQuery() );
		return list;
	}

	/**
	 * assign Bank on BankingProduct
	 * @param		command AssignBankToBankingProductCommand
	 */
	public void assignBank( AssignBankToBankingProductCommand command ) {
		// --------------------------------------
		// best to validate the command now
		// --------------------------------------
		validator.validate( command );

		// --------------------------------------
		// delegate to the projector
		// --------------------------------------
		projector.assignBank(command.getBankingProductId(), command.getAssignment());

	}

	/**
	 * unAssign Bank on BankingProduct
	 * @param		command UnAssignBankFromBankingProductCommand
	 */
	public void unAssignBank( UnAssignBankFromBankingProductCommand command ) {

		// --------------------------------------
		// validate the command
		// --------------------------------------
		validator.validate( command );

		// --------------------------------------
		// delegate to the projector
		// --------------------------------------
		projector.unAssignBank(command.getBankingProductId());
	}
	

	/**
	 * add Account to Accounts
	 * @param		command AssignAccountsToBankingProductCommand
	 */
	public void addToAccounts( AssignAccountsToBankingProductCommand command ) {

		// --------------------------------------
		// validate the command
		// --------------------------------------
		validator.validate( command );

		// --------------------------------------
		// delegate to the projector
		// --------------------------------------
		projector.addToAccounts(command.getBankingProductId(), command.getAddTo());
	}

	/**
	 * remove Account from Accounts
	 * @param		command RemoveAccountsFromBankingProductCommand
	 */
	public void removeFromAccounts( RemoveAccountsFromBankingProductCommand command )  {
		// --------------------------------------
		// validate the command
		// --------------------------------------
		validator.validate( command );

		// --------------------------------------
		// delegate to the projector
		// --------------------------------------
		projector.removeFromAccounts(command.getBankingProductId(), command.getRemoveFrom());
	}

	/**
	 * add LoanAccount to LoanAccounts
	 * @param		command AssignLoanAccountsToBankingProductCommand
	 */
	public void addToLoanAccounts( AssignLoanAccountsToBankingProductCommand command ) {

		// --------------------------------------
		// validate the command
		// --------------------------------------
		validator.validate( command );

		// --------------------------------------
		// delegate to the projector
		// --------------------------------------
		projector.addToLoanAccounts(command.getBankingProductId(), command.getAddTo());
	}

	/**
	 * remove LoanAccount from LoanAccounts
	 * @param		command RemoveLoanAccountsFromBankingProductCommand
	 */
	public void removeFromLoanAccounts( RemoveLoanAccountsFromBankingProductCommand command )  {
		// --------------------------------------
		// validate the command
		// --------------------------------------
		validator.validate( command );

		// --------------------------------------
		// delegate to the projector
		// --------------------------------------
		projector.removeFromLoanAccounts(command.getBankingProductId(), command.getRemoveFrom());
	}

	/**
	 * add PaymentCard to PaymentCards
	 * @param		command AssignPaymentCardsToBankingProductCommand
	 */
	public void addToPaymentCards( AssignPaymentCardsToBankingProductCommand command ) {

		// --------------------------------------
		// validate the command
		// --------------------------------------
		validator.validate( command );

		// --------------------------------------
		// delegate to the projector
		// --------------------------------------
		projector.addToPaymentCards(command.getBankingProductId(), command.getAddTo());
	}

	/**
	 * remove PaymentCard from PaymentCards
	 * @param		command RemovePaymentCardsFromBankingProductCommand
	 */
	public void removeFromPaymentCards( RemovePaymentCardsFromBankingProductCommand command )  {
		// --------------------------------------
		// validate the command
		// --------------------------------------
		validator.validate( command );

		// --------------------------------------
		// delegate to the projector
		// --------------------------------------
		projector.removeFromPaymentCards(command.getBankingProductId(), command.getRemoveFrom());
	}




//************************************************************************
// Attributes
//************************************************************************
	@Autowired
    private final BankingProductEntityProjector projector;
	private final BankingProductValidator validator;
	private BankingProduct bankingProduct 	= null;
	private CurrentIdentity identity			= null;
	private static final Logger LOGGER 			=  LoggerFactory.getLogger(BankingProductService.class);
}
