/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Spring Boot 3.5
 *
 * Domain Model:
 * Banking Industry Domain Model
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone National Bank Confidential
 *
 * 2026 Turnstone National Bank
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone National Bank - General Release
 */
package com.harbormaster.service;

import java.io.IOException;
import java.util.*;
import java.util.concurrent.*;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import org.springframework.stereotype.Service;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.ApplicationContext;


import com.harbormaster.api.*;
import com.harbormaster.entity.*;
import com.harbormaster.exception.*;
import com.harbormaster.repository.*;
import com.harbormaster.validator.*;
import com.harbormaster.projector.*;
import com.harbormaster.security.*;

/**
 *
 * <h2>Bank business delegate</h2>
 *
 * <p>
 * This class implements the Business Delegate design pattern for the purpose of:
 * </p>
 * <ol>
 * <li>Reducing coupling between the business tier and a client of the business tier by hiding all business-tier implementation details</li>
 * <li>Improving the available of Bank related services in the case of a Bank business related service failing.</li>
 * <li>Exposes a simpler, uniform Bank interface to the business tier, making it easy for clients to consume a simple Java object.</li>
 * <li>Hides the communication protocol that may be required to fulfill Bank business related services.</li>
 * </ol>
 *
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Spring Boot 3.5</td></tr>
 *          <tr><td>published</td><td>09/08/2026</td></tr>
 *          <tr><td>design pattern</td><td>ServiceLayer</td></tr>
 *          <tr><td>architecture style</td><td>Layered</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>Banking Industry Domain Model</td></tr>
 *          <tr><td>description</td><td>HCIDL model capturing core banking, payments, lending, cards, KYC, and FX capabilities.</td></tr>
 *          <tr><td>industry</td><td>Banking</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Services</h3>
 *		<ul>
 * 		<li>QueryGateway</li>
 * 		<li>CommandGateway</li>
 *		<li>QueryUpdateEmitter</li>
 *		</ul>
 *
 * <h3>Produces</h3>
 *
 *      <p>application/json</p>
 *
 * <p>@author Harbormaster Dev Team</p>
 *
 */
@Service
public class BankService 
		extends BaseService {
//************************************************************************
// Public Methods
//************************************************************************
	/**
	 * Default Constructor
	 */
    public BankService(CurrentIdentity identity,
				ApplicationContext applicationContext)  {

		this.identity		= identity;
		this.projector 		= new BankEntityProjector( applicationContext.getBean(ProjectorRegistry.class),
										applicationContext.getBean(BankRepository.class) );
		this.validator		= applicationContext.getBean(BankValidator.class) ;
	}


	/**
	 * Creates the provided command.
	 *
	 * @param		command ${class.getCreateCommandAlias()}
	 * @return		Bank
	 */
		public Bank createBank( CreateBankCommand command ) {

		Bank entity = new Bank();

		// --------------------------------------
		// validate the command
		// --------------------------------------
		validator.validate( command );

            entity.setBankId( command.getBankId() );
            entity.setName( command.getName() );
            entity.setLegalName( command.getLegalName() );
            entity.setSwiftBic( command.getSwiftBic() );
            entity.setHeadquartersCountry( command.getHeadquartersCountry() );
            entity.setWebsite( command.getWebsite() );

		// ------------------------------------------
		// persist a new one
		// ------------------------------------------
		entity = projector.create(entity);

		LOGGER.info( "done creating of Bank {0} ", entity.toString() );

		return entity;
	}

	/**
	 * Update the provided command.
	 * @param		command UpdateBankCommand
	 * @return		Bank
	 */
	public Bank updateBank( UpdateBankCommand command ) {

		Bank entity = new Bank();

		// --------------------------------------
		// validate
		// --------------------------------------
		validator.validate( command );

            entity.setBankId( command.getBankId() );
            entity.setName( command.getName() );
            entity.setLegalName( command.getLegalName() );
            entity.setSwiftBic( command.getSwiftBic() );
            entity.setHeadquartersCountry( command.getHeadquartersCountry() );
            entity.setWebsite( command.getWebsite() );
            entity.setBranches( command.getBranches() );
            entity.setProducts( command.getProducts() );
            entity.setCustomers( command.getCustomers() );
            entity.setAccounts( command.getAccounts() );
            entity.setPaymentCards( command.getPaymentCards() );
            entity.setLoanAccounts( command.getLoanAccounts() );
            entity.setExchangeRates( command.getExchangeRates() );
            entity.setConsents( command.getConsents() );
            entity.setThirdPartyProviders( command.getThirdPartyProviders() );

		// ------------------------------------------
		// persist an existing one
		// ------------------------------------------
		entity = projector.update(entity);

		LOGGER.info( "done saving of Bank {0} ", entity.toString() );

		return entity;
	}

	/**
	 * Deletes the associatied value object
	 * @param		command DeleteBankCommand
	 */
	public void delete( DeleteBankCommand command ) {
		UUID id = null;

		// --------------------------------------
		// validate the command
		// --------------------------------------
		validator.validate( command );

		id = command.getBankId();

		// ------------------------------------------
		// delete the entity
		// ------------------------------------------
		projector.delete(id);

		LOGGER.info( "done deleting of Bank {0} ", id );

	}

	/**
	 * Method to retrieve the Bank via BankFetchOneSummary
	 * @param 	summary BankFetchOneSummary
	 * @return 	BankFetchOneResponse
	 */
	public Bank getBank( BankFetchOneSummary summary ) {

		if( summary == null )
			throw new IllegalStateException( "BankFetchOneSummary arg cannot be null" );

		Bank entity = null;
		UUID id = summary.getBankId();

		// --------------------------------------
		// validate the fetch one summary
		// --------------------------------------
		validator.validate( summary );

		// --------------------------------------
		// find a Bank using the provided id
		// --------------------------------------
		entity = projector.find( id );

		return entity;
	}


	/**
	 * Method to retrieve a collection of all Banks
	 *
	 * @return 	List<Bank>
	 */
    public List<Bank> getAllBank() {
		List<Bank> list = projector.findAll( new FindAllBankQuery() );
		return list;
	}


	/**
	 * add Branch to Branches
	 * @param		command AssignBranchesToBankCommand
	 */
	public void addToBranches( AssignBranchesToBankCommand command ) {

		// --------------------------------------
		// validate the command
		// --------------------------------------
		validator.validate( command );

		// --------------------------------------
		// delegate to the projector
		// --------------------------------------
		projector.addToBranches(command.getBankId(), command.getAddTo());
	}

	/**
	 * remove Branch from Branches
	 * @param		command RemoveBranchesFromBankCommand
	 */
	public void removeFromBranches( RemoveBranchesFromBankCommand command )  {
		// --------------------------------------
		// validate the command
		// --------------------------------------
		validator.validate( command );

		// --------------------------------------
		// delegate to the projector
		// --------------------------------------
		projector.removeFromBranches(command.getBankId(), command.getRemoveFrom());
	}

	/**
	 * add BankingProduct to Products
	 * @param		command AssignProductsToBankCommand
	 */
	public void addToProducts( AssignProductsToBankCommand command ) {

		// --------------------------------------
		// validate the command
		// --------------------------------------
		validator.validate( command );

		// --------------------------------------
		// delegate to the projector
		// --------------------------------------
		projector.addToProducts(command.getBankId(), command.getAddTo());
	}

	/**
	 * remove BankingProduct from Products
	 * @param		command RemoveProductsFromBankCommand
	 */
	public void removeFromProducts( RemoveProductsFromBankCommand command )  {
		// --------------------------------------
		// validate the command
		// --------------------------------------
		validator.validate( command );

		// --------------------------------------
		// delegate to the projector
		// --------------------------------------
		projector.removeFromProducts(command.getBankId(), command.getRemoveFrom());
	}

	/**
	 * add Customer to Customers
	 * @param		command AssignCustomersToBankCommand
	 */
	public void addToCustomers( AssignCustomersToBankCommand command ) {

		// --------------------------------------
		// validate the command
		// --------------------------------------
		validator.validate( command );

		// --------------------------------------
		// delegate to the projector
		// --------------------------------------
		projector.addToCustomers(command.getBankId(), command.getAddTo());
	}

	/**
	 * remove Customer from Customers
	 * @param		command RemoveCustomersFromBankCommand
	 */
	public void removeFromCustomers( RemoveCustomersFromBankCommand command )  {
		// --------------------------------------
		// validate the command
		// --------------------------------------
		validator.validate( command );

		// --------------------------------------
		// delegate to the projector
		// --------------------------------------
		projector.removeFromCustomers(command.getBankId(), command.getRemoveFrom());
	}

	/**
	 * add Account to Accounts
	 * @param		command AssignAccountsToBankCommand
	 */
	public void addToAccounts( AssignAccountsToBankCommand command ) {

		// --------------------------------------
		// validate the command
		// --------------------------------------
		validator.validate( command );

		// --------------------------------------
		// delegate to the projector
		// --------------------------------------
		projector.addToAccounts(command.getBankId(), command.getAddTo());
	}

	/**
	 * remove Account from Accounts
	 * @param		command RemoveAccountsFromBankCommand
	 */
	public void removeFromAccounts( RemoveAccountsFromBankCommand command )  {
		// --------------------------------------
		// validate the command
		// --------------------------------------
		validator.validate( command );

		// --------------------------------------
		// delegate to the projector
		// --------------------------------------
		projector.removeFromAccounts(command.getBankId(), command.getRemoveFrom());
	}

	/**
	 * add PaymentCard to PaymentCards
	 * @param		command AssignPaymentCardsToBankCommand
	 */
	public void addToPaymentCards( AssignPaymentCardsToBankCommand command ) {

		// --------------------------------------
		// validate the command
		// --------------------------------------
		validator.validate( command );

		// --------------------------------------
		// delegate to the projector
		// --------------------------------------
		projector.addToPaymentCards(command.getBankId(), command.getAddTo());
	}

	/**
	 * remove PaymentCard from PaymentCards
	 * @param		command RemovePaymentCardsFromBankCommand
	 */
	public void removeFromPaymentCards( RemovePaymentCardsFromBankCommand command )  {
		// --------------------------------------
		// validate the command
		// --------------------------------------
		validator.validate( command );

		// --------------------------------------
		// delegate to the projector
		// --------------------------------------
		projector.removeFromPaymentCards(command.getBankId(), command.getRemoveFrom());
	}

	/**
	 * add LoanAccount to LoanAccounts
	 * @param		command AssignLoanAccountsToBankCommand
	 */
	public void addToLoanAccounts( AssignLoanAccountsToBankCommand command ) {

		// --------------------------------------
		// validate the command
		// --------------------------------------
		validator.validate( command );

		// --------------------------------------
		// delegate to the projector
		// --------------------------------------
		projector.addToLoanAccounts(command.getBankId(), command.getAddTo());
	}

	/**
	 * remove LoanAccount from LoanAccounts
	 * @param		command RemoveLoanAccountsFromBankCommand
	 */
	public void removeFromLoanAccounts( RemoveLoanAccountsFromBankCommand command )  {
		// --------------------------------------
		// validate the command
		// --------------------------------------
		validator.validate( command );

		// --------------------------------------
		// delegate to the projector
		// --------------------------------------
		projector.removeFromLoanAccounts(command.getBankId(), command.getRemoveFrom());
	}

	/**
	 * add ExchangeRate to ExchangeRates
	 * @param		command AssignExchangeRatesToBankCommand
	 */
	public void addToExchangeRates( AssignExchangeRatesToBankCommand command ) {

		// --------------------------------------
		// validate the command
		// --------------------------------------
		validator.validate( command );

		// --------------------------------------
		// delegate to the projector
		// --------------------------------------
		projector.addToExchangeRates(command.getBankId(), command.getAddTo());
	}

	/**
	 * remove ExchangeRate from ExchangeRates
	 * @param		command RemoveExchangeRatesFromBankCommand
	 */
	public void removeFromExchangeRates( RemoveExchangeRatesFromBankCommand command )  {
		// --------------------------------------
		// validate the command
		// --------------------------------------
		validator.validate( command );

		// --------------------------------------
		// delegate to the projector
		// --------------------------------------
		projector.removeFromExchangeRates(command.getBankId(), command.getRemoveFrom());
	}

	/**
	 * add Consent to Consents
	 * @param		command AssignConsentsToBankCommand
	 */
	public void addToConsents( AssignConsentsToBankCommand command ) {

		// --------------------------------------
		// validate the command
		// --------------------------------------
		validator.validate( command );

		// --------------------------------------
		// delegate to the projector
		// --------------------------------------
		projector.addToConsents(command.getBankId(), command.getAddTo());
	}

	/**
	 * remove Consent from Consents
	 * @param		command RemoveConsentsFromBankCommand
	 */
	public void removeFromConsents( RemoveConsentsFromBankCommand command )  {
		// --------------------------------------
		// validate the command
		// --------------------------------------
		validator.validate( command );

		// --------------------------------------
		// delegate to the projector
		// --------------------------------------
		projector.removeFromConsents(command.getBankId(), command.getRemoveFrom());
	}

	/**
	 * add ThirdPartyProvider to ThirdPartyProviders
	 * @param		command AssignThirdPartyProvidersToBankCommand
	 */
	public void addToThirdPartyProviders( AssignThirdPartyProvidersToBankCommand command ) {

		// --------------------------------------
		// validate the command
		// --------------------------------------
		validator.validate( command );

		// --------------------------------------
		// delegate to the projector
		// --------------------------------------
		projector.addToThirdPartyProviders(command.getBankId(), command.getAddTo());
	}

	/**
	 * remove ThirdPartyProvider from ThirdPartyProviders
	 * @param		command RemoveThirdPartyProvidersFromBankCommand
	 */
	public void removeFromThirdPartyProviders( RemoveThirdPartyProvidersFromBankCommand command )  {
		// --------------------------------------
		// validate the command
		// --------------------------------------
		validator.validate( command );

		// --------------------------------------
		// delegate to the projector
		// --------------------------------------
		projector.removeFromThirdPartyProviders(command.getBankId(), command.getRemoveFrom());
	}




//************************************************************************
// Attributes
//************************************************************************
	@Autowired
    private final BankEntityProjector projector;
	private final BankValidator validator;
	private Bank bank 	= null;
	private CurrentIdentity identity			= null;
	private static final Logger LOGGER 			=  LoggerFactory.getLogger(BankService.class);
}
