/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Spring Boot 3.5
 *
 * Domain Model:
 * Banking Industry Domain Model
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone National Bank Confidential
 *
 * 2026 Turnstone National Bank
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone National Bank - General Release
 */
package com.harbormaster.service;

import java.io.IOException;
import java.util.*;
import java.util.concurrent.*;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import org.springframework.stereotype.Service;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.ApplicationContext;


import com.harbormaster.api.*;
import com.harbormaster.entity.*;
import com.harbormaster.exception.*;
import com.harbormaster.repository.*;
import com.harbormaster.validator.*;
import com.harbormaster.projector.*;
import com.harbormaster.security.*;

/**
 *
 * <h2>Collateral business delegate</h2>
 *
 * <p>
 * This class implements the Business Delegate design pattern for the purpose of:
 * </p>
 * <ol>
 * <li>Reducing coupling between the business tier and a client of the business tier by hiding all business-tier implementation details</li>
 * <li>Improving the available of Collateral related services in the case of a Collateral business related service failing.</li>
 * <li>Exposes a simpler, uniform Collateral interface to the business tier, making it easy for clients to consume a simple Java object.</li>
 * <li>Hides the communication protocol that may be required to fulfill Collateral business related services.</li>
 * </ol>
 *
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Spring Boot 3.5</td></tr>
 *          <tr><td>published</td><td>09/08/2026</td></tr>
 *          <tr><td>design pattern</td><td>ServiceLayer</td></tr>
 *          <tr><td>architecture style</td><td>Layered</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>Banking Industry Domain Model</td></tr>
 *          <tr><td>description</td><td>HCIDL model capturing core banking, payments, lending, cards, KYC, and FX capabilities.</td></tr>
 *          <tr><td>industry</td><td>Banking</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Services</h3>
 *		<ul>
 * 		<li>QueryGateway</li>
 * 		<li>CommandGateway</li>
 *		<li>QueryUpdateEmitter</li>
 *		</ul>
 *
 * <h3>Produces</h3>
 *
 *      <p>application/json</p>
 *
 * <p>@author Harbormaster Dev Team</p>
 *
 */
@Service
public class CollateralService 
		extends BaseService {
//************************************************************************
// Public Methods
//************************************************************************
	/**
	 * Default Constructor
	 */
    public CollateralService(CurrentIdentity identity,
				ApplicationContext applicationContext)  {

		this.identity		= identity;
		this.projector 		= new CollateralEntityProjector( applicationContext.getBean(ProjectorRegistry.class),
										applicationContext.getBean(CollateralRepository.class) );
		this.validator		= applicationContext.getBean(CollateralValidator.class) ;
	}


	/**
	 * Creates the provided command.
	 *
	 * @param		command ${class.getCreateCommandAlias()}
	 * @return		Collateral
	 */
		public Collateral createCollateral( CreateCollateralCommand command ) {

		Collateral entity = new Collateral();

		// --------------------------------------
		// validate the command
		// --------------------------------------
		validator.validate( command );

            entity.setCollateralId( command.getCollateralId() );
            entity.setAppraisedValue( command.getAppraisedValue() );
            entity.setDescription( command.getDescription() );
            entity.setLocation( command.getLocation() );
            entity.setCollateralType( command.getCollateralType() );

		// ------------------------------------------
		// persist a new one
		// ------------------------------------------
		entity = projector.create(entity);

		LOGGER.info( "done creating of Collateral {0} ", entity.toString() );

		return entity;
	}

	/**
	 * Update the provided command.
	 * @param		command UpdateCollateralCommand
	 * @return		Collateral
	 */
	public Collateral updateCollateral( UpdateCollateralCommand command ) {

		Collateral entity = new Collateral();

		// --------------------------------------
		// validate
		// --------------------------------------
		validator.validate( command );

            entity.setCollateralId( command.getCollateralId() );
            entity.setAppraisedValue( command.getAppraisedValue() );
            entity.setDescription( command.getDescription() );
            entity.setLocation( command.getLocation() );
            entity.setLoanAccount( command.getLoanAccount() );
            entity.setCollateralType( command.getCollateralType() );

		// ------------------------------------------
		// persist an existing one
		// ------------------------------------------
		entity = projector.update(entity);

		LOGGER.info( "done saving of Collateral {0} ", entity.toString() );

		return entity;
	}

	/**
	 * Deletes the associatied value object
	 * @param		command DeleteCollateralCommand
	 */
	public void delete( DeleteCollateralCommand command ) {
		UUID id = null;

		// --------------------------------------
		// validate the command
		// --------------------------------------
		validator.validate( command );

		id = command.getCollateralId();

		// ------------------------------------------
		// delete the entity
		// ------------------------------------------
		projector.delete(id);

		LOGGER.info( "done deleting of Collateral {0} ", id );

	}

	/**
	 * Method to retrieve the Collateral via CollateralFetchOneSummary
	 * @param 	summary CollateralFetchOneSummary
	 * @return 	CollateralFetchOneResponse
	 */
	public Collateral getCollateral( CollateralFetchOneSummary summary ) {

		if( summary == null )
			throw new IllegalStateException( "CollateralFetchOneSummary arg cannot be null" );

		Collateral entity = null;
		UUID id = summary.getCollateralId();

		// --------------------------------------
		// validate the fetch one summary
		// --------------------------------------
		validator.validate( summary );

		// --------------------------------------
		// find a Collateral using the provided id
		// --------------------------------------
		entity = projector.find( id );

		return entity;
	}


	/**
	 * Method to retrieve a collection of all Collaterals
	 *
	 * @return 	List<Collateral>
	 */
    public List<Collateral> getAllCollateral() {
		List<Collateral> list = projector.findAll( new FindAllCollateralQuery() );
		return list;
	}

	/**
	 * assign LoanAccount on Collateral
	 * @param		command AssignLoanAccountToCollateralCommand
	 */
	public void assignLoanAccount( AssignLoanAccountToCollateralCommand command ) {
		// --------------------------------------
		// best to validate the command now
		// --------------------------------------
		validator.validate( command );

		// --------------------------------------
		// delegate to the projector
		// --------------------------------------
		projector.assignLoanAccount(command.getCollateralId(), command.getAssignment());

	}

	/**
	 * unAssign LoanAccount on Collateral
	 * @param		command UnAssignLoanAccountFromCollateralCommand
	 */
	public void unAssignLoanAccount( UnAssignLoanAccountFromCollateralCommand command ) {

		// --------------------------------------
		// validate the command
		// --------------------------------------
		validator.validate( command );

		// --------------------------------------
		// delegate to the projector
		// --------------------------------------
		projector.unAssignLoanAccount(command.getCollateralId());
	}
	




//************************************************************************
// Attributes
//************************************************************************
	@Autowired
    private final CollateralEntityProjector projector;
	private final CollateralValidator validator;
	private Collateral collateral 	= null;
	private CurrentIdentity identity			= null;
	private static final Logger LOGGER 			=  LoggerFactory.getLogger(CollateralService.class);
}
