/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Spring Boot 3.5
 *
 * Domain Model:
 * Banking Industry Domain Model
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone National Bank Confidential
 *
 * 2026 Turnstone National Bank
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone National Bank - General Release
 */
package com.harbormaster.service;

import java.io.IOException;
import java.util.*;
import java.util.concurrent.*;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import org.springframework.stereotype.Service;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.ApplicationContext;


import com.harbormaster.api.*;
import com.harbormaster.entity.*;
import com.harbormaster.exception.*;
import com.harbormaster.repository.*;
import com.harbormaster.validator.*;
import com.harbormaster.projector.*;
import com.harbormaster.security.*;

/**
 *
 * <h2>Customer business delegate</h2>
 *
 * <p>
 * This class implements the Business Delegate design pattern for the purpose of:
 * </p>
 * <ol>
 * <li>Reducing coupling between the business tier and a client of the business tier by hiding all business-tier implementation details</li>
 * <li>Improving the available of Customer related services in the case of a Customer business related service failing.</li>
 * <li>Exposes a simpler, uniform Customer interface to the business tier, making it easy for clients to consume a simple Java object.</li>
 * <li>Hides the communication protocol that may be required to fulfill Customer business related services.</li>
 * </ol>
 *
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Spring Boot 3.5</td></tr>
 *          <tr><td>published</td><td>09/08/2026</td></tr>
 *          <tr><td>design pattern</td><td>ServiceLayer</td></tr>
 *          <tr><td>architecture style</td><td>Layered</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>Banking Industry Domain Model</td></tr>
 *          <tr><td>description</td><td>HCIDL model capturing core banking, payments, lending, cards, KYC, and FX capabilities.</td></tr>
 *          <tr><td>industry</td><td>Banking</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Services</h3>
 *		<ul>
 * 		<li>QueryGateway</li>
 * 		<li>CommandGateway</li>
 *		<li>QueryUpdateEmitter</li>
 *		</ul>
 *
 * <h3>Produces</h3>
 *
 *      <p>application/json</p>
 *
 * <p>@author Harbormaster Dev Team</p>
 *
 */
@Service
public class CustomerService 
		extends BaseService {
//************************************************************************
// Public Methods
//************************************************************************
	/**
	 * Default Constructor
	 */
    public CustomerService(CurrentIdentity identity,
				ApplicationContext applicationContext)  {

		this.identity		= identity;
		this.projector 		= new CustomerEntityProjector( applicationContext.getBean(ProjectorRegistry.class),
										applicationContext.getBean(CustomerRepository.class) );
		this.validator		= applicationContext.getBean(CustomerValidator.class) ;
	}


	/**
	 * Creates the provided command.
	 *
	 * @param		command ${class.getCreateCommandAlias()}
	 * @return		Customer
	 */
		public Customer createCustomer( CreateCustomerCommand command ) {

		Customer entity = new Customer();

		// --------------------------------------
		// validate the command
		// --------------------------------------
		validator.validate( command );

            entity.setCustomerId( command.getCustomerId() );
            entity.setFirstName( command.getFirstName() );
            entity.setLastName( command.getLastName() );
            entity.setLegalName( command.getLegalName() );
            entity.setDateOfBirth( command.getDateOfBirth() );
            entity.setTaxId( command.getTaxId() );
            entity.setEmail( command.getEmail() );
            entity.setPhone( command.getPhone() );
            entity.setAddress( command.getAddress() );
            entity.setCustomerType( command.getCustomerType() );
            entity.setRiskRating( command.getRiskRating() );
            entity.setKycStatus( command.getKycStatus() );

		// ------------------------------------------
		// persist a new one
		// ------------------------------------------
		entity = projector.create(entity);

		LOGGER.info( "done creating of Customer {0} ", entity.toString() );

		return entity;
	}

	/**
	 * Update the provided command.
	 * @param		command UpdateCustomerCommand
	 * @return		Customer
	 */
	public Customer updateCustomer( UpdateCustomerCommand command ) {

		Customer entity = new Customer();

		// --------------------------------------
		// validate
		// --------------------------------------
		validator.validate( command );

            entity.setCustomerId( command.getCustomerId() );
            entity.setFirstName( command.getFirstName() );
            entity.setLastName( command.getLastName() );
            entity.setLegalName( command.getLegalName() );
            entity.setDateOfBirth( command.getDateOfBirth() );
            entity.setTaxId( command.getTaxId() );
            entity.setEmail( command.getEmail() );
            entity.setPhone( command.getPhone() );
            entity.setAddress( command.getAddress() );
            entity.setBank( command.getBank() );
            entity.setAccounts( command.getAccounts() );
            entity.setLoanAccounts( command.getLoanAccounts() );
            entity.setPaymentCards( command.getPaymentCards() );
            entity.setExternalAccounts( command.getExternalAccounts() );
            entity.setFundsTransfers( command.getFundsTransfers() );
            entity.setDisputes( command.getDisputes() );
            entity.setKycProfiles( command.getKycProfiles() );
            entity.setConsents( command.getConsents() );
            entity.setCustomerType( command.getCustomerType() );
            entity.setRiskRating( command.getRiskRating() );
            entity.setKycStatus( command.getKycStatus() );

		// ------------------------------------------
		// persist an existing one
		// ------------------------------------------
		entity = projector.update(entity);

		LOGGER.info( "done saving of Customer {0} ", entity.toString() );

		return entity;
	}

	/**
	 * Deletes the associatied value object
	 * @param		command DeleteCustomerCommand
	 */
	public void delete( DeleteCustomerCommand command ) {
		UUID id = null;

		// --------------------------------------
		// validate the command
		// --------------------------------------
		validator.validate( command );

		id = command.getCustomerId();

		// ------------------------------------------
		// delete the entity
		// ------------------------------------------
		projector.delete(id);

		LOGGER.info( "done deleting of Customer {0} ", id );

	}

	/**
	 * Method to retrieve the Customer via CustomerFetchOneSummary
	 * @param 	summary CustomerFetchOneSummary
	 * @return 	CustomerFetchOneResponse
	 */
	public Customer getCustomer( CustomerFetchOneSummary summary ) {

		if( summary == null )
			throw new IllegalStateException( "CustomerFetchOneSummary arg cannot be null" );

		Customer entity = null;
		UUID id = summary.getCustomerId();

		// --------------------------------------
		// validate the fetch one summary
		// --------------------------------------
		validator.validate( summary );

		// --------------------------------------
		// find a Customer using the provided id
		// --------------------------------------
		entity = projector.find( id );

		return entity;
	}


	/**
	 * Method to retrieve a collection of all Customers
	 *
	 * @return 	List<Customer>
	 */
    public List<Customer> getAllCustomer() {
		List<Customer> list = projector.findAll( new FindAllCustomerQuery() );
		return list;
	}

	/**
	 * assign Bank on Customer
	 * @param		command AssignBankToCustomerCommand
	 */
	public void assignBank( AssignBankToCustomerCommand command ) {
		// --------------------------------------
		// best to validate the command now
		// --------------------------------------
		validator.validate( command );

		// --------------------------------------
		// delegate to the projector
		// --------------------------------------
		projector.assignBank(command.getCustomerId(), command.getAssignment());

	}

	/**
	 * unAssign Bank on Customer
	 * @param		command UnAssignBankFromCustomerCommand
	 */
	public void unAssignBank( UnAssignBankFromCustomerCommand command ) {

		// --------------------------------------
		// validate the command
		// --------------------------------------
		validator.validate( command );

		// --------------------------------------
		// delegate to the projector
		// --------------------------------------
		projector.unAssignBank(command.getCustomerId());
	}
	

	/**
	 * add Account to Accounts
	 * @param		command AssignAccountsToCustomerCommand
	 */
	public void addToAccounts( AssignAccountsToCustomerCommand command ) {

		// --------------------------------------
		// validate the command
		// --------------------------------------
		validator.validate( command );

		// --------------------------------------
		// delegate to the projector
		// --------------------------------------
		projector.addToAccounts(command.getCustomerId(), command.getAddTo());
	}

	/**
	 * remove Account from Accounts
	 * @param		command RemoveAccountsFromCustomerCommand
	 */
	public void removeFromAccounts( RemoveAccountsFromCustomerCommand command )  {
		// --------------------------------------
		// validate the command
		// --------------------------------------
		validator.validate( command );

		// --------------------------------------
		// delegate to the projector
		// --------------------------------------
		projector.removeFromAccounts(command.getCustomerId(), command.getRemoveFrom());
	}

	/**
	 * add LoanAccount to LoanAccounts
	 * @param		command AssignLoanAccountsToCustomerCommand
	 */
	public void addToLoanAccounts( AssignLoanAccountsToCustomerCommand command ) {

		// --------------------------------------
		// validate the command
		// --------------------------------------
		validator.validate( command );

		// --------------------------------------
		// delegate to the projector
		// --------------------------------------
		projector.addToLoanAccounts(command.getCustomerId(), command.getAddTo());
	}

	/**
	 * remove LoanAccount from LoanAccounts
	 * @param		command RemoveLoanAccountsFromCustomerCommand
	 */
	public void removeFromLoanAccounts( RemoveLoanAccountsFromCustomerCommand command )  {
		// --------------------------------------
		// validate the command
		// --------------------------------------
		validator.validate( command );

		// --------------------------------------
		// delegate to the projector
		// --------------------------------------
		projector.removeFromLoanAccounts(command.getCustomerId(), command.getRemoveFrom());
	}

	/**
	 * add PaymentCard to PaymentCards
	 * @param		command AssignPaymentCardsToCustomerCommand
	 */
	public void addToPaymentCards( AssignPaymentCardsToCustomerCommand command ) {

		// --------------------------------------
		// validate the command
		// --------------------------------------
		validator.validate( command );

		// --------------------------------------
		// delegate to the projector
		// --------------------------------------
		projector.addToPaymentCards(command.getCustomerId(), command.getAddTo());
	}

	/**
	 * remove PaymentCard from PaymentCards
	 * @param		command RemovePaymentCardsFromCustomerCommand
	 */
	public void removeFromPaymentCards( RemovePaymentCardsFromCustomerCommand command )  {
		// --------------------------------------
		// validate the command
		// --------------------------------------
		validator.validate( command );

		// --------------------------------------
		// delegate to the projector
		// --------------------------------------
		projector.removeFromPaymentCards(command.getCustomerId(), command.getRemoveFrom());
	}

	/**
	 * add ExternalAccount to ExternalAccounts
	 * @param		command AssignExternalAccountsToCustomerCommand
	 */
	public void addToExternalAccounts( AssignExternalAccountsToCustomerCommand command ) {

		// --------------------------------------
		// validate the command
		// --------------------------------------
		validator.validate( command );

		// --------------------------------------
		// delegate to the projector
		// --------------------------------------
		projector.addToExternalAccounts(command.getCustomerId(), command.getAddTo());
	}

	/**
	 * remove ExternalAccount from ExternalAccounts
	 * @param		command RemoveExternalAccountsFromCustomerCommand
	 */
	public void removeFromExternalAccounts( RemoveExternalAccountsFromCustomerCommand command )  {
		// --------------------------------------
		// validate the command
		// --------------------------------------
		validator.validate( command );

		// --------------------------------------
		// delegate to the projector
		// --------------------------------------
		projector.removeFromExternalAccounts(command.getCustomerId(), command.getRemoveFrom());
	}

	/**
	 * add FundsTransfer to FundsTransfers
	 * @param		command AssignFundsTransfersToCustomerCommand
	 */
	public void addToFundsTransfers( AssignFundsTransfersToCustomerCommand command ) {

		// --------------------------------------
		// validate the command
		// --------------------------------------
		validator.validate( command );

		// --------------------------------------
		// delegate to the projector
		// --------------------------------------
		projector.addToFundsTransfers(command.getCustomerId(), command.getAddTo());
	}

	/**
	 * remove FundsTransfer from FundsTransfers
	 * @param		command RemoveFundsTransfersFromCustomerCommand
	 */
	public void removeFromFundsTransfers( RemoveFundsTransfersFromCustomerCommand command )  {
		// --------------------------------------
		// validate the command
		// --------------------------------------
		validator.validate( command );

		// --------------------------------------
		// delegate to the projector
		// --------------------------------------
		projector.removeFromFundsTransfers(command.getCustomerId(), command.getRemoveFrom());
	}

	/**
	 * add Dispute to Disputes
	 * @param		command AssignDisputesToCustomerCommand
	 */
	public void addToDisputes( AssignDisputesToCustomerCommand command ) {

		// --------------------------------------
		// validate the command
		// --------------------------------------
		validator.validate( command );

		// --------------------------------------
		// delegate to the projector
		// --------------------------------------
		projector.addToDisputes(command.getCustomerId(), command.getAddTo());
	}

	/**
	 * remove Dispute from Disputes
	 * @param		command RemoveDisputesFromCustomerCommand
	 */
	public void removeFromDisputes( RemoveDisputesFromCustomerCommand command )  {
		// --------------------------------------
		// validate the command
		// --------------------------------------
		validator.validate( command );

		// --------------------------------------
		// delegate to the projector
		// --------------------------------------
		projector.removeFromDisputes(command.getCustomerId(), command.getRemoveFrom());
	}

	/**
	 * add KycProfile to KycProfiles
	 * @param		command AssignKycProfilesToCustomerCommand
	 */
	public void addToKycProfiles( AssignKycProfilesToCustomerCommand command ) {

		// --------------------------------------
		// validate the command
		// --------------------------------------
		validator.validate( command );

		// --------------------------------------
		// delegate to the projector
		// --------------------------------------
		projector.addToKycProfiles(command.getCustomerId(), command.getAddTo());
	}

	/**
	 * remove KycProfile from KycProfiles
	 * @param		command RemoveKycProfilesFromCustomerCommand
	 */
	public void removeFromKycProfiles( RemoveKycProfilesFromCustomerCommand command )  {
		// --------------------------------------
		// validate the command
		// --------------------------------------
		validator.validate( command );

		// --------------------------------------
		// delegate to the projector
		// --------------------------------------
		projector.removeFromKycProfiles(command.getCustomerId(), command.getRemoveFrom());
	}

	/**
	 * add Consent to Consents
	 * @param		command AssignConsentsToCustomerCommand
	 */
	public void addToConsents( AssignConsentsToCustomerCommand command ) {

		// --------------------------------------
		// validate the command
		// --------------------------------------
		validator.validate( command );

		// --------------------------------------
		// delegate to the projector
		// --------------------------------------
		projector.addToConsents(command.getCustomerId(), command.getAddTo());
	}

	/**
	 * remove Consent from Consents
	 * @param		command RemoveConsentsFromCustomerCommand
	 */
	public void removeFromConsents( RemoveConsentsFromCustomerCommand command )  {
		// --------------------------------------
		// validate the command
		// --------------------------------------
		validator.validate( command );

		// --------------------------------------
		// delegate to the projector
		// --------------------------------------
		projector.removeFromConsents(command.getCustomerId(), command.getRemoveFrom());
	}




//************************************************************************
// Attributes
//************************************************************************
	@Autowired
    private final CustomerEntityProjector projector;
	private final CustomerValidator validator;
	private Customer customer 	= null;
	private CurrentIdentity identity			= null;
	private static final Logger LOGGER 			=  LoggerFactory.getLogger(CustomerService.class);
}
