/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Spring Boot 3.5
 *
 * Domain Model:
 * Banking Industry Domain Model
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone National Bank Confidential
 *
 * 2026 Turnstone National Bank
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone National Bank - General Release
 */
package com.harbormaster.service;

import java.io.IOException;
import java.util.*;
import java.util.concurrent.*;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import org.springframework.stereotype.Service;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.ApplicationContext;


import com.harbormaster.api.*;
import com.harbormaster.entity.*;
import com.harbormaster.exception.*;
import com.harbormaster.repository.*;
import com.harbormaster.validator.*;
import com.harbormaster.projector.*;
import com.harbormaster.security.*;

/**
 *
 * <h2>Dispute business delegate</h2>
 *
 * <p>
 * This class implements the Business Delegate design pattern for the purpose of:
 * </p>
 * <ol>
 * <li>Reducing coupling between the business tier and a client of the business tier by hiding all business-tier implementation details</li>
 * <li>Improving the available of Dispute related services in the case of a Dispute business related service failing.</li>
 * <li>Exposes a simpler, uniform Dispute interface to the business tier, making it easy for clients to consume a simple Java object.</li>
 * <li>Hides the communication protocol that may be required to fulfill Dispute business related services.</li>
 * </ol>
 *
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Spring Boot 3.5</td></tr>
 *          <tr><td>published</td><td>09/08/2026</td></tr>
 *          <tr><td>design pattern</td><td>ServiceLayer</td></tr>
 *          <tr><td>architecture style</td><td>Layered</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>Banking Industry Domain Model</td></tr>
 *          <tr><td>description</td><td>HCIDL model capturing core banking, payments, lending, cards, KYC, and FX capabilities.</td></tr>
 *          <tr><td>industry</td><td>Banking</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Services</h3>
 *		<ul>
 * 		<li>QueryGateway</li>
 * 		<li>CommandGateway</li>
 *		<li>QueryUpdateEmitter</li>
 *		</ul>
 *
 * <h3>Produces</h3>
 *
 *      <p>application/json</p>
 *
 * <p>@author Harbormaster Dev Team</p>
 *
 */
@Service
public class DisputeService 
		extends BaseService {
//************************************************************************
// Public Methods
//************************************************************************
	/**
	 * Default Constructor
	 */
    public DisputeService(CurrentIdentity identity,
				ApplicationContext applicationContext)  {

		this.identity		= identity;
		this.projector 		= new DisputeEntityProjector( applicationContext.getBean(ProjectorRegistry.class),
										applicationContext.getBean(DisputeRepository.class) );
		this.validator		= applicationContext.getBean(DisputeValidator.class) ;
	}


	/**
	 * Creates the provided command.
	 *
	 * @param		command ${class.getCreateCommandAlias()}
	 * @return		Dispute
	 */
		public Dispute createDispute( CreateDisputeCommand command ) {

		Dispute entity = new Dispute();

		// --------------------------------------
		// validate the command
		// --------------------------------------
		validator.validate( command );

            entity.setDisputeId( command.getDisputeId() );
            entity.setDisputeReference( command.getDisputeReference() );
            entity.setRaisedOn( command.getRaisedOn() );
            entity.setReason( command.getReason() );
            entity.setStatus( command.getStatus() );

		// ------------------------------------------
		// persist a new one
		// ------------------------------------------
		entity = projector.create(entity);

		LOGGER.info( "done creating of Dispute {0} ", entity.toString() );

		return entity;
	}

	/**
	 * Update the provided command.
	 * @param		command UpdateDisputeCommand
	 * @return		Dispute
	 */
	public Dispute updateDispute( UpdateDisputeCommand command ) {

		Dispute entity = new Dispute();

		// --------------------------------------
		// validate
		// --------------------------------------
		validator.validate( command );

            entity.setDisputeId( command.getDisputeId() );
            entity.setDisputeReference( command.getDisputeReference() );
            entity.setRaisedOn( command.getRaisedOn() );
            entity.setReason( command.getReason() );
            entity.setTransaction( command.getTransaction() );
            entity.setCustomer( command.getCustomer() );
            entity.setAccount( command.getAccount() );
            entity.setPaymentCard( command.getPaymentCard() );
            entity.setStatus( command.getStatus() );

		// ------------------------------------------
		// persist an existing one
		// ------------------------------------------
		entity = projector.update(entity);

		LOGGER.info( "done saving of Dispute {0} ", entity.toString() );

		return entity;
	}

	/**
	 * Deletes the associatied value object
	 * @param		command DeleteDisputeCommand
	 */
	public void delete( DeleteDisputeCommand command ) {
		UUID id = null;

		// --------------------------------------
		// validate the command
		// --------------------------------------
		validator.validate( command );

		id = command.getDisputeId();

		// ------------------------------------------
		// delete the entity
		// ------------------------------------------
		projector.delete(id);

		LOGGER.info( "done deleting of Dispute {0} ", id );

	}

	/**
	 * Method to retrieve the Dispute via DisputeFetchOneSummary
	 * @param 	summary DisputeFetchOneSummary
	 * @return 	DisputeFetchOneResponse
	 */
	public Dispute getDispute( DisputeFetchOneSummary summary ) {

		if( summary == null )
			throw new IllegalStateException( "DisputeFetchOneSummary arg cannot be null" );

		Dispute entity = null;
		UUID id = summary.getDisputeId();

		// --------------------------------------
		// validate the fetch one summary
		// --------------------------------------
		validator.validate( summary );

		// --------------------------------------
		// find a Dispute using the provided id
		// --------------------------------------
		entity = projector.find( id );

		return entity;
	}


	/**
	 * Method to retrieve a collection of all Disputes
	 *
	 * @return 	List<Dispute>
	 */
    public List<Dispute> getAllDispute() {
		List<Dispute> list = projector.findAll( new FindAllDisputeQuery() );
		return list;
	}

	/**
	 * assign Transaction on Dispute
	 * @param		command AssignTransactionToDisputeCommand
	 */
	public void assignTransaction( AssignTransactionToDisputeCommand command ) {
		// --------------------------------------
		// best to validate the command now
		// --------------------------------------
		validator.validate( command );

		// --------------------------------------
		// delegate to the projector
		// --------------------------------------
		projector.assignTransaction(command.getDisputeId(), command.getAssignment());

	}

	/**
	 * unAssign Transaction on Dispute
	 * @param		command UnAssignTransactionFromDisputeCommand
	 */
	public void unAssignTransaction( UnAssignTransactionFromDisputeCommand command ) {

		// --------------------------------------
		// validate the command
		// --------------------------------------
		validator.validate( command );

		// --------------------------------------
		// delegate to the projector
		// --------------------------------------
		projector.unAssignTransaction(command.getDisputeId());
	}
	
	/**
	 * assign Customer on Dispute
	 * @param		command AssignCustomerToDisputeCommand
	 */
	public void assignCustomer( AssignCustomerToDisputeCommand command ) {
		// --------------------------------------
		// best to validate the command now
		// --------------------------------------
		validator.validate( command );

		// --------------------------------------
		// delegate to the projector
		// --------------------------------------
		projector.assignCustomer(command.getDisputeId(), command.getAssignment());

	}

	/**
	 * unAssign Customer on Dispute
	 * @param		command UnAssignCustomerFromDisputeCommand
	 */
	public void unAssignCustomer( UnAssignCustomerFromDisputeCommand command ) {

		// --------------------------------------
		// validate the command
		// --------------------------------------
		validator.validate( command );

		// --------------------------------------
		// delegate to the projector
		// --------------------------------------
		projector.unAssignCustomer(command.getDisputeId());
	}
	
	/**
	 * assign Account on Dispute
	 * @param		command AssignAccountToDisputeCommand
	 */
	public void assignAccount( AssignAccountToDisputeCommand command ) {
		// --------------------------------------
		// best to validate the command now
		// --------------------------------------
		validator.validate( command );

		// --------------------------------------
		// delegate to the projector
		// --------------------------------------
		projector.assignAccount(command.getDisputeId(), command.getAssignment());

	}

	/**
	 * unAssign Account on Dispute
	 * @param		command UnAssignAccountFromDisputeCommand
	 */
	public void unAssignAccount( UnAssignAccountFromDisputeCommand command ) {

		// --------------------------------------
		// validate the command
		// --------------------------------------
		validator.validate( command );

		// --------------------------------------
		// delegate to the projector
		// --------------------------------------
		projector.unAssignAccount(command.getDisputeId());
	}
	
	/**
	 * assign PaymentCard on Dispute
	 * @param		command AssignPaymentCardToDisputeCommand
	 */
	public void assignPaymentCard( AssignPaymentCardToDisputeCommand command ) {
		// --------------------------------------
		// best to validate the command now
		// --------------------------------------
		validator.validate( command );

		// --------------------------------------
		// delegate to the projector
		// --------------------------------------
		projector.assignPaymentCard(command.getDisputeId(), command.getAssignment());

	}

	/**
	 * unAssign PaymentCard on Dispute
	 * @param		command UnAssignPaymentCardFromDisputeCommand
	 */
	public void unAssignPaymentCard( UnAssignPaymentCardFromDisputeCommand command ) {

		// --------------------------------------
		// validate the command
		// --------------------------------------
		validator.validate( command );

		// --------------------------------------
		// delegate to the projector
		// --------------------------------------
		projector.unAssignPaymentCard(command.getDisputeId());
	}
	




//************************************************************************
// Attributes
//************************************************************************
	@Autowired
    private final DisputeEntityProjector projector;
	private final DisputeValidator validator;
	private Dispute dispute 	= null;
	private CurrentIdentity identity			= null;
	private static final Logger LOGGER 			=  LoggerFactory.getLogger(DisputeService.class);
}
