/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Spring Boot 3.5
 *
 * Domain Model:
 * Banking Industry Domain Model
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone National Bank Confidential
 *
 * 2026 Turnstone National Bank
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone National Bank - General Release
 */
package com.harbormaster.service;

import java.io.IOException;
import java.util.*;
import java.util.concurrent.*;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import org.springframework.stereotype.Service;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.ApplicationContext;


import com.harbormaster.api.*;
import com.harbormaster.entity.*;
import com.harbormaster.exception.*;
import com.harbormaster.repository.*;
import com.harbormaster.validator.*;
import com.harbormaster.projector.*;
import com.harbormaster.security.*;

/**
 *
 * <h2>FeeCharge business delegate</h2>
 *
 * <p>
 * This class implements the Business Delegate design pattern for the purpose of:
 * </p>
 * <ol>
 * <li>Reducing coupling between the business tier and a client of the business tier by hiding all business-tier implementation details</li>
 * <li>Improving the available of FeeCharge related services in the case of a FeeCharge business related service failing.</li>
 * <li>Exposes a simpler, uniform FeeCharge interface to the business tier, making it easy for clients to consume a simple Java object.</li>
 * <li>Hides the communication protocol that may be required to fulfill FeeCharge business related services.</li>
 * </ol>
 *
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Spring Boot 3.5</td></tr>
 *          <tr><td>published</td><td>09/08/2026</td></tr>
 *          <tr><td>design pattern</td><td>ServiceLayer</td></tr>
 *          <tr><td>architecture style</td><td>Layered</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>Banking Industry Domain Model</td></tr>
 *          <tr><td>description</td><td>HCIDL model capturing core banking, payments, lending, cards, KYC, and FX capabilities.</td></tr>
 *          <tr><td>industry</td><td>Banking</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Services</h3>
 *		<ul>
 * 		<li>QueryGateway</li>
 * 		<li>CommandGateway</li>
 *		<li>QueryUpdateEmitter</li>
 *		</ul>
 *
 * <h3>Produces</h3>
 *
 *      <p>application/json</p>
 *
 * <p>@author Harbormaster Dev Team</p>
 *
 */
@Service
public class FeeChargeService 
		extends BaseService {
//************************************************************************
// Public Methods
//************************************************************************
	/**
	 * Default Constructor
	 */
    public FeeChargeService(CurrentIdentity identity,
				ApplicationContext applicationContext)  {

		this.identity		= identity;
		this.projector 		= new FeeChargeEntityProjector( applicationContext.getBean(ProjectorRegistry.class),
										applicationContext.getBean(FeeChargeRepository.class) );
		this.validator		= applicationContext.getBean(FeeChargeValidator.class) ;
	}


	/**
	 * Creates the provided command.
	 *
	 * @param		command ${class.getCreateCommandAlias()}
	 * @return		FeeCharge
	 */
		public FeeCharge createFeeCharge( CreateFeeChargeCommand command ) {

		FeeCharge entity = new FeeCharge();

		// --------------------------------------
		// validate the command
		// --------------------------------------
		validator.validate( command );

            entity.setFeeChargeId( command.getFeeChargeId() );
            entity.setFeeCode( command.getFeeCode() );
            entity.setAmount( command.getAmount() );
            entity.setAppliedOn( command.getAppliedOn() );
            entity.setFeeType( command.getFeeType() );

		// ------------------------------------------
		// persist a new one
		// ------------------------------------------
		entity = projector.create(entity);

		LOGGER.info( "done creating of FeeCharge {0} ", entity.toString() );

		return entity;
	}

	/**
	 * Update the provided command.
	 * @param		command UpdateFeeChargeCommand
	 * @return		FeeCharge
	 */
	public FeeCharge updateFeeCharge( UpdateFeeChargeCommand command ) {

		FeeCharge entity = new FeeCharge();

		// --------------------------------------
		// validate
		// --------------------------------------
		validator.validate( command );

            entity.setFeeChargeId( command.getFeeChargeId() );
            entity.setFeeCode( command.getFeeCode() );
            entity.setAmount( command.getAmount() );
            entity.setAppliedOn( command.getAppliedOn() );
            entity.setAccount( command.getAccount() );
            entity.setLoanAccount( command.getLoanAccount() );
            entity.setFeeType( command.getFeeType() );

		// ------------------------------------------
		// persist an existing one
		// ------------------------------------------
		entity = projector.update(entity);

		LOGGER.info( "done saving of FeeCharge {0} ", entity.toString() );

		return entity;
	}

	/**
	 * Deletes the associatied value object
	 * @param		command DeleteFeeChargeCommand
	 */
	public void delete( DeleteFeeChargeCommand command ) {
		UUID id = null;

		// --------------------------------------
		// validate the command
		// --------------------------------------
		validator.validate( command );

		id = command.getFeeChargeId();

		// ------------------------------------------
		// delete the entity
		// ------------------------------------------
		projector.delete(id);

		LOGGER.info( "done deleting of FeeCharge {0} ", id );

	}

	/**
	 * Method to retrieve the FeeCharge via FeeChargeFetchOneSummary
	 * @param 	summary FeeChargeFetchOneSummary
	 * @return 	FeeChargeFetchOneResponse
	 */
	public FeeCharge getFeeCharge( FeeChargeFetchOneSummary summary ) {

		if( summary == null )
			throw new IllegalStateException( "FeeChargeFetchOneSummary arg cannot be null" );

		FeeCharge entity = null;
		UUID id = summary.getFeeChargeId();

		// --------------------------------------
		// validate the fetch one summary
		// --------------------------------------
		validator.validate( summary );

		// --------------------------------------
		// find a FeeCharge using the provided id
		// --------------------------------------
		entity = projector.find( id );

		return entity;
	}


	/**
	 * Method to retrieve a collection of all FeeCharges
	 *
	 * @return 	List<FeeCharge>
	 */
    public List<FeeCharge> getAllFeeCharge() {
		List<FeeCharge> list = projector.findAll( new FindAllFeeChargeQuery() );
		return list;
	}

	/**
	 * assign Account on FeeCharge
	 * @param		command AssignAccountToFeeChargeCommand
	 */
	public void assignAccount( AssignAccountToFeeChargeCommand command ) {
		// --------------------------------------
		// best to validate the command now
		// --------------------------------------
		validator.validate( command );

		// --------------------------------------
		// delegate to the projector
		// --------------------------------------
		projector.assignAccount(command.getFeeChargeId(), command.getAssignment());

	}

	/**
	 * unAssign Account on FeeCharge
	 * @param		command UnAssignAccountFromFeeChargeCommand
	 */
	public void unAssignAccount( UnAssignAccountFromFeeChargeCommand command ) {

		// --------------------------------------
		// validate the command
		// --------------------------------------
		validator.validate( command );

		// --------------------------------------
		// delegate to the projector
		// --------------------------------------
		projector.unAssignAccount(command.getFeeChargeId());
	}
	
	/**
	 * assign LoanAccount on FeeCharge
	 * @param		command AssignLoanAccountToFeeChargeCommand
	 */
	public void assignLoanAccount( AssignLoanAccountToFeeChargeCommand command ) {
		// --------------------------------------
		// best to validate the command now
		// --------------------------------------
		validator.validate( command );

		// --------------------------------------
		// delegate to the projector
		// --------------------------------------
		projector.assignLoanAccount(command.getFeeChargeId(), command.getAssignment());

	}

	/**
	 * unAssign LoanAccount on FeeCharge
	 * @param		command UnAssignLoanAccountFromFeeChargeCommand
	 */
	public void unAssignLoanAccount( UnAssignLoanAccountFromFeeChargeCommand command ) {

		// --------------------------------------
		// validate the command
		// --------------------------------------
		validator.validate( command );

		// --------------------------------------
		// delegate to the projector
		// --------------------------------------
		projector.unAssignLoanAccount(command.getFeeChargeId());
	}
	




//************************************************************************
// Attributes
//************************************************************************
	@Autowired
    private final FeeChargeEntityProjector projector;
	private final FeeChargeValidator validator;
	private FeeCharge feeCharge 	= null;
	private CurrentIdentity identity			= null;
	private static final Logger LOGGER 			=  LoggerFactory.getLogger(FeeChargeService.class);
}
