/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Spring Boot 3.5
 *
 * Domain Model:
 * Banking Industry Domain Model
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone National Bank Confidential
 *
 * 2026 Turnstone National Bank
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone National Bank - General Release
 */
package com.harbormaster.service;

import java.io.IOException;
import java.util.*;
import java.util.concurrent.*;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import org.springframework.stereotype.Service;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.ApplicationContext;


import com.harbormaster.api.*;
import com.harbormaster.entity.*;
import com.harbormaster.exception.*;
import com.harbormaster.repository.*;
import com.harbormaster.validator.*;
import com.harbormaster.projector.*;
import com.harbormaster.security.*;

/**
 *
 * <h2>FundsTransfer business delegate</h2>
 *
 * <p>
 * This class implements the Business Delegate design pattern for the purpose of:
 * </p>
 * <ol>
 * <li>Reducing coupling between the business tier and a client of the business tier by hiding all business-tier implementation details</li>
 * <li>Improving the available of FundsTransfer related services in the case of a FundsTransfer business related service failing.</li>
 * <li>Exposes a simpler, uniform FundsTransfer interface to the business tier, making it easy for clients to consume a simple Java object.</li>
 * <li>Hides the communication protocol that may be required to fulfill FundsTransfer business related services.</li>
 * </ol>
 *
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Spring Boot 3.5</td></tr>
 *          <tr><td>published</td><td>09/08/2026</td></tr>
 *          <tr><td>design pattern</td><td>ServiceLayer</td></tr>
 *          <tr><td>architecture style</td><td>Layered</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>Banking Industry Domain Model</td></tr>
 *          <tr><td>description</td><td>HCIDL model capturing core banking, payments, lending, cards, KYC, and FX capabilities.</td></tr>
 *          <tr><td>industry</td><td>Banking</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Services</h3>
 *		<ul>
 * 		<li>QueryGateway</li>
 * 		<li>CommandGateway</li>
 *		<li>QueryUpdateEmitter</li>
 *		</ul>
 *
 * <h3>Produces</h3>
 *
 *      <p>application/json</p>
 *
 * <p>@author Harbormaster Dev Team</p>
 *
 */
@Service
public class FundsTransferService 
		extends BaseService {
//************************************************************************
// Public Methods
//************************************************************************
	/**
	 * Default Constructor
	 */
    public FundsTransferService(CurrentIdentity identity,
				ApplicationContext applicationContext)  {

		this.identity		= identity;
		this.projector 		= new FundsTransferEntityProjector( applicationContext.getBean(ProjectorRegistry.class),
										applicationContext.getBean(FundsTransferRepository.class) );
		this.validator		= applicationContext.getBean(FundsTransferValidator.class) ;
	}


	/**
	 * Creates the provided command.
	 *
	 * @param		command ${class.getCreateCommandAlias()}
	 * @return		FundsTransfer
	 */
		public FundsTransfer createFundsTransfer( CreateFundsTransferCommand command ) {

		FundsTransfer entity = new FundsTransfer();

		// --------------------------------------
		// validate the command
		// --------------------------------------
		validator.validate( command );

            entity.setFundsTransferId( command.getFundsTransferId() );
            entity.setTransferReference( command.getTransferReference() );
            entity.setAmount( command.getAmount() );
            entity.setRequestedDate( command.getRequestedDate() );
            entity.setExecutionDate( command.getExecutionDate() );
            entity.setPurpose( command.getPurpose() );
            entity.setFeeAmount( command.getFeeAmount() );
            entity.setMethod( command.getMethod() );
            entity.setStatus( command.getStatus() );

		// ------------------------------------------
		// persist a new one
		// ------------------------------------------
		entity = projector.create(entity);

		LOGGER.info( "done creating of FundsTransfer {0} ", entity.toString() );

		return entity;
	}

	/**
	 * Update the provided command.
	 * @param		command UpdateFundsTransferCommand
	 * @return		FundsTransfer
	 */
	public FundsTransfer updateFundsTransfer( UpdateFundsTransferCommand command ) {

		FundsTransfer entity = new FundsTransfer();

		// --------------------------------------
		// validate
		// --------------------------------------
		validator.validate( command );

            entity.setFundsTransferId( command.getFundsTransferId() );
            entity.setTransferReference( command.getTransferReference() );
            entity.setAmount( command.getAmount() );
            entity.setRequestedDate( command.getRequestedDate() );
            entity.setExecutionDate( command.getExecutionDate() );
            entity.setPurpose( command.getPurpose() );
            entity.setFeeAmount( command.getFeeAmount() );
            entity.setSourceAccount( command.getSourceAccount() );
            entity.setDestinationAccount( command.getDestinationAccount() );
            entity.setExternalBeneficiary( command.getExternalBeneficiary() );
            entity.setInitiatedBy( command.getInitiatedBy() );
            entity.setTransactions( command.getTransactions() );
            entity.setMethod( command.getMethod() );
            entity.setStatus( command.getStatus() );

		// ------------------------------------------
		// persist an existing one
		// ------------------------------------------
		entity = projector.update(entity);

		LOGGER.info( "done saving of FundsTransfer {0} ", entity.toString() );

		return entity;
	}

	/**
	 * Deletes the associatied value object
	 * @param		command DeleteFundsTransferCommand
	 */
	public void delete( DeleteFundsTransferCommand command ) {
		UUID id = null;

		// --------------------------------------
		// validate the command
		// --------------------------------------
		validator.validate( command );

		id = command.getFundsTransferId();

		// ------------------------------------------
		// delete the entity
		// ------------------------------------------
		projector.delete(id);

		LOGGER.info( "done deleting of FundsTransfer {0} ", id );

	}

	/**
	 * Method to retrieve the FundsTransfer via FundsTransferFetchOneSummary
	 * @param 	summary FundsTransferFetchOneSummary
	 * @return 	FundsTransferFetchOneResponse
	 */
	public FundsTransfer getFundsTransfer( FundsTransferFetchOneSummary summary ) {

		if( summary == null )
			throw new IllegalStateException( "FundsTransferFetchOneSummary arg cannot be null" );

		FundsTransfer entity = null;
		UUID id = summary.getFundsTransferId();

		// --------------------------------------
		// validate the fetch one summary
		// --------------------------------------
		validator.validate( summary );

		// --------------------------------------
		// find a FundsTransfer using the provided id
		// --------------------------------------
		entity = projector.find( id );

		return entity;
	}


	/**
	 * Method to retrieve a collection of all FundsTransfers
	 *
	 * @return 	List<FundsTransfer>
	 */
    public List<FundsTransfer> getAllFundsTransfer() {
		List<FundsTransfer> list = projector.findAll( new FindAllFundsTransferQuery() );
		return list;
	}

	/**
	 * assign SourceAccount on FundsTransfer
	 * @param		command AssignSourceAccountToFundsTransferCommand
	 */
	public void assignSourceAccount( AssignSourceAccountToFundsTransferCommand command ) {
		// --------------------------------------
		// best to validate the command now
		// --------------------------------------
		validator.validate( command );

		// --------------------------------------
		// delegate to the projector
		// --------------------------------------
		projector.assignSourceAccount(command.getFundsTransferId(), command.getAssignment());

	}

	/**
	 * unAssign SourceAccount on FundsTransfer
	 * @param		command UnAssignSourceAccountFromFundsTransferCommand
	 */
	public void unAssignSourceAccount( UnAssignSourceAccountFromFundsTransferCommand command ) {

		// --------------------------------------
		// validate the command
		// --------------------------------------
		validator.validate( command );

		// --------------------------------------
		// delegate to the projector
		// --------------------------------------
		projector.unAssignSourceAccount(command.getFundsTransferId());
	}
	
	/**
	 * assign DestinationAccount on FundsTransfer
	 * @param		command AssignDestinationAccountToFundsTransferCommand
	 */
	public void assignDestinationAccount( AssignDestinationAccountToFundsTransferCommand command ) {
		// --------------------------------------
		// best to validate the command now
		// --------------------------------------
		validator.validate( command );

		// --------------------------------------
		// delegate to the projector
		// --------------------------------------
		projector.assignDestinationAccount(command.getFundsTransferId(), command.getAssignment());

	}

	/**
	 * unAssign DestinationAccount on FundsTransfer
	 * @param		command UnAssignDestinationAccountFromFundsTransferCommand
	 */
	public void unAssignDestinationAccount( UnAssignDestinationAccountFromFundsTransferCommand command ) {

		// --------------------------------------
		// validate the command
		// --------------------------------------
		validator.validate( command );

		// --------------------------------------
		// delegate to the projector
		// --------------------------------------
		projector.unAssignDestinationAccount(command.getFundsTransferId());
	}
	
	/**
	 * assign ExternalBeneficiary on FundsTransfer
	 * @param		command AssignExternalBeneficiaryToFundsTransferCommand
	 */
	public void assignExternalBeneficiary( AssignExternalBeneficiaryToFundsTransferCommand command ) {
		// --------------------------------------
		// best to validate the command now
		// --------------------------------------
		validator.validate( command );

		// --------------------------------------
		// delegate to the projector
		// --------------------------------------
		projector.assignExternalBeneficiary(command.getFundsTransferId(), command.getAssignment());

	}

	/**
	 * unAssign ExternalBeneficiary on FundsTransfer
	 * @param		command UnAssignExternalBeneficiaryFromFundsTransferCommand
	 */
	public void unAssignExternalBeneficiary( UnAssignExternalBeneficiaryFromFundsTransferCommand command ) {

		// --------------------------------------
		// validate the command
		// --------------------------------------
		validator.validate( command );

		// --------------------------------------
		// delegate to the projector
		// --------------------------------------
		projector.unAssignExternalBeneficiary(command.getFundsTransferId());
	}
	
	/**
	 * assign InitiatedBy on FundsTransfer
	 * @param		command AssignInitiatedByToFundsTransferCommand
	 */
	public void assignInitiatedBy( AssignInitiatedByToFundsTransferCommand command ) {
		// --------------------------------------
		// best to validate the command now
		// --------------------------------------
		validator.validate( command );

		// --------------------------------------
		// delegate to the projector
		// --------------------------------------
		projector.assignInitiatedBy(command.getFundsTransferId(), command.getAssignment());

	}

	/**
	 * unAssign InitiatedBy on FundsTransfer
	 * @param		command UnAssignInitiatedByFromFundsTransferCommand
	 */
	public void unAssignInitiatedBy( UnAssignInitiatedByFromFundsTransferCommand command ) {

		// --------------------------------------
		// validate the command
		// --------------------------------------
		validator.validate( command );

		// --------------------------------------
		// delegate to the projector
		// --------------------------------------
		projector.unAssignInitiatedBy(command.getFundsTransferId());
	}
	

	/**
	 * add Transaction to Transactions
	 * @param		command AssignTransactionsToFundsTransferCommand
	 */
	public void addToTransactions( AssignTransactionsToFundsTransferCommand command ) {

		// --------------------------------------
		// validate the command
		// --------------------------------------
		validator.validate( command );

		// --------------------------------------
		// delegate to the projector
		// --------------------------------------
		projector.addToTransactions(command.getFundsTransferId(), command.getAddTo());
	}

	/**
	 * remove Transaction from Transactions
	 * @param		command RemoveTransactionsFromFundsTransferCommand
	 */
	public void removeFromTransactions( RemoveTransactionsFromFundsTransferCommand command )  {
		// --------------------------------------
		// validate the command
		// --------------------------------------
		validator.validate( command );

		// --------------------------------------
		// delegate to the projector
		// --------------------------------------
		projector.removeFromTransactions(command.getFundsTransferId(), command.getRemoveFrom());
	}




//************************************************************************
// Attributes
//************************************************************************
	@Autowired
    private final FundsTransferEntityProjector projector;
	private final FundsTransferValidator validator;
	private FundsTransfer fundsTransfer 	= null;
	private CurrentIdentity identity			= null;
	private static final Logger LOGGER 			=  LoggerFactory.getLogger(FundsTransferService.class);
}
