/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Spring Boot 3.5
 *
 * Domain Model:
 * Banking Industry Domain Model
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone National Bank Confidential
 *
 * 2026 Turnstone National Bank
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone National Bank - General Release
 */
package com.harbormaster.service;

import java.io.IOException;
import java.util.*;
import java.util.concurrent.*;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import org.springframework.stereotype.Service;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.ApplicationContext;


import com.harbormaster.api.*;
import com.harbormaster.entity.*;
import com.harbormaster.exception.*;
import com.harbormaster.repository.*;
import com.harbormaster.validator.*;
import com.harbormaster.projector.*;
import com.harbormaster.security.*;

/**
 *
 * <h2>LoanPayment business delegate</h2>
 *
 * <p>
 * This class implements the Business Delegate design pattern for the purpose of:
 * </p>
 * <ol>
 * <li>Reducing coupling between the business tier and a client of the business tier by hiding all business-tier implementation details</li>
 * <li>Improving the available of LoanPayment related services in the case of a LoanPayment business related service failing.</li>
 * <li>Exposes a simpler, uniform LoanPayment interface to the business tier, making it easy for clients to consume a simple Java object.</li>
 * <li>Hides the communication protocol that may be required to fulfill LoanPayment business related services.</li>
 * </ol>
 *
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Spring Boot 3.5</td></tr>
 *          <tr><td>published</td><td>09/08/2026</td></tr>
 *          <tr><td>design pattern</td><td>ServiceLayer</td></tr>
 *          <tr><td>architecture style</td><td>Layered</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>Banking Industry Domain Model</td></tr>
 *          <tr><td>description</td><td>HCIDL model capturing core banking, payments, lending, cards, KYC, and FX capabilities.</td></tr>
 *          <tr><td>industry</td><td>Banking</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Services</h3>
 *		<ul>
 * 		<li>QueryGateway</li>
 * 		<li>CommandGateway</li>
 *		<li>QueryUpdateEmitter</li>
 *		</ul>
 *
 * <h3>Produces</h3>
 *
 *      <p>application/json</p>
 *
 * <p>@author Harbormaster Dev Team</p>
 *
 */
@Service
public class LoanPaymentService 
		extends BaseService {
//************************************************************************
// Public Methods
//************************************************************************
	/**
	 * Default Constructor
	 */
    public LoanPaymentService(CurrentIdentity identity,
				ApplicationContext applicationContext)  {

		this.identity		= identity;
		this.projector 		= new LoanPaymentEntityProjector( applicationContext.getBean(ProjectorRegistry.class),
										applicationContext.getBean(LoanPaymentRepository.class) );
		this.validator		= applicationContext.getBean(LoanPaymentValidator.class) ;
	}


	/**
	 * Creates the provided command.
	 *
	 * @param		command ${class.getCreateCommandAlias()}
	 * @return		LoanPayment
	 */
		public LoanPayment createLoanPayment( CreateLoanPaymentCommand command ) {

		LoanPayment entity = new LoanPayment();

		// --------------------------------------
		// validate the command
		// --------------------------------------
		validator.validate( command );

            entity.setLoanPaymentId( command.getLoanPaymentId() );
            entity.setPaymentReference( command.getPaymentReference() );
            entity.setAmount( command.getAmount() );
            entity.setPaymentDate( command.getPaymentDate() );
            entity.setMethod( command.getMethod() );
            entity.setStatus( command.getStatus() );

		// ------------------------------------------
		// persist a new one
		// ------------------------------------------
		entity = projector.create(entity);

		LOGGER.info( "done creating of LoanPayment {0} ", entity.toString() );

		return entity;
	}

	/**
	 * Update the provided command.
	 * @param		command UpdateLoanPaymentCommand
	 * @return		LoanPayment
	 */
	public LoanPayment updateLoanPayment( UpdateLoanPaymentCommand command ) {

		LoanPayment entity = new LoanPayment();

		// --------------------------------------
		// validate
		// --------------------------------------
		validator.validate( command );

            entity.setLoanPaymentId( command.getLoanPaymentId() );
            entity.setPaymentReference( command.getPaymentReference() );
            entity.setAmount( command.getAmount() );
            entity.setPaymentDate( command.getPaymentDate() );
            entity.setLoanAccount( command.getLoanAccount() );
            entity.setTransaction( command.getTransaction() );
            entity.setMethod( command.getMethod() );
            entity.setStatus( command.getStatus() );

		// ------------------------------------------
		// persist an existing one
		// ------------------------------------------
		entity = projector.update(entity);

		LOGGER.info( "done saving of LoanPayment {0} ", entity.toString() );

		return entity;
	}

	/**
	 * Deletes the associatied value object
	 * @param		command DeleteLoanPaymentCommand
	 */
	public void delete( DeleteLoanPaymentCommand command ) {
		UUID id = null;

		// --------------------------------------
		// validate the command
		// --------------------------------------
		validator.validate( command );

		id = command.getLoanPaymentId();

		// ------------------------------------------
		// delete the entity
		// ------------------------------------------
		projector.delete(id);

		LOGGER.info( "done deleting of LoanPayment {0} ", id );

	}

	/**
	 * Method to retrieve the LoanPayment via LoanPaymentFetchOneSummary
	 * @param 	summary LoanPaymentFetchOneSummary
	 * @return 	LoanPaymentFetchOneResponse
	 */
	public LoanPayment getLoanPayment( LoanPaymentFetchOneSummary summary ) {

		if( summary == null )
			throw new IllegalStateException( "LoanPaymentFetchOneSummary arg cannot be null" );

		LoanPayment entity = null;
		UUID id = summary.getLoanPaymentId();

		// --------------------------------------
		// validate the fetch one summary
		// --------------------------------------
		validator.validate( summary );

		// --------------------------------------
		// find a LoanPayment using the provided id
		// --------------------------------------
		entity = projector.find( id );

		return entity;
	}


	/**
	 * Method to retrieve a collection of all LoanPayments
	 *
	 * @return 	List<LoanPayment>
	 */
    public List<LoanPayment> getAllLoanPayment() {
		List<LoanPayment> list = projector.findAll( new FindAllLoanPaymentQuery() );
		return list;
	}

	/**
	 * assign LoanAccount on LoanPayment
	 * @param		command AssignLoanAccountToLoanPaymentCommand
	 */
	public void assignLoanAccount( AssignLoanAccountToLoanPaymentCommand command ) {
		// --------------------------------------
		// best to validate the command now
		// --------------------------------------
		validator.validate( command );

		// --------------------------------------
		// delegate to the projector
		// --------------------------------------
		projector.assignLoanAccount(command.getLoanPaymentId(), command.getAssignment());

	}

	/**
	 * unAssign LoanAccount on LoanPayment
	 * @param		command UnAssignLoanAccountFromLoanPaymentCommand
	 */
	public void unAssignLoanAccount( UnAssignLoanAccountFromLoanPaymentCommand command ) {

		// --------------------------------------
		// validate the command
		// --------------------------------------
		validator.validate( command );

		// --------------------------------------
		// delegate to the projector
		// --------------------------------------
		projector.unAssignLoanAccount(command.getLoanPaymentId());
	}
	
	/**
	 * assign Transaction on LoanPayment
	 * @param		command AssignTransactionToLoanPaymentCommand
	 */
	public void assignTransaction( AssignTransactionToLoanPaymentCommand command ) {
		// --------------------------------------
		// best to validate the command now
		// --------------------------------------
		validator.validate( command );

		// --------------------------------------
		// delegate to the projector
		// --------------------------------------
		projector.assignTransaction(command.getLoanPaymentId(), command.getAssignment());

	}

	/**
	 * unAssign Transaction on LoanPayment
	 * @param		command UnAssignTransactionFromLoanPaymentCommand
	 */
	public void unAssignTransaction( UnAssignTransactionFromLoanPaymentCommand command ) {

		// --------------------------------------
		// validate the command
		// --------------------------------------
		validator.validate( command );

		// --------------------------------------
		// delegate to the projector
		// --------------------------------------
		projector.unAssignTransaction(command.getLoanPaymentId());
	}
	




//************************************************************************
// Attributes
//************************************************************************
	@Autowired
    private final LoanPaymentEntityProjector projector;
	private final LoanPaymentValidator validator;
	private LoanPayment loanPayment 	= null;
	private CurrentIdentity identity			= null;
	private static final Logger LOGGER 			=  LoggerFactory.getLogger(LoanPaymentService.class);
}
