/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Spring Boot 3.5
 *
 * Domain Model:
 * Banking Industry Domain Model
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone National Bank Confidential
 *
 * 2026 Turnstone National Bank
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone National Bank - General Release
 */
package com.harbormaster.service;

import java.io.IOException;
import java.util.*;
import java.util.concurrent.*;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import org.springframework.stereotype.Service;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.ApplicationContext;


import com.harbormaster.api.*;
import com.harbormaster.entity.*;
import com.harbormaster.exception.*;
import com.harbormaster.repository.*;
import com.harbormaster.validator.*;
import com.harbormaster.projector.*;
import com.harbormaster.security.*;

/**
 *
 * <h2>LoanAccount business delegate</h2>
 *
 * <p>
 * This class implements the Business Delegate design pattern for the purpose of:
 * </p>
 * <ol>
 * <li>Reducing coupling between the business tier and a client of the business tier by hiding all business-tier implementation details</li>
 * <li>Improving the available of LoanAccount related services in the case of a LoanAccount business related service failing.</li>
 * <li>Exposes a simpler, uniform LoanAccount interface to the business tier, making it easy for clients to consume a simple Java object.</li>
 * <li>Hides the communication protocol that may be required to fulfill LoanAccount business related services.</li>
 * </ol>
 *
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Spring Boot 3.5</td></tr>
 *          <tr><td>published</td><td>09/08/2026</td></tr>
 *          <tr><td>design pattern</td><td>ServiceLayer</td></tr>
 *          <tr><td>architecture style</td><td>Layered</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>Banking Industry Domain Model</td></tr>
 *          <tr><td>description</td><td>HCIDL model capturing core banking, payments, lending, cards, KYC, and FX capabilities.</td></tr>
 *          <tr><td>industry</td><td>Banking</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Services</h3>
 *		<ul>
 * 		<li>QueryGateway</li>
 * 		<li>CommandGateway</li>
 *		<li>QueryUpdateEmitter</li>
 *		</ul>
 *
 * <h3>Produces</h3>
 *
 *      <p>application/json</p>
 *
 * <p>@author Harbormaster Dev Team</p>
 *
 */
@Service
public class LoanAccountService 
		extends BaseService {
//************************************************************************
// Public Methods
//************************************************************************
	/**
	 * Default Constructor
	 */
    public LoanAccountService(CurrentIdentity identity,
				ApplicationContext applicationContext)  {

		this.identity		= identity;
		this.projector 		= new LoanAccountEntityProjector( applicationContext.getBean(ProjectorRegistry.class),
										applicationContext.getBean(LoanAccountRepository.class) );
		this.validator		= applicationContext.getBean(LoanAccountValidator.class) ;
	}


	/**
	 * Creates the provided command.
	 *
	 * @param		command ${class.getCreateCommandAlias()}
	 * @return		LoanAccount
	 */
		public LoanAccount createLoanAccount( CreateLoanAccountCommand command ) {

		LoanAccount entity = new LoanAccount();

		// --------------------------------------
		// validate the command
		// --------------------------------------
		validator.validate( command );

            entity.setLoanAccountId( command.getLoanAccountId() );
            entity.setLoanNumber( command.getLoanNumber() );
            entity.setPrincipalAmount( command.getPrincipalAmount() );
            entity.setOutstandingPrincipal( command.getOutstandingPrincipal() );
            entity.setInterestRate( command.getInterestRate() );
            entity.setOriginationDate( command.getOriginationDate() );
            entity.setMaturityDate( command.getMaturityDate() );
            entity.setPaymentDayOfMonth( command.getPaymentDayOfMonth() );
            entity.setCurrency( command.getCurrency() );
            entity.setLoanType( command.getLoanType() );
            entity.setRateType( command.getRateType() );
            entity.setCompounding( command.getCompounding() );
            entity.setStatus( command.getStatus() );

		// ------------------------------------------
		// persist a new one
		// ------------------------------------------
		entity = projector.create(entity);

		LOGGER.info( "done creating of LoanAccount {0} ", entity.toString() );

		return entity;
	}

	/**
	 * Update the provided command.
	 * @param		command UpdateLoanAccountCommand
	 * @return		LoanAccount
	 */
	public LoanAccount updateLoanAccount( UpdateLoanAccountCommand command ) {

		LoanAccount entity = new LoanAccount();

		// --------------------------------------
		// validate
		// --------------------------------------
		validator.validate( command );

            entity.setLoanAccountId( command.getLoanAccountId() );
            entity.setLoanNumber( command.getLoanNumber() );
            entity.setPrincipalAmount( command.getPrincipalAmount() );
            entity.setOutstandingPrincipal( command.getOutstandingPrincipal() );
            entity.setInterestRate( command.getInterestRate() );
            entity.setOriginationDate( command.getOriginationDate() );
            entity.setMaturityDate( command.getMaturityDate() );
            entity.setPaymentDayOfMonth( command.getPaymentDayOfMonth() );
            entity.setCurrency( command.getCurrency() );
            entity.setBank( command.getBank() );
            entity.setBranch( command.getBranch() );
            entity.setProduct( command.getProduct() );
            entity.setBorrowers( command.getBorrowers() );
            entity.setRepaymentSchedule( command.getRepaymentSchedule() );
            entity.setPayments( command.getPayments() );
            entity.setCollateral( command.getCollateral() );
            entity.setFeeCharges( command.getFeeCharges() );
            entity.setLoanType( command.getLoanType() );
            entity.setRateType( command.getRateType() );
            entity.setCompounding( command.getCompounding() );
            entity.setStatus( command.getStatus() );

		// ------------------------------------------
		// persist an existing one
		// ------------------------------------------
		entity = projector.update(entity);

		LOGGER.info( "done saving of LoanAccount {0} ", entity.toString() );

		return entity;
	}

	/**
	 * Deletes the associatied value object
	 * @param		command DeleteLoanAccountCommand
	 */
	public void delete( DeleteLoanAccountCommand command ) {
		UUID id = null;

		// --------------------------------------
		// validate the command
		// --------------------------------------
		validator.validate( command );

		id = command.getLoanAccountId();

		// ------------------------------------------
		// delete the entity
		// ------------------------------------------
		projector.delete(id);

		LOGGER.info( "done deleting of LoanAccount {0} ", id );

	}

	/**
	 * Method to retrieve the LoanAccount via LoanAccountFetchOneSummary
	 * @param 	summary LoanAccountFetchOneSummary
	 * @return 	LoanAccountFetchOneResponse
	 */
	public LoanAccount getLoanAccount( LoanAccountFetchOneSummary summary ) {

		if( summary == null )
			throw new IllegalStateException( "LoanAccountFetchOneSummary arg cannot be null" );

		LoanAccount entity = null;
		UUID id = summary.getLoanAccountId();

		// --------------------------------------
		// validate the fetch one summary
		// --------------------------------------
		validator.validate( summary );

		// --------------------------------------
		// find a LoanAccount using the provided id
		// --------------------------------------
		entity = projector.find( id );

		return entity;
	}


	/**
	 * Method to retrieve a collection of all LoanAccounts
	 *
	 * @return 	List<LoanAccount>
	 */
    public List<LoanAccount> getAllLoanAccount() {
		List<LoanAccount> list = projector.findAll( new FindAllLoanAccountQuery() );
		return list;
	}

	/**
	 * assign Bank on LoanAccount
	 * @param		command AssignBankToLoanAccountCommand
	 */
	public void assignBank( AssignBankToLoanAccountCommand command ) {
		// --------------------------------------
		// best to validate the command now
		// --------------------------------------
		validator.validate( command );

		// --------------------------------------
		// delegate to the projector
		// --------------------------------------
		projector.assignBank(command.getLoanAccountId(), command.getAssignment());

	}

	/**
	 * unAssign Bank on LoanAccount
	 * @param		command UnAssignBankFromLoanAccountCommand
	 */
	public void unAssignBank( UnAssignBankFromLoanAccountCommand command ) {

		// --------------------------------------
		// validate the command
		// --------------------------------------
		validator.validate( command );

		// --------------------------------------
		// delegate to the projector
		// --------------------------------------
		projector.unAssignBank(command.getLoanAccountId());
	}
	
	/**
	 * assign Branch on LoanAccount
	 * @param		command AssignBranchToLoanAccountCommand
	 */
	public void assignBranch( AssignBranchToLoanAccountCommand command ) {
		// --------------------------------------
		// best to validate the command now
		// --------------------------------------
		validator.validate( command );

		// --------------------------------------
		// delegate to the projector
		// --------------------------------------
		projector.assignBranch(command.getLoanAccountId(), command.getAssignment());

	}

	/**
	 * unAssign Branch on LoanAccount
	 * @param		command UnAssignBranchFromLoanAccountCommand
	 */
	public void unAssignBranch( UnAssignBranchFromLoanAccountCommand command ) {

		// --------------------------------------
		// validate the command
		// --------------------------------------
		validator.validate( command );

		// --------------------------------------
		// delegate to the projector
		// --------------------------------------
		projector.unAssignBranch(command.getLoanAccountId());
	}
	
	/**
	 * assign Product on LoanAccount
	 * @param		command AssignProductToLoanAccountCommand
	 */
	public void assignProduct( AssignProductToLoanAccountCommand command ) {
		// --------------------------------------
		// best to validate the command now
		// --------------------------------------
		validator.validate( command );

		// --------------------------------------
		// delegate to the projector
		// --------------------------------------
		projector.assignProduct(command.getLoanAccountId(), command.getAssignment());

	}

	/**
	 * unAssign Product on LoanAccount
	 * @param		command UnAssignProductFromLoanAccountCommand
	 */
	public void unAssignProduct( UnAssignProductFromLoanAccountCommand command ) {

		// --------------------------------------
		// validate the command
		// --------------------------------------
		validator.validate( command );

		// --------------------------------------
		// delegate to the projector
		// --------------------------------------
		projector.unAssignProduct(command.getLoanAccountId());
	}
	

	/**
	 * add Customer to Borrowers
	 * @param		command AssignBorrowersToLoanAccountCommand
	 */
	public void addToBorrowers( AssignBorrowersToLoanAccountCommand command ) {

		// --------------------------------------
		// validate the command
		// --------------------------------------
		validator.validate( command );

		// --------------------------------------
		// delegate to the projector
		// --------------------------------------
		projector.addToBorrowers(command.getLoanAccountId(), command.getAddTo());
	}

	/**
	 * remove Customer from Borrowers
	 * @param		command RemoveBorrowersFromLoanAccountCommand
	 */
	public void removeFromBorrowers( RemoveBorrowersFromLoanAccountCommand command )  {
		// --------------------------------------
		// validate the command
		// --------------------------------------
		validator.validate( command );

		// --------------------------------------
		// delegate to the projector
		// --------------------------------------
		projector.removeFromBorrowers(command.getLoanAccountId(), command.getRemoveFrom());
	}

	/**
	 * add RepaymentSchedule to RepaymentSchedule
	 * @param		command AssignRepaymentScheduleToLoanAccountCommand
	 */
	public void addToRepaymentSchedule( AssignRepaymentScheduleToLoanAccountCommand command ) {

		// --------------------------------------
		// validate the command
		// --------------------------------------
		validator.validate( command );

		// --------------------------------------
		// delegate to the projector
		// --------------------------------------
		projector.addToRepaymentSchedule(command.getLoanAccountId(), command.getAddTo());
	}

	/**
	 * remove RepaymentSchedule from RepaymentSchedule
	 * @param		command RemoveRepaymentScheduleFromLoanAccountCommand
	 */
	public void removeFromRepaymentSchedule( RemoveRepaymentScheduleFromLoanAccountCommand command )  {
		// --------------------------------------
		// validate the command
		// --------------------------------------
		validator.validate( command );

		// --------------------------------------
		// delegate to the projector
		// --------------------------------------
		projector.removeFromRepaymentSchedule(command.getLoanAccountId(), command.getRemoveFrom());
	}

	/**
	 * add LoanPayment to Payments
	 * @param		command AssignPaymentsToLoanAccountCommand
	 */
	public void addToPayments( AssignPaymentsToLoanAccountCommand command ) {

		// --------------------------------------
		// validate the command
		// --------------------------------------
		validator.validate( command );

		// --------------------------------------
		// delegate to the projector
		// --------------------------------------
		projector.addToPayments(command.getLoanAccountId(), command.getAddTo());
	}

	/**
	 * remove LoanPayment from Payments
	 * @param		command RemovePaymentsFromLoanAccountCommand
	 */
	public void removeFromPayments( RemovePaymentsFromLoanAccountCommand command )  {
		// --------------------------------------
		// validate the command
		// --------------------------------------
		validator.validate( command );

		// --------------------------------------
		// delegate to the projector
		// --------------------------------------
		projector.removeFromPayments(command.getLoanAccountId(), command.getRemoveFrom());
	}

	/**
	 * add Collateral to Collateral
	 * @param		command AssignCollateralToLoanAccountCommand
	 */
	public void addToCollateral( AssignCollateralToLoanAccountCommand command ) {

		// --------------------------------------
		// validate the command
		// --------------------------------------
		validator.validate( command );

		// --------------------------------------
		// delegate to the projector
		// --------------------------------------
		projector.addToCollateral(command.getLoanAccountId(), command.getAddTo());
	}

	/**
	 * remove Collateral from Collateral
	 * @param		command RemoveCollateralFromLoanAccountCommand
	 */
	public void removeFromCollateral( RemoveCollateralFromLoanAccountCommand command )  {
		// --------------------------------------
		// validate the command
		// --------------------------------------
		validator.validate( command );

		// --------------------------------------
		// delegate to the projector
		// --------------------------------------
		projector.removeFromCollateral(command.getLoanAccountId(), command.getRemoveFrom());
	}

	/**
	 * add FeeCharge to FeeCharges
	 * @param		command AssignFeeChargesToLoanAccountCommand
	 */
	public void addToFeeCharges( AssignFeeChargesToLoanAccountCommand command ) {

		// --------------------------------------
		// validate the command
		// --------------------------------------
		validator.validate( command );

		// --------------------------------------
		// delegate to the projector
		// --------------------------------------
		projector.addToFeeCharges(command.getLoanAccountId(), command.getAddTo());
	}

	/**
	 * remove FeeCharge from FeeCharges
	 * @param		command RemoveFeeChargesFromLoanAccountCommand
	 */
	public void removeFromFeeCharges( RemoveFeeChargesFromLoanAccountCommand command )  {
		// --------------------------------------
		// validate the command
		// --------------------------------------
		validator.validate( command );

		// --------------------------------------
		// delegate to the projector
		// --------------------------------------
		projector.removeFromFeeCharges(command.getLoanAccountId(), command.getRemoveFrom());
	}




//************************************************************************
// Attributes
//************************************************************************
	@Autowired
    private final LoanAccountEntityProjector projector;
	private final LoanAccountValidator validator;
	private LoanAccount loanAccount 	= null;
	private CurrentIdentity identity			= null;
	private static final Logger LOGGER 			=  LoggerFactory.getLogger(LoanAccountService.class);
}
