/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Spring Boot 3.5
 *
 * Domain Model:
 * Banking Industry Domain Model
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone National Bank Confidential
 *
 * 2026 Turnstone National Bank
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone National Bank - General Release
 */
package com.harbormaster.service;

import java.io.IOException;
import java.util.*;
import java.util.concurrent.*;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import org.springframework.stereotype.Service;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.ApplicationContext;


import com.harbormaster.api.*;
import com.harbormaster.entity.*;
import com.harbormaster.exception.*;
import com.harbormaster.repository.*;
import com.harbormaster.validator.*;
import com.harbormaster.projector.*;
import com.harbormaster.security.*;

/**
 *
 * <h2>RiskAssessment business delegate</h2>
 *
 * <p>
 * This class implements the Business Delegate design pattern for the purpose of:
 * </p>
 * <ol>
 * <li>Reducing coupling between the business tier and a client of the business tier by hiding all business-tier implementation details</li>
 * <li>Improving the available of RiskAssessment related services in the case of a RiskAssessment business related service failing.</li>
 * <li>Exposes a simpler, uniform RiskAssessment interface to the business tier, making it easy for clients to consume a simple Java object.</li>
 * <li>Hides the communication protocol that may be required to fulfill RiskAssessment business related services.</li>
 * </ol>
 *
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Spring Boot 3.5</td></tr>
 *          <tr><td>published</td><td>09/08/2026</td></tr>
 *          <tr><td>design pattern</td><td>ServiceLayer</td></tr>
 *          <tr><td>architecture style</td><td>Layered</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>Banking Industry Domain Model</td></tr>
 *          <tr><td>description</td><td>HCIDL model capturing core banking, payments, lending, cards, KYC, and FX capabilities.</td></tr>
 *          <tr><td>industry</td><td>Banking</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Services</h3>
 *		<ul>
 * 		<li>QueryGateway</li>
 * 		<li>CommandGateway</li>
 *		<li>QueryUpdateEmitter</li>
 *		</ul>
 *
 * <h3>Produces</h3>
 *
 *      <p>application/json</p>
 *
 * <p>@author Harbormaster Dev Team</p>
 *
 */
@Service
public class RiskAssessmentService 
		extends BaseService {
//************************************************************************
// Public Methods
//************************************************************************
	/**
	 * Default Constructor
	 */
    public RiskAssessmentService(CurrentIdentity identity,
				ApplicationContext applicationContext)  {

		this.identity		= identity;
		this.projector 		= new RiskAssessmentEntityProjector( applicationContext.getBean(ProjectorRegistry.class),
										applicationContext.getBean(RiskAssessmentRepository.class) );
		this.validator		= applicationContext.getBean(RiskAssessmentValidator.class) ;
	}


	/**
	 * Creates the provided command.
	 *
	 * @param		command ${class.getCreateCommandAlias()}
	 * @return		RiskAssessment
	 */
		public RiskAssessment createRiskAssessment( CreateRiskAssessmentCommand command ) {

		RiskAssessment entity = new RiskAssessment();

		// --------------------------------------
		// validate the command
		// --------------------------------------
		validator.validate( command );

            entity.setRiskAssessmentId( command.getRiskAssessmentId() );
            entity.setScore( command.getScore() );
            entity.setAssessedOn( command.getAssessedOn() );
            entity.setRating( command.getRating() );

		// ------------------------------------------
		// persist a new one
		// ------------------------------------------
		entity = projector.create(entity);

		LOGGER.info( "done creating of RiskAssessment {0} ", entity.toString() );

		return entity;
	}

	/**
	 * Update the provided command.
	 * @param		command UpdateRiskAssessmentCommand
	 * @return		RiskAssessment
	 */
	public RiskAssessment updateRiskAssessment( UpdateRiskAssessmentCommand command ) {

		RiskAssessment entity = new RiskAssessment();

		// --------------------------------------
		// validate
		// --------------------------------------
		validator.validate( command );

            entity.setRiskAssessmentId( command.getRiskAssessmentId() );
            entity.setScore( command.getScore() );
            entity.setAssessedOn( command.getAssessedOn() );
            entity.setKycProfile( command.getKycProfile() );
            entity.setRating( command.getRating() );

		// ------------------------------------------
		// persist an existing one
		// ------------------------------------------
		entity = projector.update(entity);

		LOGGER.info( "done saving of RiskAssessment {0} ", entity.toString() );

		return entity;
	}

	/**
	 * Deletes the associatied value object
	 * @param		command DeleteRiskAssessmentCommand
	 */
	public void delete( DeleteRiskAssessmentCommand command ) {
		UUID id = null;

		// --------------------------------------
		// validate the command
		// --------------------------------------
		validator.validate( command );

		id = command.getRiskAssessmentId();

		// ------------------------------------------
		// delete the entity
		// ------------------------------------------
		projector.delete(id);

		LOGGER.info( "done deleting of RiskAssessment {0} ", id );

	}

	/**
	 * Method to retrieve the RiskAssessment via RiskAssessmentFetchOneSummary
	 * @param 	summary RiskAssessmentFetchOneSummary
	 * @return 	RiskAssessmentFetchOneResponse
	 */
	public RiskAssessment getRiskAssessment( RiskAssessmentFetchOneSummary summary ) {

		if( summary == null )
			throw new IllegalStateException( "RiskAssessmentFetchOneSummary arg cannot be null" );

		RiskAssessment entity = null;
		UUID id = summary.getRiskAssessmentId();

		// --------------------------------------
		// validate the fetch one summary
		// --------------------------------------
		validator.validate( summary );

		// --------------------------------------
		// find a RiskAssessment using the provided id
		// --------------------------------------
		entity = projector.find( id );

		return entity;
	}


	/**
	 * Method to retrieve a collection of all RiskAssessments
	 *
	 * @return 	List<RiskAssessment>
	 */
    public List<RiskAssessment> getAllRiskAssessment() {
		List<RiskAssessment> list = projector.findAll( new FindAllRiskAssessmentQuery() );
		return list;
	}

	/**
	 * assign KycProfile on RiskAssessment
	 * @param		command AssignKycProfileToRiskAssessmentCommand
	 */
	public void assignKycProfile( AssignKycProfileToRiskAssessmentCommand command ) {
		// --------------------------------------
		// best to validate the command now
		// --------------------------------------
		validator.validate( command );

		// --------------------------------------
		// delegate to the projector
		// --------------------------------------
		projector.assignKycProfile(command.getRiskAssessmentId(), command.getAssignment());

	}

	/**
	 * unAssign KycProfile on RiskAssessment
	 * @param		command UnAssignKycProfileFromRiskAssessmentCommand
	 */
	public void unAssignKycProfile( UnAssignKycProfileFromRiskAssessmentCommand command ) {

		// --------------------------------------
		// validate the command
		// --------------------------------------
		validator.validate( command );

		// --------------------------------------
		// delegate to the projector
		// --------------------------------------
		projector.unAssignKycProfile(command.getRiskAssessmentId());
	}
	




//************************************************************************
// Attributes
//************************************************************************
	@Autowired
    private final RiskAssessmentEntityProjector projector;
	private final RiskAssessmentValidator validator;
	private RiskAssessment riskAssessment 	= null;
	private CurrentIdentity identity			= null;
	private static final Logger LOGGER 			=  LoggerFactory.getLogger(RiskAssessmentService.class);
}
