/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Spring Boot 3.5
 *
 * Domain Model:
 * Banking Industry Domain Model
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone National Bank Confidential
 *
 * 2026 Turnstone National Bank
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone National Bank - General Release
 */
package com.harbormaster.service;

import java.io.IOException;
import java.util.*;
import java.util.concurrent.*;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import org.springframework.stereotype.Service;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.ApplicationContext;


import com.harbormaster.api.*;
import com.harbormaster.entity.*;
import com.harbormaster.exception.*;
import com.harbormaster.repository.*;
import com.harbormaster.validator.*;
import com.harbormaster.projector.*;
import com.harbormaster.security.*;

/**
 *
 * <h2>ScreeningResult business delegate</h2>
 *
 * <p>
 * This class implements the Business Delegate design pattern for the purpose of:
 * </p>
 * <ol>
 * <li>Reducing coupling between the business tier and a client of the business tier by hiding all business-tier implementation details</li>
 * <li>Improving the available of ScreeningResult related services in the case of a ScreeningResult business related service failing.</li>
 * <li>Exposes a simpler, uniform ScreeningResult interface to the business tier, making it easy for clients to consume a simple Java object.</li>
 * <li>Hides the communication protocol that may be required to fulfill ScreeningResult business related services.</li>
 * </ol>
 *
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Spring Boot 3.5</td></tr>
 *          <tr><td>published</td><td>09/08/2026</td></tr>
 *          <tr><td>design pattern</td><td>ServiceLayer</td></tr>
 *          <tr><td>architecture style</td><td>Layered</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>Banking Industry Domain Model</td></tr>
 *          <tr><td>description</td><td>HCIDL model capturing core banking, payments, lending, cards, KYC, and FX capabilities.</td></tr>
 *          <tr><td>industry</td><td>Banking</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Services</h3>
 *		<ul>
 * 		<li>QueryGateway</li>
 * 		<li>CommandGateway</li>
 *		<li>QueryUpdateEmitter</li>
 *		</ul>
 *
 * <h3>Produces</h3>
 *
 *      <p>application/json</p>
 *
 * <p>@author Harbormaster Dev Team</p>
 *
 */
@Service
public class ScreeningResultService 
		extends BaseService {
//************************************************************************
// Public Methods
//************************************************************************
	/**
	 * Default Constructor
	 */
    public ScreeningResultService(CurrentIdentity identity,
				ApplicationContext applicationContext)  {

		this.identity		= identity;
		this.projector 		= new ScreeningResultEntityProjector( applicationContext.getBean(ProjectorRegistry.class),
										applicationContext.getBean(ScreeningResultRepository.class) );
		this.validator		= applicationContext.getBean(ScreeningResultValidator.class) ;
	}


	/**
	 * Creates the provided command.
	 *
	 * @param		command ${class.getCreateCommandAlias()}
	 * @return		ScreeningResult
	 */
		public ScreeningResult createScreeningResult( CreateScreeningResultCommand command ) {

		ScreeningResult entity = new ScreeningResult();

		// --------------------------------------
		// validate the command
		// --------------------------------------
		validator.validate( command );

            entity.setScreeningResultId( command.getScreeningResultId() );
            entity.setScreeningDate( command.getScreeningDate() );
            entity.setProvider( command.getProvider() );
            entity.setOutcome( command.getOutcome() );

		// ------------------------------------------
		// persist a new one
		// ------------------------------------------
		entity = projector.create(entity);

		LOGGER.info( "done creating of ScreeningResult {0} ", entity.toString() );

		return entity;
	}

	/**
	 * Update the provided command.
	 * @param		command UpdateScreeningResultCommand
	 * @return		ScreeningResult
	 */
	public ScreeningResult updateScreeningResult( UpdateScreeningResultCommand command ) {

		ScreeningResult entity = new ScreeningResult();

		// --------------------------------------
		// validate
		// --------------------------------------
		validator.validate( command );

            entity.setScreeningResultId( command.getScreeningResultId() );
            entity.setScreeningDate( command.getScreeningDate() );
            entity.setProvider( command.getProvider() );
            entity.setKycProfile( command.getKycProfile() );
            entity.setOutcome( command.getOutcome() );

		// ------------------------------------------
		// persist an existing one
		// ------------------------------------------
		entity = projector.update(entity);

		LOGGER.info( "done saving of ScreeningResult {0} ", entity.toString() );

		return entity;
	}

	/**
	 * Deletes the associatied value object
	 * @param		command DeleteScreeningResultCommand
	 */
	public void delete( DeleteScreeningResultCommand command ) {
		UUID id = null;

		// --------------------------------------
		// validate the command
		// --------------------------------------
		validator.validate( command );

		id = command.getScreeningResultId();

		// ------------------------------------------
		// delete the entity
		// ------------------------------------------
		projector.delete(id);

		LOGGER.info( "done deleting of ScreeningResult {0} ", id );

	}

	/**
	 * Method to retrieve the ScreeningResult via ScreeningResultFetchOneSummary
	 * @param 	summary ScreeningResultFetchOneSummary
	 * @return 	ScreeningResultFetchOneResponse
	 */
	public ScreeningResult getScreeningResult( ScreeningResultFetchOneSummary summary ) {

		if( summary == null )
			throw new IllegalStateException( "ScreeningResultFetchOneSummary arg cannot be null" );

		ScreeningResult entity = null;
		UUID id = summary.getScreeningResultId();

		// --------------------------------------
		// validate the fetch one summary
		// --------------------------------------
		validator.validate( summary );

		// --------------------------------------
		// find a ScreeningResult using the provided id
		// --------------------------------------
		entity = projector.find( id );

		return entity;
	}


	/**
	 * Method to retrieve a collection of all ScreeningResults
	 *
	 * @return 	List<ScreeningResult>
	 */
    public List<ScreeningResult> getAllScreeningResult() {
		List<ScreeningResult> list = projector.findAll( new FindAllScreeningResultQuery() );
		return list;
	}

	/**
	 * assign KycProfile on ScreeningResult
	 * @param		command AssignKycProfileToScreeningResultCommand
	 */
	public void assignKycProfile( AssignKycProfileToScreeningResultCommand command ) {
		// --------------------------------------
		// best to validate the command now
		// --------------------------------------
		validator.validate( command );

		// --------------------------------------
		// delegate to the projector
		// --------------------------------------
		projector.assignKycProfile(command.getScreeningResultId(), command.getAssignment());

	}

	/**
	 * unAssign KycProfile on ScreeningResult
	 * @param		command UnAssignKycProfileFromScreeningResultCommand
	 */
	public void unAssignKycProfile( UnAssignKycProfileFromScreeningResultCommand command ) {

		// --------------------------------------
		// validate the command
		// --------------------------------------
		validator.validate( command );

		// --------------------------------------
		// delegate to the projector
		// --------------------------------------
		projector.unAssignKycProfile(command.getScreeningResultId());
	}
	




//************************************************************************
// Attributes
//************************************************************************
	@Autowired
    private final ScreeningResultEntityProjector projector;
	private final ScreeningResultValidator validator;
	private ScreeningResult screeningResult 	= null;
	private CurrentIdentity identity			= null;
	private static final Logger LOGGER 			=  LoggerFactory.getLogger(ScreeningResultService.class);
}
