/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Spring Boot 3.5
 *
 * Domain Model:
 * Banking Industry Domain Model
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone National Bank Confidential
 *
 * 2026 Turnstone National Bank
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone National Bank - General Release
 */
package com.harbormaster.service;

import java.io.IOException;
import java.util.*;
import java.util.concurrent.*;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import org.springframework.stereotype.Service;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.ApplicationContext;


import com.harbormaster.api.*;
import com.harbormaster.entity.*;
import com.harbormaster.exception.*;
import com.harbormaster.repository.*;
import com.harbormaster.validator.*;
import com.harbormaster.projector.*;
import com.harbormaster.security.*;

/**
 *
 * <h2>StandingInstruction business delegate</h2>
 *
 * <p>
 * This class implements the Business Delegate design pattern for the purpose of:
 * </p>
 * <ol>
 * <li>Reducing coupling between the business tier and a client of the business tier by hiding all business-tier implementation details</li>
 * <li>Improving the available of StandingInstruction related services in the case of a StandingInstruction business related service failing.</li>
 * <li>Exposes a simpler, uniform StandingInstruction interface to the business tier, making it easy for clients to consume a simple Java object.</li>
 * <li>Hides the communication protocol that may be required to fulfill StandingInstruction business related services.</li>
 * </ol>
 *
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Spring Boot 3.5</td></tr>
 *          <tr><td>published</td><td>09/08/2026</td></tr>
 *          <tr><td>design pattern</td><td>ServiceLayer</td></tr>
 *          <tr><td>architecture style</td><td>Layered</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>Banking Industry Domain Model</td></tr>
 *          <tr><td>description</td><td>HCIDL model capturing core banking, payments, lending, cards, KYC, and FX capabilities.</td></tr>
 *          <tr><td>industry</td><td>Banking</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Services</h3>
 *		<ul>
 * 		<li>QueryGateway</li>
 * 		<li>CommandGateway</li>
 *		<li>QueryUpdateEmitter</li>
 *		</ul>
 *
 * <h3>Produces</h3>
 *
 *      <p>application/json</p>
 *
 * <p>@author Harbormaster Dev Team</p>
 *
 */
@Service
public class StandingInstructionService 
		extends BaseService {
//************************************************************************
// Public Methods
//************************************************************************
	/**
	 * Default Constructor
	 */
    public StandingInstructionService(CurrentIdentity identity,
				ApplicationContext applicationContext)  {

		this.identity		= identity;
		this.projector 		= new StandingInstructionEntityProjector( applicationContext.getBean(ProjectorRegistry.class),
										applicationContext.getBean(StandingInstructionRepository.class) );
		this.validator		= applicationContext.getBean(StandingInstructionValidator.class) ;
	}


	/**
	 * Creates the provided command.
	 *
	 * @param		command ${class.getCreateCommandAlias()}
	 * @return		StandingInstruction
	 */
		public StandingInstruction createStandingInstruction( CreateStandingInstructionCommand command ) {

		StandingInstruction entity = new StandingInstruction();

		// --------------------------------------
		// validate the command
		// --------------------------------------
		validator.validate( command );

            entity.setStandingInstructionId( command.getStandingInstructionId() );
            entity.setInstructionId( command.getInstructionId() );
            entity.setAmount( command.getAmount() );
            entity.setNextExecutionDate( command.getNextExecutionDate() );
            entity.setFrequency( command.getFrequency() );
            entity.setStatus( command.getStatus() );

		// ------------------------------------------
		// persist a new one
		// ------------------------------------------
		entity = projector.create(entity);

		LOGGER.info( "done creating of StandingInstruction {0} ", entity.toString() );

		return entity;
	}

	/**
	 * Update the provided command.
	 * @param		command UpdateStandingInstructionCommand
	 * @return		StandingInstruction
	 */
	public StandingInstruction updateStandingInstruction( UpdateStandingInstructionCommand command ) {

		StandingInstruction entity = new StandingInstruction();

		// --------------------------------------
		// validate
		// --------------------------------------
		validator.validate( command );

            entity.setStandingInstructionId( command.getStandingInstructionId() );
            entity.setInstructionId( command.getInstructionId() );
            entity.setAmount( command.getAmount() );
            entity.setNextExecutionDate( command.getNextExecutionDate() );
            entity.setAccount( command.getAccount() );
            entity.setBeneficiary( command.getBeneficiary() );
            entity.setFrequency( command.getFrequency() );
            entity.setStatus( command.getStatus() );

		// ------------------------------------------
		// persist an existing one
		// ------------------------------------------
		entity = projector.update(entity);

		LOGGER.info( "done saving of StandingInstruction {0} ", entity.toString() );

		return entity;
	}

	/**
	 * Deletes the associatied value object
	 * @param		command DeleteStandingInstructionCommand
	 */
	public void delete( DeleteStandingInstructionCommand command ) {
		UUID id = null;

		// --------------------------------------
		// validate the command
		// --------------------------------------
		validator.validate( command );

		id = command.getStandingInstructionId();

		// ------------------------------------------
		// delete the entity
		// ------------------------------------------
		projector.delete(id);

		LOGGER.info( "done deleting of StandingInstruction {0} ", id );

	}

	/**
	 * Method to retrieve the StandingInstruction via StandingInstructionFetchOneSummary
	 * @param 	summary StandingInstructionFetchOneSummary
	 * @return 	StandingInstructionFetchOneResponse
	 */
	public StandingInstruction getStandingInstruction( StandingInstructionFetchOneSummary summary ) {

		if( summary == null )
			throw new IllegalStateException( "StandingInstructionFetchOneSummary arg cannot be null" );

		StandingInstruction entity = null;
		UUID id = summary.getStandingInstructionId();

		// --------------------------------------
		// validate the fetch one summary
		// --------------------------------------
		validator.validate( summary );

		// --------------------------------------
		// find a StandingInstruction using the provided id
		// --------------------------------------
		entity = projector.find( id );

		return entity;
	}


	/**
	 * Method to retrieve a collection of all StandingInstructions
	 *
	 * @return 	List<StandingInstruction>
	 */
    public List<StandingInstruction> getAllStandingInstruction() {
		List<StandingInstruction> list = projector.findAll( new FindAllStandingInstructionQuery() );
		return list;
	}

	/**
	 * assign Account on StandingInstruction
	 * @param		command AssignAccountToStandingInstructionCommand
	 */
	public void assignAccount( AssignAccountToStandingInstructionCommand command ) {
		// --------------------------------------
		// best to validate the command now
		// --------------------------------------
		validator.validate( command );

		// --------------------------------------
		// delegate to the projector
		// --------------------------------------
		projector.assignAccount(command.getStandingInstructionId(), command.getAssignment());

	}

	/**
	 * unAssign Account on StandingInstruction
	 * @param		command UnAssignAccountFromStandingInstructionCommand
	 */
	public void unAssignAccount( UnAssignAccountFromStandingInstructionCommand command ) {

		// --------------------------------------
		// validate the command
		// --------------------------------------
		validator.validate( command );

		// --------------------------------------
		// delegate to the projector
		// --------------------------------------
		projector.unAssignAccount(command.getStandingInstructionId());
	}
	
	/**
	 * assign Beneficiary on StandingInstruction
	 * @param		command AssignBeneficiaryToStandingInstructionCommand
	 */
	public void assignBeneficiary( AssignBeneficiaryToStandingInstructionCommand command ) {
		// --------------------------------------
		// best to validate the command now
		// --------------------------------------
		validator.validate( command );

		// --------------------------------------
		// delegate to the projector
		// --------------------------------------
		projector.assignBeneficiary(command.getStandingInstructionId(), command.getAssignment());

	}

	/**
	 * unAssign Beneficiary on StandingInstruction
	 * @param		command UnAssignBeneficiaryFromStandingInstructionCommand
	 */
	public void unAssignBeneficiary( UnAssignBeneficiaryFromStandingInstructionCommand command ) {

		// --------------------------------------
		// validate the command
		// --------------------------------------
		validator.validate( command );

		// --------------------------------------
		// delegate to the projector
		// --------------------------------------
		projector.unAssignBeneficiary(command.getStandingInstructionId());
	}
	




//************************************************************************
// Attributes
//************************************************************************
	@Autowired
    private final StandingInstructionEntityProjector projector;
	private final StandingInstructionValidator validator;
	private StandingInstruction standingInstruction 	= null;
	private CurrentIdentity identity			= null;
	private static final Logger LOGGER 			=  LoggerFactory.getLogger(StandingInstructionService.class);
}
