/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Spring Boot 3.5
 *
 * Domain Model:
 * Banking Industry Domain Model
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone National Bank Confidential
 *
 * 2026 Turnstone National Bank
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone National Bank - General Release
 */
package com.harbormaster.service;

import java.io.IOException;
import java.util.*;
import java.util.concurrent.*;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import org.springframework.stereotype.Service;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.ApplicationContext;


import com.harbormaster.api.*;
import com.harbormaster.entity.*;
import com.harbormaster.exception.*;
import com.harbormaster.repository.*;
import com.harbormaster.validator.*;
import com.harbormaster.projector.*;
import com.harbormaster.security.*;

/**
 *
 * <h2>ThirdPartyProvider business delegate</h2>
 *
 * <p>
 * This class implements the Business Delegate design pattern for the purpose of:
 * </p>
 * <ol>
 * <li>Reducing coupling between the business tier and a client of the business tier by hiding all business-tier implementation details</li>
 * <li>Improving the available of ThirdPartyProvider related services in the case of a ThirdPartyProvider business related service failing.</li>
 * <li>Exposes a simpler, uniform ThirdPartyProvider interface to the business tier, making it easy for clients to consume a simple Java object.</li>
 * <li>Hides the communication protocol that may be required to fulfill ThirdPartyProvider business related services.</li>
 * </ol>
 *
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Spring Boot 3.5</td></tr>
 *          <tr><td>published</td><td>09/08/2026</td></tr>
 *          <tr><td>design pattern</td><td>ServiceLayer</td></tr>
 *          <tr><td>architecture style</td><td>Layered</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>Banking Industry Domain Model</td></tr>
 *          <tr><td>description</td><td>HCIDL model capturing core banking, payments, lending, cards, KYC, and FX capabilities.</td></tr>
 *          <tr><td>industry</td><td>Banking</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Services</h3>
 *		<ul>
 * 		<li>QueryGateway</li>
 * 		<li>CommandGateway</li>
 *		<li>QueryUpdateEmitter</li>
 *		</ul>
 *
 * <h3>Produces</h3>
 *
 *      <p>application/json</p>
 *
 * <p>@author Harbormaster Dev Team</p>
 *
 */
@Service
public class ThirdPartyProviderService 
		extends BaseService {
//************************************************************************
// Public Methods
//************************************************************************
	/**
	 * Default Constructor
	 */
    public ThirdPartyProviderService(CurrentIdentity identity,
				ApplicationContext applicationContext)  {

		this.identity		= identity;
		this.projector 		= new ThirdPartyProviderEntityProjector( applicationContext.getBean(ProjectorRegistry.class),
										applicationContext.getBean(ThirdPartyProviderRepository.class) );
		this.validator		= applicationContext.getBean(ThirdPartyProviderValidator.class) ;
	}


	/**
	 * Creates the provided command.
	 *
	 * @param		command ${class.getCreateCommandAlias()}
	 * @return		ThirdPartyProvider
	 */
		public ThirdPartyProvider createThirdPartyProvider( CreateThirdPartyProviderCommand command ) {

		ThirdPartyProvider entity = new ThirdPartyProvider();

		// --------------------------------------
		// validate the command
		// --------------------------------------
		validator.validate( command );

            entity.setThirdPartyProviderId( command.getThirdPartyProviderId() );
            entity.setName( command.getName() );
            entity.setRegistrationId( command.getRegistrationId() );
            entity.setWebsite( command.getWebsite() );

		// ------------------------------------------
		// persist a new one
		// ------------------------------------------
		entity = projector.create(entity);

		LOGGER.info( "done creating of ThirdPartyProvider {0} ", entity.toString() );

		return entity;
	}

	/**
	 * Update the provided command.
	 * @param		command UpdateThirdPartyProviderCommand
	 * @return		ThirdPartyProvider
	 */
	public ThirdPartyProvider updateThirdPartyProvider( UpdateThirdPartyProviderCommand command ) {

		ThirdPartyProvider entity = new ThirdPartyProvider();

		// --------------------------------------
		// validate
		// --------------------------------------
		validator.validate( command );

            entity.setThirdPartyProviderId( command.getThirdPartyProviderId() );
            entity.setName( command.getName() );
            entity.setRegistrationId( command.getRegistrationId() );
            entity.setWebsite( command.getWebsite() );
            entity.setBank( command.getBank() );
            entity.setConsents( command.getConsents() );

		// ------------------------------------------
		// persist an existing one
		// ------------------------------------------
		entity = projector.update(entity);

		LOGGER.info( "done saving of ThirdPartyProvider {0} ", entity.toString() );

		return entity;
	}

	/**
	 * Deletes the associatied value object
	 * @param		command DeleteThirdPartyProviderCommand
	 */
	public void delete( DeleteThirdPartyProviderCommand command ) {
		UUID id = null;

		// --------------------------------------
		// validate the command
		// --------------------------------------
		validator.validate( command );

		id = command.getThirdPartyProviderId();

		// ------------------------------------------
		// delete the entity
		// ------------------------------------------
		projector.delete(id);

		LOGGER.info( "done deleting of ThirdPartyProvider {0} ", id );

	}

	/**
	 * Method to retrieve the ThirdPartyProvider via ThirdPartyProviderFetchOneSummary
	 * @param 	summary ThirdPartyProviderFetchOneSummary
	 * @return 	ThirdPartyProviderFetchOneResponse
	 */
	public ThirdPartyProvider getThirdPartyProvider( ThirdPartyProviderFetchOneSummary summary ) {

		if( summary == null )
			throw new IllegalStateException( "ThirdPartyProviderFetchOneSummary arg cannot be null" );

		ThirdPartyProvider entity = null;
		UUID id = summary.getThirdPartyProviderId();

		// --------------------------------------
		// validate the fetch one summary
		// --------------------------------------
		validator.validate( summary );

		// --------------------------------------
		// find a ThirdPartyProvider using the provided id
		// --------------------------------------
		entity = projector.find( id );

		return entity;
	}


	/**
	 * Method to retrieve a collection of all ThirdPartyProviders
	 *
	 * @return 	List<ThirdPartyProvider>
	 */
    public List<ThirdPartyProvider> getAllThirdPartyProvider() {
		List<ThirdPartyProvider> list = projector.findAll( new FindAllThirdPartyProviderQuery() );
		return list;
	}

	/**
	 * assign Bank on ThirdPartyProvider
	 * @param		command AssignBankToThirdPartyProviderCommand
	 */
	public void assignBank( AssignBankToThirdPartyProviderCommand command ) {
		// --------------------------------------
		// best to validate the command now
		// --------------------------------------
		validator.validate( command );

		// --------------------------------------
		// delegate to the projector
		// --------------------------------------
		projector.assignBank(command.getThirdPartyProviderId(), command.getAssignment());

	}

	/**
	 * unAssign Bank on ThirdPartyProvider
	 * @param		command UnAssignBankFromThirdPartyProviderCommand
	 */
	public void unAssignBank( UnAssignBankFromThirdPartyProviderCommand command ) {

		// --------------------------------------
		// validate the command
		// --------------------------------------
		validator.validate( command );

		// --------------------------------------
		// delegate to the projector
		// --------------------------------------
		projector.unAssignBank(command.getThirdPartyProviderId());
	}
	

	/**
	 * add Consent to Consents
	 * @param		command AssignConsentsToThirdPartyProviderCommand
	 */
	public void addToConsents( AssignConsentsToThirdPartyProviderCommand command ) {

		// --------------------------------------
		// validate the command
		// --------------------------------------
		validator.validate( command );

		// --------------------------------------
		// delegate to the projector
		// --------------------------------------
		projector.addToConsents(command.getThirdPartyProviderId(), command.getAddTo());
	}

	/**
	 * remove Consent from Consents
	 * @param		command RemoveConsentsFromThirdPartyProviderCommand
	 */
	public void removeFromConsents( RemoveConsentsFromThirdPartyProviderCommand command )  {
		// --------------------------------------
		// validate the command
		// --------------------------------------
		validator.validate( command );

		// --------------------------------------
		// delegate to the projector
		// --------------------------------------
		projector.removeFromConsents(command.getThirdPartyProviderId(), command.getRemoveFrom());
	}




//************************************************************************
// Attributes
//************************************************************************
	@Autowired
    private final ThirdPartyProviderEntityProjector projector;
	private final ThirdPartyProviderValidator validator;
	private ThirdPartyProvider thirdPartyProvider 	= null;
	private CurrentIdentity identity			= null;
	private static final Logger LOGGER 			=  LoggerFactory.getLogger(ThirdPartyProviderService.class);
}
