/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Spring Boot 3.5
 *
 * Domain Model:
 * Banking Industry Domain Model
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone National Bank Confidential
 *
 * 2026 Turnstone National Bank
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone National Bank - General Release
 */
package com.harbormaster.service;

import java.io.IOException;
import java.util.*;
import java.util.concurrent.*;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import org.springframework.stereotype.Service;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.ApplicationContext;


import com.harbormaster.api.*;
import com.harbormaster.entity.*;
import com.harbormaster.exception.*;
import com.harbormaster.repository.*;
import com.harbormaster.validator.*;
import com.harbormaster.projector.*;
import com.harbormaster.security.*;

/**
 *
 * <h2>Transaction business delegate</h2>
 *
 * <p>
 * This class implements the Business Delegate design pattern for the purpose of:
 * </p>
 * <ol>
 * <li>Reducing coupling between the business tier and a client of the business tier by hiding all business-tier implementation details</li>
 * <li>Improving the available of Transaction related services in the case of a Transaction business related service failing.</li>
 * <li>Exposes a simpler, uniform Transaction interface to the business tier, making it easy for clients to consume a simple Java object.</li>
 * <li>Hides the communication protocol that may be required to fulfill Transaction business related services.</li>
 * </ol>
 *
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Spring Boot 3.5</td></tr>
 *          <tr><td>published</td><td>09/08/2026</td></tr>
 *          <tr><td>design pattern</td><td>ServiceLayer</td></tr>
 *          <tr><td>architecture style</td><td>Layered</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>Banking Industry Domain Model</td></tr>
 *          <tr><td>description</td><td>HCIDL model capturing core banking, payments, lending, cards, KYC, and FX capabilities.</td></tr>
 *          <tr><td>industry</td><td>Banking</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Services</h3>
 *		<ul>
 * 		<li>QueryGateway</li>
 * 		<li>CommandGateway</li>
 *		<li>QueryUpdateEmitter</li>
 *		</ul>
 *
 * <h3>Produces</h3>
 *
 *      <p>application/json</p>
 *
 * <p>@author Harbormaster Dev Team</p>
 *
 */
@Service
public class TransactionService 
		extends BaseService {
//************************************************************************
// Public Methods
//************************************************************************
	/**
	 * Default Constructor
	 */
    public TransactionService(CurrentIdentity identity,
				ApplicationContext applicationContext)  {

		this.identity		= identity;
		this.projector 		= new TransactionEntityProjector( applicationContext.getBean(ProjectorRegistry.class),
										applicationContext.getBean(TransactionRepository.class) );
		this.validator		= applicationContext.getBean(TransactionValidator.class) ;
	}


	/**
	 * Creates the provided command.
	 *
	 * @param		command ${class.getCreateCommandAlias()}
	 * @return		Transaction
	 */
		public Transaction createTransaction( CreateTransactionCommand command ) {

		Transaction entity = new Transaction();

		// --------------------------------------
		// validate the command
		// --------------------------------------
		validator.validate( command );

            entity.setTransactionId( command.getTransactionId() );
            entity.setBookingDate( command.getBookingDate() );
            entity.setValueDate( command.getValueDate() );
            entity.setAmount( command.getAmount() );
            entity.setDescription( command.getDescription() );
            entity.setDirection( command.getDirection() );
            entity.setTransactionType( command.getTransactionType() );
            entity.setStatus( command.getStatus() );
            entity.setChannel( command.getChannel() );

		// ------------------------------------------
		// persist a new one
		// ------------------------------------------
		entity = projector.create(entity);

		LOGGER.info( "done creating of Transaction {0} ", entity.toString() );

		return entity;
	}

	/**
	 * Update the provided command.
	 * @param		command UpdateTransactionCommand
	 * @return		Transaction
	 */
	public Transaction updateTransaction( UpdateTransactionCommand command ) {

		Transaction entity = new Transaction();

		// --------------------------------------
		// validate
		// --------------------------------------
		validator.validate( command );

            entity.setTransactionId( command.getTransactionId() );
            entity.setBookingDate( command.getBookingDate() );
            entity.setValueDate( command.getValueDate() );
            entity.setAmount( command.getAmount() );
            entity.setDescription( command.getDescription() );
            entity.setAccount( command.getAccount() );
            entity.setExternalCounterparty( command.getExternalCounterparty() );
            entity.setPaymentCard( command.getPaymentCard() );
            entity.setFundsTransfer( command.getFundsTransfer() );
            entity.setFxTrade( command.getFxTrade() );
            entity.setDispute( command.getDispute() );
            entity.setDirection( command.getDirection() );
            entity.setTransactionType( command.getTransactionType() );
            entity.setStatus( command.getStatus() );
            entity.setChannel( command.getChannel() );

		// ------------------------------------------
		// persist an existing one
		// ------------------------------------------
		entity = projector.update(entity);

		LOGGER.info( "done saving of Transaction {0} ", entity.toString() );

		return entity;
	}

	/**
	 * Deletes the associatied value object
	 * @param		command DeleteTransactionCommand
	 */
	public void delete( DeleteTransactionCommand command ) {
		UUID id = null;

		// --------------------------------------
		// validate the command
		// --------------------------------------
		validator.validate( command );

		id = command.getTransactionId();

		// ------------------------------------------
		// delete the entity
		// ------------------------------------------
		projector.delete(id);

		LOGGER.info( "done deleting of Transaction {0} ", id );

	}

	/**
	 * Method to retrieve the Transaction via TransactionFetchOneSummary
	 * @param 	summary TransactionFetchOneSummary
	 * @return 	TransactionFetchOneResponse
	 */
	public Transaction getTransaction( TransactionFetchOneSummary summary ) {

		if( summary == null )
			throw new IllegalStateException( "TransactionFetchOneSummary arg cannot be null" );

		Transaction entity = null;
		UUID id = summary.getTransactionId();

		// --------------------------------------
		// validate the fetch one summary
		// --------------------------------------
		validator.validate( summary );

		// --------------------------------------
		// find a Transaction using the provided id
		// --------------------------------------
		entity = projector.find( id );

		return entity;
	}


	/**
	 * Method to retrieve a collection of all Transactions
	 *
	 * @return 	List<Transaction>
	 */
    public List<Transaction> getAllTransaction() {
		List<Transaction> list = projector.findAll( new FindAllTransactionQuery() );
		return list;
	}

	/**
	 * assign Account on Transaction
	 * @param		command AssignAccountToTransactionCommand
	 */
	public void assignAccount( AssignAccountToTransactionCommand command ) {
		// --------------------------------------
		// best to validate the command now
		// --------------------------------------
		validator.validate( command );

		// --------------------------------------
		// delegate to the projector
		// --------------------------------------
		projector.assignAccount(command.getTransactionId(), command.getAssignment());

	}

	/**
	 * unAssign Account on Transaction
	 * @param		command UnAssignAccountFromTransactionCommand
	 */
	public void unAssignAccount( UnAssignAccountFromTransactionCommand command ) {

		// --------------------------------------
		// validate the command
		// --------------------------------------
		validator.validate( command );

		// --------------------------------------
		// delegate to the projector
		// --------------------------------------
		projector.unAssignAccount(command.getTransactionId());
	}
	
	/**
	 * assign ExternalCounterparty on Transaction
	 * @param		command AssignExternalCounterpartyToTransactionCommand
	 */
	public void assignExternalCounterparty( AssignExternalCounterpartyToTransactionCommand command ) {
		// --------------------------------------
		// best to validate the command now
		// --------------------------------------
		validator.validate( command );

		// --------------------------------------
		// delegate to the projector
		// --------------------------------------
		projector.assignExternalCounterparty(command.getTransactionId(), command.getAssignment());

	}

	/**
	 * unAssign ExternalCounterparty on Transaction
	 * @param		command UnAssignExternalCounterpartyFromTransactionCommand
	 */
	public void unAssignExternalCounterparty( UnAssignExternalCounterpartyFromTransactionCommand command ) {

		// --------------------------------------
		// validate the command
		// --------------------------------------
		validator.validate( command );

		// --------------------------------------
		// delegate to the projector
		// --------------------------------------
		projector.unAssignExternalCounterparty(command.getTransactionId());
	}
	
	/**
	 * assign PaymentCard on Transaction
	 * @param		command AssignPaymentCardToTransactionCommand
	 */
	public void assignPaymentCard( AssignPaymentCardToTransactionCommand command ) {
		// --------------------------------------
		// best to validate the command now
		// --------------------------------------
		validator.validate( command );

		// --------------------------------------
		// delegate to the projector
		// --------------------------------------
		projector.assignPaymentCard(command.getTransactionId(), command.getAssignment());

	}

	/**
	 * unAssign PaymentCard on Transaction
	 * @param		command UnAssignPaymentCardFromTransactionCommand
	 */
	public void unAssignPaymentCard( UnAssignPaymentCardFromTransactionCommand command ) {

		// --------------------------------------
		// validate the command
		// --------------------------------------
		validator.validate( command );

		// --------------------------------------
		// delegate to the projector
		// --------------------------------------
		projector.unAssignPaymentCard(command.getTransactionId());
	}
	
	/**
	 * assign FundsTransfer on Transaction
	 * @param		command AssignFundsTransferToTransactionCommand
	 */
	public void assignFundsTransfer( AssignFundsTransferToTransactionCommand command ) {
		// --------------------------------------
		// best to validate the command now
		// --------------------------------------
		validator.validate( command );

		// --------------------------------------
		// delegate to the projector
		// --------------------------------------
		projector.assignFundsTransfer(command.getTransactionId(), command.getAssignment());

	}

	/**
	 * unAssign FundsTransfer on Transaction
	 * @param		command UnAssignFundsTransferFromTransactionCommand
	 */
	public void unAssignFundsTransfer( UnAssignFundsTransferFromTransactionCommand command ) {

		// --------------------------------------
		// validate the command
		// --------------------------------------
		validator.validate( command );

		// --------------------------------------
		// delegate to the projector
		// --------------------------------------
		projector.unAssignFundsTransfer(command.getTransactionId());
	}
	
	/**
	 * assign FxTrade on Transaction
	 * @param		command AssignFxTradeToTransactionCommand
	 */
	public void assignFxTrade( AssignFxTradeToTransactionCommand command ) {
		// --------------------------------------
		// best to validate the command now
		// --------------------------------------
		validator.validate( command );

		// --------------------------------------
		// delegate to the projector
		// --------------------------------------
		projector.assignFxTrade(command.getTransactionId(), command.getAssignment());

	}

	/**
	 * unAssign FxTrade on Transaction
	 * @param		command UnAssignFxTradeFromTransactionCommand
	 */
	public void unAssignFxTrade( UnAssignFxTradeFromTransactionCommand command ) {

		// --------------------------------------
		// validate the command
		// --------------------------------------
		validator.validate( command );

		// --------------------------------------
		// delegate to the projector
		// --------------------------------------
		projector.unAssignFxTrade(command.getTransactionId());
	}
	
	/**
	 * assign Dispute on Transaction
	 * @param		command AssignDisputeToTransactionCommand
	 */
	public void assignDispute( AssignDisputeToTransactionCommand command ) {
		// --------------------------------------
		// best to validate the command now
		// --------------------------------------
		validator.validate( command );

		// --------------------------------------
		// delegate to the projector
		// --------------------------------------
		projector.assignDispute(command.getTransactionId(), command.getAssignment());

	}

	/**
	 * unAssign Dispute on Transaction
	 * @param		command UnAssignDisputeFromTransactionCommand
	 */
	public void unAssignDispute( UnAssignDisputeFromTransactionCommand command ) {

		// --------------------------------------
		// validate the command
		// --------------------------------------
		validator.validate( command );

		// --------------------------------------
		// delegate to the projector
		// --------------------------------------
		projector.unAssignDispute(command.getTransactionId());
	}
	




//************************************************************************
// Attributes
//************************************************************************
	@Autowired
    private final TransactionEntityProjector projector;
	private final TransactionValidator validator;
	private Transaction transaction 	= null;
	private CurrentIdentity identity			= null;
	private static final Logger LOGGER 			=  LoggerFactory.getLogger(TransactionService.class);
}
